// =============================================================================
// Narwhal Cloud Agent Gateway Protocol  —  v1.0
//
// 概述 / Overview:
//   本协议定义了 Narwhal Cloud 平台与 Agent 节点之间的双向流式 gRPC 通信。
//   Agent 运行于宿主机（VPS 物理节点），负责管理其上所有 VM 的完整生命周期。
//
//   This file defines the bidirectional streaming gRPC protocol between the
//   Narwhal Cloud platform and agent nodes. Each agent manages VMs on a single host.
//
// 连接流程 / Connection Flow:
//   1. Agent 拨号平台 gRPC 端点（支持 TLS）。
//      Agent dials the platform gRPC endpoint (TLS recommended).
//   2. Agent 在 gRPC metadata 中携带身份令牌：
//      Agent sets metadata:  authorization = "Bearer <agent_token>"
//   3. Agent 调用 AgentGateway.Connect() 建立持久双向流。
//      Agent calls AgentGateway.Connect() to open a persistent stream.
//   4. Agent 每 30 秒发送一次 Heartbeat；平台按需下发命令。
//      Agent sends Heartbeat every 30 s; platform sends commands on demand.
//   5. 断线后 Agent 须以指数退避策略重连。
//      On disconnect, agent reconnects with exponential backoff.
//
// 命令确认 / Command Acknowledgement:
//   平台每条下行命令都携带全局唯一的 command_id。
//   Agent 执行完毕（或失败）后，必须通过 CommandResult 回报结果。
//
//   Every platform command carries a unique command_id.
//   Agent MUST respond with CommandResult (success or failure) for every command.
//
// 代码生成 / Code Generation:
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          proto/agent/agent.proto
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VMStatus — VM 运行时状态。
// Agent 只上报运行时状态；到期、下线等生命周期事件由平台侧管理。
type VMStatus int32

const (
	VMStatus_VM_STATUS_UNSPECIFIED VMStatus = 0 // 未知 / unknown
	VMStatus_VM_STATUS_CREATING    VMStatus = 1 // 创建中，等待 Agent 回报 / being provisioned
	VMStatus_VM_STATUS_RUNNING     VMStatus = 2 // 运行中 / running
	VMStatus_VM_STATUS_STOPPED     VMStatus = 3 // 已停止 / stopped / powered off
	VMStatus_VM_STATUS_ERROR       VMStatus = 4 // 异常，需人工介入 / error, needs attention
)

// Enum value maps for VMStatus.
var (
	VMStatus_name = map[int32]string{
		0: "VM_STATUS_UNSPECIFIED",
		1: "VM_STATUS_CREATING",
		2: "VM_STATUS_RUNNING",
		3: "VM_STATUS_STOPPED",
		4: "VM_STATUS_ERROR",
	}
	VMStatus_value = map[string]int32{
		"VM_STATUS_UNSPECIFIED": 0,
		"VM_STATUS_CREATING":    1,
		"VM_STATUS_RUNNING":     2,
		"VM_STATUS_STOPPED":     3,
		"VM_STATUS_ERROR":       4,
	}
)

func (x VMStatus) Enum() *VMStatus {
	p := new(VMStatus)
	*p = x
	return p
}

func (x VMStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[0].Descriptor()
}

func (VMStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[0]
}

func (x VMStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMStatus.Descriptor instead.
func (VMStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

// Protocol — 端口转发所用的传输层协议。
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_TCP         Protocol = 1
	Protocol_PROTOCOL_UDP         Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

// ConsoleEventType — 控制台会话生命周期事件类型。
type ConsoleEventType int32

const (
	ConsoleEventType_CONSOLE_EVENT_UNSPECIFIED  ConsoleEventType = 0
	ConsoleEventType_CONSOLE_EVENT_CONNECTED    ConsoleEventType = 1 // TTY 已成功附接到 VM / TTY attached successfully
	ConsoleEventType_CONSOLE_EVENT_DISCONNECTED ConsoleEventType = 2 // TTY 正常断开 / TTY closed normally
	ConsoleEventType_CONSOLE_EVENT_ERROR        ConsoleEventType = 3 // TTY 异常断开 / TTY closed due to error
)

// Enum value maps for ConsoleEventType.
var (
	ConsoleEventType_name = map[int32]string{
		0: "CONSOLE_EVENT_UNSPECIFIED",
		1: "CONSOLE_EVENT_CONNECTED",
		2: "CONSOLE_EVENT_DISCONNECTED",
		3: "CONSOLE_EVENT_ERROR",
	}
	ConsoleEventType_value = map[string]int32{
		"CONSOLE_EVENT_UNSPECIFIED":  0,
		"CONSOLE_EVENT_CONNECTED":    1,
		"CONSOLE_EVENT_DISCONNECTED": 2,
		"CONSOLE_EVENT_ERROR":        3,
	}
)

func (x ConsoleEventType) Enum() *ConsoleEventType {
	p := new(ConsoleEventType)
	*p = x
	return p
}

func (x ConsoleEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsoleEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[2].Descriptor()
}

func (ConsoleEventType) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[2]
}

func (x ConsoleEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsoleEventType.Descriptor instead.
func (ConsoleEventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

// AgentEnvelope — Agent 发往平台的消息信封。
// 每条消息须携带唯一的 message_id，用于去重和链路追踪。
type AgentEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端生成的唯一消息 ID，建议使用 UUID v4。
	// Client-generated unique message ID (UUID v4 recommended).
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEnvelope_Heartbeat
	//	*AgentEnvelope_CmdResult
	//	*AgentEnvelope_PortFwdList
	//	*AgentEnvelope_ConsoleOutput
	//	*AgentEnvelope_ConsoleEvent
	//	*AgentEnvelope_WgSyncRequest
	Payload       isAgentEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEnvelope) Reset() {
	*x = AgentEnvelope{}
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEnvelope) ProtoMessage() {}

func (x *AgentEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEnvelope.ProtoReflect.Descriptor instead.
func (*AgentEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentEnvelope) GetPayload() isAgentEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEnvelope) GetCmdResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_CmdResult); ok {
			return x.CmdResult
		}
	}
	return nil
}

func (x *AgentEnvelope) GetPortFwdList() *PortForwardList {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_PortFwdList); ok {
			return x.PortFwdList
		}
	}
	return nil
}

func (x *AgentEnvelope) GetConsoleOutput() *ConsoleOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_ConsoleOutput); ok {
			return x.ConsoleOutput
		}
	}
	return nil
}

func (x *AgentEnvelope) GetConsoleEvent() *ConsoleEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_ConsoleEvent); ok {
			return x.ConsoleEvent
		}
	}
	return nil
}

func (x *AgentEnvelope) GetWgSyncRequest() *WGSyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_WgSyncRequest); ok {
			return x.WgSyncRequest
		}
	}
	return nil
}

type isAgentEnvelope_Payload interface {
	isAgentEnvelope_Payload()
}

type AgentEnvelope_Heartbeat struct {
	// --- 周期性上报 / Periodic reports ---
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"` // 心跳，每 30 秒一次 / heartbeat, every 30 s
}

type AgentEnvelope_CmdResult struct {
	// --- 命令回执 / Command acknowledgements ---
	CmdResult *CommandResult `protobuf:"bytes,4,opt,name=cmd_result,json=cmdResult,proto3,oneof"` // 平台命令执行结果 / result of a platform command
}

type AgentEnvelope_PortFwdList struct {
	PortFwdList *PortForwardList `protobuf:"bytes,5,opt,name=port_fwd_list,json=portFwdList,proto3,oneof"` // CmdGetPortForwards 的查询结果 / port-forward query result
}

type AgentEnvelope_ConsoleOutput struct {
	// --- 控制台 / Console TTY ---
	ConsoleOutput *ConsoleOutput `protobuf:"bytes,8,opt,name=console_output,json=consoleOutput,proto3,oneof"` // TTY 原始输出字节 / raw TTY output bytes
}

type AgentEnvelope_ConsoleEvent struct {
	ConsoleEvent *ConsoleEvent `protobuf:"bytes,9,opt,name=console_event,json=consoleEvent,proto3,oneof"` // 控制台会话生命周期事件 / console session lifecycle event
}

type AgentEnvelope_WgSyncRequest struct {
	// --- 专属IP绑定 / Dedicated IP via WireGuard ---
	WgSyncRequest *WGSyncRequest `protobuf:"bytes,11,opt,name=wg_sync_request,json=wgSyncRequest,proto3,oneof"` // Agent 定期主动拉取本机应有的 WG 绑定期望状态 / agent-initiated periodic pull of desired WG bindings for this host
}

func (*AgentEnvelope_Heartbeat) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_CmdResult) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_PortFwdList) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_ConsoleOutput) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_ConsoleEvent) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_WgSyncRequest) isAgentEnvelope_Payload() {}

// Heartbeat — 宿主机实时快照，每 30 秒上报一次。
// 字段变化时才需填写 entry_host / entry_ipv6 / os_images，未变化可留空。
// Fields entry_host, entry_ipv6, and os_images are optional;
// only populate them when the value changes.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- 时间戳 ---
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix 秒 / Unix epoch seconds
	// --- 宿主机实时负载 / Host real-time metrics ---
	CpuPct     float32 `protobuf:"fixed32,2,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`              // CPU 使用率，0–100 / CPU utilization 0–100
	RamUsedMb  int64   `protobuf:"varint,3,opt,name=ram_used_mb,json=ramUsedMb,proto3" json:"ram_used_mb,omitempty"`    // 已用内存 (MB) / used RAM in MB
	DiskUsedGb int64   `protobuf:"varint,4,opt,name=disk_used_gb,json=diskUsedGb,proto3" json:"disk_used_gb,omitempty"` // 已用磁盘 (GB) / used disk in GB
	NetInBps   int64   `protobuf:"varint,5,opt,name=net_in_bps,json=netInBps,proto3" json:"net_in_bps,omitempty"`       // 实时入口速率 (bytes/s) / inbound bandwidth bytes/s
	NetOutBps  int64   `protobuf:"varint,6,opt,name=net_out_bps,json=netOutBps,proto3" json:"net_out_bps,omitempty"`    // 实时出口速率 (bytes/s) / outbound bandwidth bytes/s
	// --- VM 摘要列表（平台对账用）/ VM summary list for reconciliation ---
	Vms []*VMSummary `protobuf:"bytes,7,rep,name=vms,proto3" json:"vms,omitempty"`
	// --- 宿主机接入信息（变化时才填）/ Host endpoint (only when changed) ---
	// IPv4 地址或 DDNS 域名 / IPv4 address or DDNS hostname
	EntryHost string `protobuf:"bytes,8,opt,name=entry_host,json=entryHost,proto3" json:"entry_host,omitempty"`
	// IPv6 地址（可选）/ IPv6 address (optional)
	EntryIpv6 string `protobuf:"bytes,9,opt,name=entry_ipv6,json=entryIpv6,proto3" json:"entry_ipv6,omitempty"`
	// --- 可用 OS 镜像列表（变化时才填）/ Available OS images (only when changed) ---
	OsImages []*OSImageInfo `protobuf:"bytes,10,rep,name=os_images,json=osImages,proto3" json:"os_images,omitempty"`
	// --- 系统负载 / System load averages ---
	Load1  float32 `protobuf:"fixed32,11,opt,name=load1,proto3" json:"load1,omitempty"`   // 1 分钟负载均值 / 1-min load average
	Load5  float32 `protobuf:"fixed32,12,opt,name=load5,proto3" json:"load5,omitempty"`   // 5 分钟负载均值 / 5-min load average
	Load15 float32 `protobuf:"fixed32,13,opt,name=load15,proto3" json:"load15,omitempty"` // 15 分钟负载均值 / 15-min load average
	Uptime int64   `protobuf:"varint,14,opt,name=uptime,proto3" json:"uptime,omitempty"`  // 系统运行时间 (秒) / system uptime in seconds
	// --- 宿主机规格 / Host capacity ---
	Cpus          int32 `protobuf:"varint,15,opt,name=cpus,proto3" json:"cpus,omitempty"`                                        // 逻辑 CPU 核数 / logical CPU count
	RamTotalMb    int64 `protobuf:"varint,16,opt,name=ram_total_mb,json=ramTotalMb,proto3" json:"ram_total_mb,omitempty"`        // 总内存 (MB) / total RAM in MB
	DiskTotalGb   int64 `protobuf:"varint,17,opt,name=disk_total_gb,json=diskTotalGb,proto3" json:"disk_total_gb,omitempty"`     // 总磁盘 (GB) / total disk in GB
	BandwidthMbps int32 `protobuf:"varint,18,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // 总带宽 (Mbps) / total bandwidth in Mbps
	// --- 虚拟化类型 / Virtualization backend ---
	// 已知值：podman（容器）、cloudhv（Cloud Hypervisor KVM）
	// Known values: "podman" (container), "cloudhv" (Cloud Hypervisor / KVM)
	VirtType      string `protobuf:"bytes,19,opt,name=virt_type,json=virtType,proto3" json:"virt_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetCpuPct() float32 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *Heartbeat) GetRamUsedMb() int64 {
	if x != nil {
		return x.RamUsedMb
	}
	return 0
}

func (x *Heartbeat) GetDiskUsedGb() int64 {
	if x != nil {
		return x.DiskUsedGb
	}
	return 0
}

func (x *Heartbeat) GetNetInBps() int64 {
	if x != nil {
		return x.NetInBps
	}
	return 0
}

func (x *Heartbeat) GetNetOutBps() int64 {
	if x != nil {
		return x.NetOutBps
	}
	return 0
}

func (x *Heartbeat) GetVms() []*VMSummary {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *Heartbeat) GetEntryHost() string {
	if x != nil {
		return x.EntryHost
	}
	return ""
}

func (x *Heartbeat) GetEntryIpv6() string {
	if x != nil {
		return x.EntryIpv6
	}
	return ""
}

func (x *Heartbeat) GetOsImages() []*OSImageInfo {
	if x != nil {
		return x.OsImages
	}
	return nil
}

func (x *Heartbeat) GetLoad1() float32 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Heartbeat) GetLoad5() float32 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *Heartbeat) GetLoad15() float32 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *Heartbeat) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Heartbeat) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *Heartbeat) GetRamTotalMb() int64 {
	if x != nil {
		return x.RamTotalMb
	}
	return 0
}

func (x *Heartbeat) GetDiskTotalGb() int64 {
	if x != nil {
		return x.DiskTotalGb
	}
	return 0
}

func (x *Heartbeat) GetBandwidthMbps() int32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *Heartbeat) GetVirtType() string {
	if x != nil {
		return x.VirtType
	}
	return ""
}

// OSImageInfo — 宿主机支持的操作系统镜像条目。
type OSImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // 镜像唯一标识符，对应 CmdCreateVM.os_image / image ID used in CmdCreateVM
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 人类可读名称，例如 "Ubuntu 24.04 LTS" / human-readable display name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSImageInfo) Reset() {
	*x = OSImageInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSImageInfo) ProtoMessage() {}

func (x *OSImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSImageInfo.ProtoReflect.Descriptor instead.
func (*OSImageInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *OSImageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSImageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// VMSummary — 心跳中内嵌的单个 VM 状态摘要，供平台侧对账使用。
type VMSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VmId              string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                                           // VM UUID
	Status            VMStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=agent.VMStatus" json:"status,omitempty"`                              // 当前运行状态 / current runtime status
	CpuPct            float32                `protobuf:"fixed32,3,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`                                   // CPU 使用率，0–100 / CPU utilization 0–100
	RamUsedMb         int64                  `protobuf:"varint,4,opt,name=ram_used_mb,json=ramUsedMb,proto3" json:"ram_used_mb,omitempty"`                         // 已用内存 (MB) / used RAM in MB
	TrafficInBytes    int64                  `protobuf:"varint,5,opt,name=traffic_in_bytes,json=trafficInBytes,proto3" json:"traffic_in_bytes,omitempty"`          // 累计入站流量 (bytes，自创建起) / cumulative inbound traffic since creation
	TrafficOutBytes   int64                  `protobuf:"varint,6,opt,name=traffic_out_bytes,json=trafficOutBytes,proto3" json:"traffic_out_bytes,omitempty"`       // 累计出站流量 (bytes，自创建起) / cumulative outbound traffic since creation
	Ips               []string               `protobuf:"bytes,7,rep,name=ips,proto3" json:"ips,omitempty"`                                                         // VM 的 IP 地址列表（内部 + 公网）/ VM IP addresses (internal and public)
	MonthlyTrafficIn  int64                  `protobuf:"varint,8,opt,name=monthly_traffic_in,json=monthlyTrafficIn,proto3" json:"monthly_traffic_in,omitempty"`    // 本月累计入站流量 (bytes) / current month inbound traffic
	MonthlyTrafficOut int64                  `protobuf:"varint,9,opt,name=monthly_traffic_out,json=monthlyTrafficOut,proto3" json:"monthly_traffic_out,omitempty"` // 本月累计出站流量 (bytes) / current month outbound traffic
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VMSummary) Reset() {
	*x = VMSummary{}
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMSummary) ProtoMessage() {}

func (x *VMSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMSummary.ProtoReflect.Descriptor instead.
func (*VMSummary) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *VMSummary) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMSummary) GetStatus() VMStatus {
	if x != nil {
		return x.Status
	}
	return VMStatus_VM_STATUS_UNSPECIFIED
}

func (x *VMSummary) GetCpuPct() float32 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *VMSummary) GetRamUsedMb() int64 {
	if x != nil {
		return x.RamUsedMb
	}
	return 0
}

func (x *VMSummary) GetTrafficInBytes() int64 {
	if x != nil {
		return x.TrafficInBytes
	}
	return 0
}

func (x *VMSummary) GetTrafficOutBytes() int64 {
	if x != nil {
		return x.TrafficOutBytes
	}
	return 0
}

func (x *VMSummary) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *VMSummary) GetMonthlyTrafficIn() int64 {
	if x != nil {
		return x.MonthlyTrafficIn
	}
	return 0
}

func (x *VMSummary) GetMonthlyTrafficOut() int64 {
	if x != nil {
		return x.MonthlyTrafficOut
	}
	return 0
}

// CommandResult — Agent 对平台命令的执行结果回报。
// 每条 PlatformEnvelope 必须有且仅有一条对应的 CommandResult。
// Every PlatformEnvelope command MUST be acknowledged with exactly one CommandResult.
type CommandResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 对应 PlatformEnvelope.command_id / echoes PlatformEnvelope.command_id
	Success   bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                     // 执行是否成功 / whether the command succeeded
	Error     string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // 失败原因（success=false 时填写）/ error message when success=false
	// JSON 编码的附加数据，具体结构见各命令说明。
	// JSON-encoded extra data; schema depends on the command type.
	// Currently used by: CmdGetPortForwards (returns PortForwardEntry[])
	Data          []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// PortForwardList — CmdGetPortForwards 的查询结果，通过 AgentEnvelope 回传。
// 注意：此消息通过专用的 port_fwd_list 字段传输，而非 CommandResult.data。
type PortForwardList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 对应 CmdGetPortForwards 的 command_id
	Entries       []*PortForwardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardList) Reset() {
	*x = PortForwardList{}
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardList) ProtoMessage() {}

func (x *PortForwardList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardList.ProtoReflect.Descriptor instead.
func (*PortForwardList) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PortForwardList) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PortForwardList) GetEntries() []*PortForwardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// PortForwardEntry — 单条端口转发规则。
type PortForwardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                  // VM UUID
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=agent.Protocol" json:"protocol,omitempty"` // 协议 / protocol
	HostPort      int32                  `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`     // 宿主机端口 / host (external) port
	GuestPort     int32                  `protobuf:"varint,4,opt,name=guest_port,json=guestPort,proto3" json:"guest_port,omitempty"`  // VM 内部端口 / guest (VM-internal) port
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                // 备注，例如 "SSH" / description e.g. "SSH"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardEntry) Reset() {
	*x = PortForwardEntry{}
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardEntry) ProtoMessage() {}

func (x *PortForwardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardEntry.ProtoReflect.Descriptor instead.
func (*PortForwardEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *PortForwardEntry) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *PortForwardEntry) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *PortForwardEntry) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortForwardEntry) GetGuestPort() int32 {
	if x != nil {
		return x.GuestPort
	}
	return 0
}

func (x *PortForwardEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ConsoleOutput — Agent 将 VM TTY 的原始输出转发给平台。
// 平台再通过 WebSocket 推送给用户浏览器。
type ConsoleOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话唯一 ID，与 CmdConsoleOpen.session_id 对应
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // TTY 原始输出字节（stdout / stderr 混合）/ raw TTY output bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleOutput) Reset() {
	*x = ConsoleOutput{}
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleOutput) ProtoMessage() {}

func (x *ConsoleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleOutput.ProtoReflect.Descriptor instead.
func (*ConsoleOutput) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ConsoleOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsoleOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// ConsoleEvent — 控制台会话生命周期事件，由 Agent 上报给平台。
type ConsoleEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`   // 会话唯一 ID / session ID
	Type      ConsoleEventType       `protobuf:"varint,2,opt,name=type,proto3,enum=agent.ConsoleEventType" json:"type,omitempty"` // 事件类型 / event type
	// DISCONNECTED 或 ERROR 时填写原因描述。
	// Reason string for DISCONNECTED or ERROR events.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleEvent) Reset() {
	*x = ConsoleEvent{}
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleEvent) ProtoMessage() {}

func (x *ConsoleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleEvent.ProtoReflect.Descriptor instead.
func (*ConsoleEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ConsoleEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConsoleEvent) GetType() ConsoleEventType {
	if x != nil {
		return x.Type
	}
	return ConsoleEventType_CONSOLE_EVENT_UNSPECIFIED
}

func (x *ConsoleEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PlatformEnvelope — 平台发往 Agent 的命令信封。
// Agent 完成执行后须通过 CommandResult 确认每一条命令。
// Agent MUST acknowledge every command with a CommandResult.
type PlatformEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 平台生成的全局唯一命令 ID（持久化到数据库，用于断线重放）。
	// Globally unique command ID generated by the platform (persisted to DB for replay).
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PlatformEnvelope_CreateVm
	//	*PlatformEnvelope_StartVm
	//	*PlatformEnvelope_StopVm
	//	*PlatformEnvelope_RestartVm
	//	*PlatformEnvelope_DeleteVm
	//	*PlatformEnvelope_ReinstallVm
	//	*PlatformEnvelope_ResetPassword
	//	*PlatformEnvelope_SetPortFwd
	//	*PlatformEnvelope_DelPortFwd
	//	*PlatformEnvelope_GetPortFwds
	//	*PlatformEnvelope_Ping
	//	*PlatformEnvelope_ConsoleOpen
	//	*PlatformEnvelope_ConsoleInput
	//	*PlatformEnvelope_ConsoleResize
	//	*PlatformEnvelope_ConsoleClose
	//	*PlatformEnvelope_WgSyncResponse
	Payload       isPlatformEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformEnvelope) Reset() {
	*x = PlatformEnvelope{}
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformEnvelope) ProtoMessage() {}

func (x *PlatformEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformEnvelope.ProtoReflect.Descriptor instead.
func (*PlatformEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *PlatformEnvelope) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PlatformEnvelope) GetPayload() isPlatformEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PlatformEnvelope) GetCreateVm() *CmdCreateVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_CreateVm); ok {
			return x.CreateVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetStartVm() *CmdStartVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_StartVm); ok {
			return x.StartVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetStopVm() *CmdStopVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_StopVm); ok {
			return x.StopVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetRestartVm() *CmdRestartVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_RestartVm); ok {
			return x.RestartVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetDeleteVm() *CmdDeleteVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_DeleteVm); ok {
			return x.DeleteVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetReinstallVm() *CmdReinstallVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_ReinstallVm); ok {
			return x.ReinstallVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetResetPassword() *CmdResetPassword {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_ResetPassword); ok {
			return x.ResetPassword
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetSetPortFwd() *CmdSetPortForward {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_SetPortFwd); ok {
			return x.SetPortFwd
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetDelPortFwd() *CmdDelPortForward {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_DelPortFwd); ok {
			return x.DelPortFwd
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetGetPortFwds() *CmdGetPortForwards {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_GetPortFwds); ok {
			return x.GetPortFwds
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetConsoleOpen() *CmdConsoleOpen {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_ConsoleOpen); ok {
			return x.ConsoleOpen
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetConsoleInput() *CmdConsoleInput {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_ConsoleInput); ok {
			return x.ConsoleInput
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetConsoleResize() *CmdConsoleResize {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_ConsoleResize); ok {
			return x.ConsoleResize
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetConsoleClose() *CmdConsoleClose {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_ConsoleClose); ok {
			return x.ConsoleClose
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetWgSyncResponse() *WGSyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_WgSyncResponse); ok {
			return x.WgSyncResponse
		}
	}
	return nil
}

type isPlatformEnvelope_Payload interface {
	isPlatformEnvelope_Payload()
}

type PlatformEnvelope_CreateVm struct {
	// --- VM 生命周期 / VM lifecycle ---
	CreateVm *CmdCreateVM `protobuf:"bytes,2,opt,name=create_vm,json=createVm,proto3,oneof"` // 创建 VM / provision a new VM
}

type PlatformEnvelope_StartVm struct {
	StartVm *CmdStartVM `protobuf:"bytes,3,opt,name=start_vm,json=startVm,proto3,oneof"` // 启动 VM / power on
}

type PlatformEnvelope_StopVm struct {
	StopVm *CmdStopVM `protobuf:"bytes,4,opt,name=stop_vm,json=stopVm,proto3,oneof"` // 关闭 VM / power off
}

type PlatformEnvelope_RestartVm struct {
	RestartVm *CmdRestartVM `protobuf:"bytes,5,opt,name=restart_vm,json=restartVm,proto3,oneof"` // 重启 VM / reboot
}

type PlatformEnvelope_DeleteVm struct {
	DeleteVm *CmdDeleteVM `protobuf:"bytes,6,opt,name=delete_vm,json=deleteVm,proto3,oneof"` // 销毁 VM（不可恢复）/ destroy VM (irreversible)
}

type PlatformEnvelope_ReinstallVm struct {
	ReinstallVm *CmdReinstallVM `protobuf:"bytes,13,opt,name=reinstall_vm,json=reinstallVm,proto3,oneof"` // 重装系统 / reinstall OS
}

type PlatformEnvelope_ResetPassword struct {
	// --- VM 配置 / VM configuration ---
	ResetPassword *CmdResetPassword `protobuf:"bytes,7,opt,name=reset_password,json=resetPassword,proto3,oneof"` // 重置 root 密码 / reset root password
}

type PlatformEnvelope_SetPortFwd struct {
	// --- 端口转发 / Port forwarding ---
	SetPortFwd *CmdSetPortForward `protobuf:"bytes,8,opt,name=set_port_fwd,json=setPortFwd,proto3,oneof"` // 新增端口转发规则 / add port-forward rule
}

type PlatformEnvelope_DelPortFwd struct {
	DelPortFwd *CmdDelPortForward `protobuf:"bytes,9,opt,name=del_port_fwd,json=delPortFwd,proto3,oneof"` // 删除端口转发规则 / remove port-forward rule
}

type PlatformEnvelope_GetPortFwds struct {
	GetPortFwds *CmdGetPortForwards `protobuf:"bytes,14,opt,name=get_port_fwds,json=getPortFwds,proto3,oneof"` // 查询端口转发规则列表 / list port-forward rules
}

type PlatformEnvelope_Ping struct {
	// --- 保活 / Keep-alive ---
	Ping *Ping `protobuf:"bytes,15,opt,name=ping,proto3,oneof"` // 服务端保活，Agent 收到后无需回复 / no-op, no CommandResult needed
}

type PlatformEnvelope_ConsoleOpen struct {
	// --- 控制台 TTY / Console TTY ---
	ConsoleOpen *CmdConsoleOpen `protobuf:"bytes,16,opt,name=console_open,json=consoleOpen,proto3,oneof"` // 打开控制台会话 / open console session
}

type PlatformEnvelope_ConsoleInput struct {
	ConsoleInput *CmdConsoleInput `protobuf:"bytes,17,opt,name=console_input,json=consoleInput,proto3,oneof"` // 转发键盘输入 / forward keyboard input
}

type PlatformEnvelope_ConsoleResize struct {
	ConsoleResize *CmdConsoleResize `protobuf:"bytes,18,opt,name=console_resize,json=consoleResize,proto3,oneof"` // 调整终端尺寸 / resize terminal
}

type PlatformEnvelope_ConsoleClose struct {
	ConsoleClose *CmdConsoleClose `protobuf:"bytes,19,opt,name=console_close,json=consoleClose,proto3,oneof"` // 关闭控制台会话 / close console session
}

type PlatformEnvelope_WgSyncResponse struct {
	// --- 专属IP绑定 / Dedicated IP via WireGuard ---
	WgSyncResponse *WGSyncResponse `protobuf:"bytes,23,opt,name=wg_sync_response,json=wgSyncResponse,proto3,oneof"` // 响应 Agent 的 WGSyncRequest：本机当前应有的全部 WG 绑定 / response to the agent's WGSyncRequest: the full set of WG bindings that should currently exist on this host
}

func (*PlatformEnvelope_CreateVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_StartVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_StopVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_RestartVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_DeleteVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_ReinstallVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_ResetPassword) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_SetPortFwd) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_DelPortFwd) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_GetPortFwds) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_Ping) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_ConsoleOpen) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_ConsoleInput) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_ConsoleResize) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_ConsoleClose) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_WgSyncResponse) isPlatformEnvelope_Payload() {}

// CmdCreateVM — 在宿主机上创建并启动一台新的 VM。
// 成功后 Agent 须将 VM 状态变更为 VM_STATUS_RUNNING 并在下次心跳中上报。
type CmdCreateVM struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	VmId   string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`        // 平台分配的 VM UUID，Agent 以此作为本地标识符
	Cpu    int32                  `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`                     // CPU 核数 / vCPU count
	RamMb  int64                  `protobuf:"varint,3,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`    // 内存 (MB) / RAM in MB
	DiskGb int64                  `protobuf:"varint,4,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"` // 磁盘 (GB) / disk in GB
	// 带宽限速 (Mbps)；0 表示不限速。/ bandwidth limit in Mbps; 0 = unlimited
	BandwidthMbps int32 `protobuf:"varint,5,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"`
	// 操作系统镜像 ID，须与 Heartbeat.os_images 中的 id 一致。
	// OS image ID; must match an entry from Heartbeat.os_images.
	OsImage string `protobuf:"bytes,6,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	// root 初始密码（明文），Agent 负责写入系统。
	// Initial root password (plaintext); agent writes it into the VM.
	RootPassword  string `protobuf:"bytes,7,opt,name=root_password,json=rootPassword,proto3" json:"root_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdCreateVM) Reset() {
	*x = CmdCreateVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdCreateVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdCreateVM) ProtoMessage() {}

func (x *CmdCreateVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdCreateVM.ProtoReflect.Descriptor instead.
func (*CmdCreateVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CmdCreateVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdCreateVM) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CmdCreateVM) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *CmdCreateVM) GetDiskGb() int64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *CmdCreateVM) GetBandwidthMbps() int32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *CmdCreateVM) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *CmdCreateVM) GetRootPassword() string {
	if x != nil {
		return x.RootPassword
	}
	return ""
}

// CmdStartVM — 启动一台处于停止状态的 VM。
type CmdStartVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdStartVM) Reset() {
	*x = CmdStartVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdStartVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStartVM) ProtoMessage() {}

func (x *CmdStartVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStartVM.ProtoReflect.Descriptor instead.
func (*CmdStartVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CmdStartVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// CmdStopVM — 关闭 VM。
type CmdStopVM struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	VmId  string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// true = 强制断电（等同于拔电源），false = 优雅关机（发送 ACPI 信号）。
	// true = force power off (hard cut); false = graceful shutdown (ACPI signal).
	Force         bool `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdStopVM) Reset() {
	*x = CmdStopVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdStopVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStopVM) ProtoMessage() {}

func (x *CmdStopVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStopVM.ProtoReflect.Descriptor instead.
func (*CmdStopVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CmdStopVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdStopVM) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// CmdRestartVM — 重启 VM（优雅重启；如需强制，先发 CmdStopVM force=true 再发 CmdStartVM）。
type CmdRestartVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdRestartVM) Reset() {
	*x = CmdRestartVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRestartVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRestartVM) ProtoMessage() {}

func (x *CmdRestartVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRestartVM.ProtoReflect.Descriptor instead.
func (*CmdRestartVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *CmdRestartVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// CmdDeleteVM — 永久销毁 VM，释放全部资源（磁盘、IP、端口转发等）。
// 此操作不可恢复，执行前平台已完成计费清算。
// This is irreversible. Platform performs billing settlement before issuing this command.
type CmdDeleteVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdDeleteVM) Reset() {
	*x = CmdDeleteVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdDeleteVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdDeleteVM) ProtoMessage() {}

func (x *CmdDeleteVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdDeleteVM.ProtoReflect.Descriptor instead.
func (*CmdDeleteVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CmdDeleteVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// CmdReinstallVM — 重装 VM 操作系统，原磁盘数据将被清除。
// Agent 应先停止 VM，然后用新镜像重新创建，再启动。
// Agent should stop the VM, reprovision with the new image, then start it.
type CmdReinstallVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                             // VM UUID
	OsImage       string                 `protobuf:"bytes,2,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`                    // 新操作系统镜像 ID / new OS image ID
	RootPassword  string                 `protobuf:"bytes,3,opt,name=root_password,json=rootPassword,proto3" json:"root_password,omitempty"`     // 新 root 密码 / new root password (plaintext)
	Cpu           int32                  `protobuf:"varint,4,opt,name=cpu,proto3" json:"cpu,omitempty"`                                          // CPU 核数（可能随套餐变更）/ vCPU count (may change with plan)
	RamMb         int64                  `protobuf:"varint,5,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`                         // 内存 (MB)
	DiskGb        int64                  `protobuf:"varint,6,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`                      // 磁盘 (GB)
	BandwidthMbps int32                  `protobuf:"varint,7,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // 带宽限速 (Mbps)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdReinstallVM) Reset() {
	*x = CmdReinstallVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdReinstallVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdReinstallVM) ProtoMessage() {}

func (x *CmdReinstallVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdReinstallVM.ProtoReflect.Descriptor instead.
func (*CmdReinstallVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CmdReinstallVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdReinstallVM) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *CmdReinstallVM) GetRootPassword() string {
	if x != nil {
		return x.RootPassword
	}
	return ""
}

func (x *CmdReinstallVM) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CmdReinstallVM) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *CmdReinstallVM) GetDiskGb() int64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *CmdReinstallVM) GetBandwidthMbps() int32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

// CmdResetPassword — 重置 VM 的 root 账户密码。
// Agent 需在 VM 运行时（或通过磁盘挂载方式）写入新密码。
type CmdResetPassword struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	VmId  string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	// 新密码（明文），Agent 负责写入虚拟机内部（如通过 cloud-init / chroot）。
	// New root password (plaintext); agent writes it into the VM.
	NewPassword   string `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdResetPassword) Reset() {
	*x = CmdResetPassword{}
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdResetPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdResetPassword) ProtoMessage() {}

func (x *CmdResetPassword) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdResetPassword.ProtoReflect.Descriptor instead.
func (*CmdResetPassword) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CmdResetPassword) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdResetPassword) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// CmdSetPortForward — 在宿主机上为指定 VM 添加一条端口转发规则。
// 宿主机端口范围建议限制在 1024–65535。
// Recommended host port range: 1024–65535.
type CmdSetPortForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                  // VM UUID
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=agent.Protocol" json:"protocol,omitempty"` // 协议 / protocol
	HostPort      int32                  `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`     // 宿主机（外部）端口 / host (external) port
	GuestPort     int32                  `protobuf:"varint,4,opt,name=guest_port,json=guestPort,proto3" json:"guest_port,omitempty"`  // VM 内部端口 / guest (VM-internal) port
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                // 备注，例如 "SSH 22" / description e.g. "SSH 22"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdSetPortForward) Reset() {
	*x = CmdSetPortForward{}
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdSetPortForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdSetPortForward) ProtoMessage() {}

func (x *CmdSetPortForward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdSetPortForward.ProtoReflect.Descriptor instead.
func (*CmdSetPortForward) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CmdSetPortForward) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdSetPortForward) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *CmdSetPortForward) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *CmdSetPortForward) GetGuestPort() int32 {
	if x != nil {
		return x.GuestPort
	}
	return 0
}

func (x *CmdSetPortForward) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CmdDelPortForward — 删除一条已有的端口转发规则。
type CmdDelPortForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=agent.Protocol" json:"protocol,omitempty"`
	HostPort      int32                  `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"` // 要删除的宿主机端口 / host port to remove
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdDelPortForward) Reset() {
	*x = CmdDelPortForward{}
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdDelPortForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdDelPortForward) ProtoMessage() {}

func (x *CmdDelPortForward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdDelPortForward.ProtoReflect.Descriptor instead.
func (*CmdDelPortForward) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *CmdDelPortForward) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdDelPortForward) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *CmdDelPortForward) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

// CmdGetPortForwards — 查询某 VM 当前所有端口转发规则。
// Agent 须通过 AgentEnvelope.port_fwd_list 回传结果（而非 CommandResult.data）。
// Agent responds via AgentEnvelope.port_fwd_list (not via CommandResult.data).
type CmdGetPortForwards struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdGetPortForwards) Reset() {
	*x = CmdGetPortForwards{}
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdGetPortForwards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetPortForwards) ProtoMessage() {}

func (x *CmdGetPortForwards) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetPortForwards.ProtoReflect.Descriptor instead.
func (*CmdGetPortForwards) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *CmdGetPortForwards) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// Ping — 平台定期下发，用于维持 gRPC 连接活跃（防止代理层超时断开）。
// Agent 收到后无需发送 CommandResult。
// Agent does NOT need to send a CommandResult in response to Ping.
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{20}
}

// CmdConsoleOpen — 请求 Agent 打开一个交互式控制台会话并附接到指定 VM 的 TTY。
// Agent 成功附接后须上报 ConsoleEvent{type=CONNECTED}；失败则上报 DISCONNECTED 或 ERROR。
// On success, agent reports ConsoleEvent{type=CONNECTED}.
// On failure, agent reports ConsoleEvent{type=ERROR} with a reason string.
type CmdConsoleOpen struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	VmId  string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // 目标 VM UUID / target VM UUID
	// 平台生成的会话唯一 ID，后续所有控制台帧均以此关联。
	// Platform-generated unique session ID; all subsequent console frames reference this.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"` // 初始终端宽度（字符列数）/ initial terminal width in columns
	Rows          uint32 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"` // 初始终端高度（字符行数）/ initial terminal height in rows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdConsoleOpen) Reset() {
	*x = CmdConsoleOpen{}
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdConsoleOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdConsoleOpen) ProtoMessage() {}

func (x *CmdConsoleOpen) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdConsoleOpen.ProtoReflect.Descriptor instead.
func (*CmdConsoleOpen) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *CmdConsoleOpen) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdConsoleOpen) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CmdConsoleOpen) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CmdConsoleOpen) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// CmdConsoleInput — 将用户键盘输入转发到 VM 的 TTY stdin。
type CmdConsoleInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // stdin 原始字节（含控制字符）/ raw stdin bytes (including control chars)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdConsoleInput) Reset() {
	*x = CmdConsoleInput{}
	mi := &file_proto_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdConsoleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdConsoleInput) ProtoMessage() {}

func (x *CmdConsoleInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdConsoleInput.ProtoReflect.Descriptor instead.
func (*CmdConsoleInput) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *CmdConsoleInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CmdConsoleInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// CmdConsoleResize — 通知 Agent 调整 VM TTY 的终端尺寸（ioctl TIOCSWINSZ）。
type CmdConsoleResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"` // 新宽度（列）/ new terminal width in columns
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"` // 新高度（行）/ new terminal height in rows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdConsoleResize) Reset() {
	*x = CmdConsoleResize{}
	mi := &file_proto_agent_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdConsoleResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdConsoleResize) ProtoMessage() {}

func (x *CmdConsoleResize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdConsoleResize.ProtoReflect.Descriptor instead.
func (*CmdConsoleResize) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{23}
}

func (x *CmdConsoleResize) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CmdConsoleResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *CmdConsoleResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

// CmdConsoleClose — 请求 Agent 关闭并清理指定控制台会话。
// Agent 应在断开 TTY 后上报 ConsoleEvent{type=DISCONNECTED}。
// Agent should report ConsoleEvent{type=DISCONNECTED} after closing the TTY.
type CmdConsoleClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdConsoleClose) Reset() {
	*x = CmdConsoleClose{}
	mi := &file_proto_agent_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdConsoleClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdConsoleClose) ProtoMessage() {}

func (x *CmdConsoleClose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdConsoleClose.ProtoReflect.Descriptor instead.
func (*CmdConsoleClose) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{24}
}

func (x *CmdConsoleClose) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// WGSyncRequest — Agent 主动发起，请求平台下发本机当前应有的 WG 绑定期望状态。
// WGSyncRequest — agent-initiated request for the desired WG binding state of this host.
type WGSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Agent 生成的唯一请求 ID / agent-generated unique request ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WGSyncRequest) Reset() {
	*x = WGSyncRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WGSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WGSyncRequest) ProtoMessage() {}

func (x *WGSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WGSyncRequest.ProtoReflect.Descriptor instead.
func (*WGSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{25}
}

func (x *WGSyncRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// WGSyncResponse — WGSyncRequest 的响应：该宿主机当前应当存在的全部绑定。
// 不在列表中的、Agent 本地已有的绑定应当被删除（幂等收敛，而非增量指令）。
//
// WGSyncResponse — the response to WGSyncRequest: the full set of bindings
// that should currently exist on this host. Any binding the agent currently
// holds locally that is NOT in this list should be removed (idempotent
// reconciliation to a full desired-state snapshot, not an incremental diff).
type WGSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 对应 WGSyncRequest.request_id / echoes WGSyncRequest.request_id
	Bindings      []*WGBindDesired       `protobuf:"bytes,2,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WGSyncResponse) Reset() {
	*x = WGSyncResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WGSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WGSyncResponse) ProtoMessage() {}

func (x *WGSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WGSyncResponse.ProtoReflect.Descriptor instead.
func (*WGSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{26}
}

func (x *WGSyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WGSyncResponse) GetBindings() []*WGBindDesired {
	if x != nil {
		return x.Bindings
	}
	return nil
}

// WGBindDesired — 单条 WireGuard 绑定的期望配置：把平台侧 VyOS 网关上已创建好
// 的 Peer 的私钥与网关连接信息交给 Agent；Agent 是该 Peer 的主动拨号端，将这条
// 隧道地址的流量转发进目标 VM（复用 Agent 已有的 wgbind.Manager 实现）。按
// resource_id 寻址：Agent 应在本地已有同 resource_id 的绑定时原地更新，否则新建。
//
// WGBindDesired — desired configuration for a single WireGuard binding: the
// private key and gateway connection info for a peer already created on the
// platform-side VyOS gateway, handed to the agent, which becomes the active
// dialer for this peer and forwards traffic addressed to the tunnel address
// into the target VM (reusing the agent's existing wgbind.Manager). Addressed
// by resource_id: the agent should update an existing local binding with the
// same resource_id in place, or create one if none exists.
type WGBindDesired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                              // 目标 VM UUID / target VM UUID
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`            // 平台 IPResource UUID，Agent 侧用作寻址/幂等 key / platform IPResource UUID, used as the agent-side addressing/idempotency key
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`            // 本端(Agent侧)私钥，base64，由平台生成 / local (agent-side) private key, base64, platform-generated
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                                    // 隧道地址(即用户租用的公网IP)，可带前缀 / tunnel address (the rented public IP), may include a prefix length
	PeerPublicKey string                 `protobuf:"bytes,5,opt,name=peer_public_key,json=peerPublicKey,proto3" json:"peer_public_key,omitempty"` // 对端(VyOS网关WG接口)公钥，base64 / remote (VyOS gateway WG interface) public key, base64
	PresharedKey  string                 `protobuf:"bytes,6,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`      // 预共享密钥，base64，可为空 / preshared key, base64, may be empty
	Endpoint      string                 `protobuf:"bytes,7,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                  // 对端 host:port（网关WG监听地址）/ remote endpoint host:port (gateway's WG listen address)
	AllowedIps    []string               `protobuf:"bytes,8,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`            // 允许的网段，通常为该资源自身地址 / allowed IPs, usually just this resource's own address
	KeepaliveSec  int32                  `protobuf:"varint,9,opt,name=keepalive_sec,json=keepaliveSec,proto3" json:"keepalive_sec,omitempty"`     // PersistentKeepalive 秒数，建议 25 / persistent keepalive interval in seconds, 25 recommended
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WGBindDesired) Reset() {
	*x = WGBindDesired{}
	mi := &file_proto_agent_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WGBindDesired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WGBindDesired) ProtoMessage() {}

func (x *WGBindDesired) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WGBindDesired.ProtoReflect.Descriptor instead.
func (*WGBindDesired) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{27}
}

func (x *WGBindDesired) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *WGBindDesired) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *WGBindDesired) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *WGBindDesired) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WGBindDesired) GetPeerPublicKey() string {
	if x != nil {
		return x.PeerPublicKey
	}
	return ""
}

func (x *WGBindDesired) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *WGBindDesired) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *WGBindDesired) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *WGBindDesired) GetKeepaliveSec() int32 {
	if x != nil {
		return x.KeepaliveSec
	}
	return 0
}

var File_proto_agent_agent_proto protoreflect.FileDescriptor

const file_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent/agent.proto\x12\x05agent\"\xa1\x03\n" +
	"\rAgentEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x120\n" +
	"\theartbeat\x18\x02 \x01(\v2\x10.agent.HeartbeatH\x00R\theartbeat\x125\n" +
	"\n" +
	"cmd_result\x18\x04 \x01(\v2\x14.agent.CommandResultH\x00R\tcmdResult\x12<\n" +
	"\rport_fwd_list\x18\x05 \x01(\v2\x16.agent.PortForwardListH\x00R\vportFwdList\x12=\n" +
	"\x0econsole_output\x18\b \x01(\v2\x14.agent.ConsoleOutputH\x00R\rconsoleOutput\x12:\n" +
	"\rconsole_event\x18\t \x01(\v2\x13.agent.ConsoleEventH\x00R\fconsoleEvent\x12>\n" +
	"\x0fwg_sync_request\x18\v \x01(\v2\x14.agent.WGSyncRequestH\x00R\rwgSyncRequestB\t\n" +
	"\apayloadJ\x04\b\n" +
	"\x10\v\"\xcf\x04\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\acpu_pct\x18\x02 \x01(\x02R\x06cpuPct\x12\x1e\n" +
	"\vram_used_mb\x18\x03 \x01(\x03R\tramUsedMb\x12 \n" +
	"\fdisk_used_gb\x18\x04 \x01(\x03R\n" +
	"diskUsedGb\x12\x1c\n" +
	"\n" +
	"net_in_bps\x18\x05 \x01(\x03R\bnetInBps\x12\x1e\n" +
	"\vnet_out_bps\x18\x06 \x01(\x03R\tnetOutBps\x12\"\n" +
	"\x03vms\x18\a \x03(\v2\x10.agent.VMSummaryR\x03vms\x12\x1d\n" +
	"\n" +
	"entry_host\x18\b \x01(\tR\tentryHost\x12\x1d\n" +
	"\n" +
	"entry_ipv6\x18\t \x01(\tR\tentryIpv6\x12/\n" +
	"\tos_images\x18\n" +
	" \x03(\v2\x12.agent.OSImageInfoR\bosImages\x12\x14\n" +
	"\x05load1\x18\v \x01(\x02R\x05load1\x12\x14\n" +
	"\x05load5\x18\f \x01(\x02R\x05load5\x12\x16\n" +
	"\x06load15\x18\r \x01(\x02R\x06load15\x12\x16\n" +
	"\x06uptime\x18\x0e \x01(\x03R\x06uptime\x12\x12\n" +
	"\x04cpus\x18\x0f \x01(\x05R\x04cpus\x12 \n" +
	"\fram_total_mb\x18\x10 \x01(\x03R\n" +
	"ramTotalMb\x12\"\n" +
	"\rdisk_total_gb\x18\x11 \x01(\x03R\vdiskTotalGb\x12%\n" +
	"\x0ebandwidth_mbps\x18\x12 \x01(\x05R\rbandwidthMbps\x12\x1b\n" +
	"\tvirt_type\x18\x13 \x01(\tR\bvirtType\"1\n" +
	"\vOSImageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc8\x02\n" +
	"\tVMSummary\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.agent.VMStatusR\x06status\x12\x17\n" +
	"\acpu_pct\x18\x03 \x01(\x02R\x06cpuPct\x12\x1e\n" +
	"\vram_used_mb\x18\x04 \x01(\x03R\tramUsedMb\x12(\n" +
	"\x10traffic_in_bytes\x18\x05 \x01(\x03R\x0etrafficInBytes\x12*\n" +
	"\x11traffic_out_bytes\x18\x06 \x01(\x03R\x0ftrafficOutBytes\x12\x10\n" +
	"\x03ips\x18\a \x03(\tR\x03ips\x12,\n" +
	"\x12monthly_traffic_in\x18\b \x01(\x03R\x10monthlyTrafficIn\x12.\n" +
	"\x13monthly_traffic_out\x18\t \x01(\x03R\x11monthlyTrafficOut\"r\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"c\n" +
	"\x0fPortForwardList\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x121\n" +
	"\aentries\x18\x02 \x03(\v2\x17.agent.PortForwardEntryR\aentries\"\xb2\x01\n" +
	"\x10PortForwardEntry\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12+\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x0f.agent.ProtocolR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\x05R\bhostPort\x12\x1d\n" +
	"\n" +
	"guest_port\x18\x04 \x01(\x05R\tguestPort\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"B\n" +
	"\rConsoleOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"r\n" +
	"\fConsoleEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.agent.ConsoleEventTypeR\x04type\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xe4\a\n" +
	"\x10PlatformEnvelope\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x121\n" +
	"\tcreate_vm\x18\x02 \x01(\v2\x12.agent.CmdCreateVMH\x00R\bcreateVm\x12.\n" +
	"\bstart_vm\x18\x03 \x01(\v2\x11.agent.CmdStartVMH\x00R\astartVm\x12+\n" +
	"\astop_vm\x18\x04 \x01(\v2\x10.agent.CmdStopVMH\x00R\x06stopVm\x124\n" +
	"\n" +
	"restart_vm\x18\x05 \x01(\v2\x13.agent.CmdRestartVMH\x00R\trestartVm\x121\n" +
	"\tdelete_vm\x18\x06 \x01(\v2\x12.agent.CmdDeleteVMH\x00R\bdeleteVm\x12:\n" +
	"\freinstall_vm\x18\r \x01(\v2\x15.agent.CmdReinstallVMH\x00R\vreinstallVm\x12@\n" +
	"\x0ereset_password\x18\a \x01(\v2\x17.agent.CmdResetPasswordH\x00R\rresetPassword\x12<\n" +
	"\fset_port_fwd\x18\b \x01(\v2\x18.agent.CmdSetPortForwardH\x00R\n" +
	"setPortFwd\x12<\n" +
	"\fdel_port_fwd\x18\t \x01(\v2\x18.agent.CmdDelPortForwardH\x00R\n" +
	"delPortFwd\x12?\n" +
	"\rget_port_fwds\x18\x0e \x01(\v2\x19.agent.CmdGetPortForwardsH\x00R\vgetPortFwds\x12!\n" +
	"\x04ping\x18\x0f \x01(\v2\v.agent.PingH\x00R\x04ping\x12:\n" +
	"\fconsole_open\x18\x10 \x01(\v2\x15.agent.CmdConsoleOpenH\x00R\vconsoleOpen\x12=\n" +
	"\rconsole_input\x18\x11 \x01(\v2\x16.agent.CmdConsoleInputH\x00R\fconsoleInput\x12@\n" +
	"\x0econsole_resize\x18\x12 \x01(\v2\x17.agent.CmdConsoleResizeH\x00R\rconsoleResize\x12=\n" +
	"\rconsole_close\x18\x13 \x01(\v2\x16.agent.CmdConsoleCloseH\x00R\fconsoleClose\x12A\n" +
	"\x10wg_sync_response\x18\x17 \x01(\v2\x15.agent.WGSyncResponseH\x00R\x0ewgSyncResponseB\t\n" +
	"\apayloadJ\x04\b\x14\x10\x15J\x04\b\x15\x10\x16J\x04\b\x16\x10\x17\"\xcb\x01\n" +
	"\vCmdCreateVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x05R\x03cpu\x12\x15\n" +
	"\x06ram_mb\x18\x03 \x01(\x03R\x05ramMb\x12\x17\n" +
	"\adisk_gb\x18\x04 \x01(\x03R\x06diskGb\x12%\n" +
	"\x0ebandwidth_mbps\x18\x05 \x01(\x05R\rbandwidthMbps\x12\x19\n" +
	"\bos_image\x18\x06 \x01(\tR\aosImage\x12#\n" +
	"\rroot_password\x18\a \x01(\tR\frootPassword\"!\n" +
	"\n" +
	"CmdStartVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"6\n" +
	"\tCmdStopVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"#\n" +
	"\fCmdRestartVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\"\n" +
	"\vCmdDeleteVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\xce\x01\n" +
	"\x0eCmdReinstallVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x19\n" +
	"\bos_image\x18\x02 \x01(\tR\aosImage\x12#\n" +
	"\rroot_password\x18\x03 \x01(\tR\frootPassword\x12\x10\n" +
	"\x03cpu\x18\x04 \x01(\x05R\x03cpu\x12\x15\n" +
	"\x06ram_mb\x18\x05 \x01(\x03R\x05ramMb\x12\x17\n" +
	"\adisk_gb\x18\x06 \x01(\x03R\x06diskGb\x12%\n" +
	"\x0ebandwidth_mbps\x18\a \x01(\x05R\rbandwidthMbps\"J\n" +
	"\x10CmdResetPassword\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\xb3\x01\n" +
	"\x11CmdSetPortForward\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12+\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x0f.agent.ProtocolR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\x05R\bhostPort\x12\x1d\n" +
	"\n" +
	"guest_port\x18\x04 \x01(\x05R\tguestPort\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"r\n" +
	"\x11CmdDelPortForward\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12+\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x0f.agent.ProtocolR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\x05R\bhostPort\")\n" +
	"\x12CmdGetPortForwards\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\x06\n" +
	"\x04Ping\"l\n" +
	"\x0eCmdConsoleOpen\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\"D\n" +
	"\x0fCmdConsoleInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"Y\n" +
	"\x10CmdConsoleResize\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"0\n" +
	"\x0fCmdConsoleClose\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\".\n" +
	"\rWGSyncRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"a\n" +
	"\x0eWGSyncResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x120\n" +
	"\bbindings\x18\x02 \x03(\v2\x14.agent.WGBindDesiredR\bbindings\"\xaf\x02\n" +
	"\rWGBindDesired\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12&\n" +
	"\x0fpeer_public_key\x18\x05 \x01(\tR\rpeerPublicKey\x12#\n" +
	"\rpreshared_key\x18\x06 \x01(\tR\fpresharedKey\x12\x1a\n" +
	"\bendpoint\x18\a \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\b \x03(\tR\n" +
	"allowedIps\x12#\n" +
	"\rkeepalive_sec\x18\t \x01(\x05R\fkeepaliveSec*\x80\x01\n" +
	"\bVMStatus\x12\x19\n" +
	"\x15VM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VM_STATUS_CREATING\x10\x01\x12\x15\n" +
	"\x11VM_STATUS_RUNNING\x10\x02\x12\x15\n" +
	"\x11VM_STATUS_STOPPED\x10\x03\x12\x13\n" +
	"\x0fVM_STATUS_ERROR\x10\x04*H\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x02*\x87\x01\n" +
	"\x10ConsoleEventType\x12\x1d\n" +
	"\x19CONSOLE_EVENT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONSOLE_EVENT_CONNECTED\x10\x01\x12\x1e\n" +
	"\x1aCONSOLE_EVENT_DISCONNECTED\x10\x02\x12\x17\n" +
	"\x13CONSOLE_EVENT_ERROR\x10\x032L\n" +
	"\fAgentGateway\x12<\n" +
	"\aConnect\x12\x14.agent.AgentEnvelope\x1a\x17.agent.PlatformEnvelope(\x010\x01B\x17Z\x15runman-v2/proto/agentb\x06proto3"

var (
	file_proto_agent_agent_proto_rawDescOnce sync.Once
	file_proto_agent_agent_proto_rawDescData []byte
)

func file_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)))
	})
	return file_proto_agent_agent_proto_rawDescData
}

var file_proto_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_agent_agent_proto_goTypes = []any{
	(VMStatus)(0),              // 0: agent.VMStatus
	(Protocol)(0),              // 1: agent.Protocol
	(ConsoleEventType)(0),      // 2: agent.ConsoleEventType
	(*AgentEnvelope)(nil),      // 3: agent.AgentEnvelope
	(*Heartbeat)(nil),          // 4: agent.Heartbeat
	(*OSImageInfo)(nil),        // 5: agent.OSImageInfo
	(*VMSummary)(nil),          // 6: agent.VMSummary
	(*CommandResult)(nil),      // 7: agent.CommandResult
	(*PortForwardList)(nil),    // 8: agent.PortForwardList
	(*PortForwardEntry)(nil),   // 9: agent.PortForwardEntry
	(*ConsoleOutput)(nil),      // 10: agent.ConsoleOutput
	(*ConsoleEvent)(nil),       // 11: agent.ConsoleEvent
	(*PlatformEnvelope)(nil),   // 12: agent.PlatformEnvelope
	(*CmdCreateVM)(nil),        // 13: agent.CmdCreateVM
	(*CmdStartVM)(nil),         // 14: agent.CmdStartVM
	(*CmdStopVM)(nil),          // 15: agent.CmdStopVM
	(*CmdRestartVM)(nil),       // 16: agent.CmdRestartVM
	(*CmdDeleteVM)(nil),        // 17: agent.CmdDeleteVM
	(*CmdReinstallVM)(nil),     // 18: agent.CmdReinstallVM
	(*CmdResetPassword)(nil),   // 19: agent.CmdResetPassword
	(*CmdSetPortForward)(nil),  // 20: agent.CmdSetPortForward
	(*CmdDelPortForward)(nil),  // 21: agent.CmdDelPortForward
	(*CmdGetPortForwards)(nil), // 22: agent.CmdGetPortForwards
	(*Ping)(nil),               // 23: agent.Ping
	(*CmdConsoleOpen)(nil),     // 24: agent.CmdConsoleOpen
	(*CmdConsoleInput)(nil),    // 25: agent.CmdConsoleInput
	(*CmdConsoleResize)(nil),   // 26: agent.CmdConsoleResize
	(*CmdConsoleClose)(nil),    // 27: agent.CmdConsoleClose
	(*WGSyncRequest)(nil),      // 28: agent.WGSyncRequest
	(*WGSyncResponse)(nil),     // 29: agent.WGSyncResponse
	(*WGBindDesired)(nil),      // 30: agent.WGBindDesired
}
var file_proto_agent_agent_proto_depIdxs = []int32{
	4,  // 0: agent.AgentEnvelope.heartbeat:type_name -> agent.Heartbeat
	7,  // 1: agent.AgentEnvelope.cmd_result:type_name -> agent.CommandResult
	8,  // 2: agent.AgentEnvelope.port_fwd_list:type_name -> agent.PortForwardList
	10, // 3: agent.AgentEnvelope.console_output:type_name -> agent.ConsoleOutput
	11, // 4: agent.AgentEnvelope.console_event:type_name -> agent.ConsoleEvent
	28, // 5: agent.AgentEnvelope.wg_sync_request:type_name -> agent.WGSyncRequest
	6,  // 6: agent.Heartbeat.vms:type_name -> agent.VMSummary
	5,  // 7: agent.Heartbeat.os_images:type_name -> agent.OSImageInfo
	0,  // 8: agent.VMSummary.status:type_name -> agent.VMStatus
	9,  // 9: agent.PortForwardList.entries:type_name -> agent.PortForwardEntry
	1,  // 10: agent.PortForwardEntry.protocol:type_name -> agent.Protocol
	2,  // 11: agent.ConsoleEvent.type:type_name -> agent.ConsoleEventType
	13, // 12: agent.PlatformEnvelope.create_vm:type_name -> agent.CmdCreateVM
	14, // 13: agent.PlatformEnvelope.start_vm:type_name -> agent.CmdStartVM
	15, // 14: agent.PlatformEnvelope.stop_vm:type_name -> agent.CmdStopVM
	16, // 15: agent.PlatformEnvelope.restart_vm:type_name -> agent.CmdRestartVM
	17, // 16: agent.PlatformEnvelope.delete_vm:type_name -> agent.CmdDeleteVM
	18, // 17: agent.PlatformEnvelope.reinstall_vm:type_name -> agent.CmdReinstallVM
	19, // 18: agent.PlatformEnvelope.reset_password:type_name -> agent.CmdResetPassword
	20, // 19: agent.PlatformEnvelope.set_port_fwd:type_name -> agent.CmdSetPortForward
	21, // 20: agent.PlatformEnvelope.del_port_fwd:type_name -> agent.CmdDelPortForward
	22, // 21: agent.PlatformEnvelope.get_port_fwds:type_name -> agent.CmdGetPortForwards
	23, // 22: agent.PlatformEnvelope.ping:type_name -> agent.Ping
	24, // 23: agent.PlatformEnvelope.console_open:type_name -> agent.CmdConsoleOpen
	25, // 24: agent.PlatformEnvelope.console_input:type_name -> agent.CmdConsoleInput
	26, // 25: agent.PlatformEnvelope.console_resize:type_name -> agent.CmdConsoleResize
	27, // 26: agent.PlatformEnvelope.console_close:type_name -> agent.CmdConsoleClose
	29, // 27: agent.PlatformEnvelope.wg_sync_response:type_name -> agent.WGSyncResponse
	1,  // 28: agent.CmdSetPortForward.protocol:type_name -> agent.Protocol
	1,  // 29: agent.CmdDelPortForward.protocol:type_name -> agent.Protocol
	30, // 30: agent.WGSyncResponse.bindings:type_name -> agent.WGBindDesired
	3,  // 31: agent.AgentGateway.Connect:input_type -> agent.AgentEnvelope
	12, // 32: agent.AgentGateway.Connect:output_type -> agent.PlatformEnvelope
	32, // [32:33] is the sub-list for method output_type
	31, // [31:32] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_proto_agent_agent_proto_init() }
func file_proto_agent_agent_proto_init() {
	if File_proto_agent_agent_proto != nil {
		return
	}
	file_proto_agent_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentEnvelope_Heartbeat)(nil),
		(*AgentEnvelope_CmdResult)(nil),
		(*AgentEnvelope_PortFwdList)(nil),
		(*AgentEnvelope_ConsoleOutput)(nil),
		(*AgentEnvelope_ConsoleEvent)(nil),
		(*AgentEnvelope_WgSyncRequest)(nil),
	}
	file_proto_agent_agent_proto_msgTypes[9].OneofWrappers = []any{
		(*PlatformEnvelope_CreateVm)(nil),
		(*PlatformEnvelope_StartVm)(nil),
		(*PlatformEnvelope_StopVm)(nil),
		(*PlatformEnvelope_RestartVm)(nil),
		(*PlatformEnvelope_DeleteVm)(nil),
		(*PlatformEnvelope_ReinstallVm)(nil),
		(*PlatformEnvelope_ResetPassword)(nil),
		(*PlatformEnvelope_SetPortFwd)(nil),
		(*PlatformEnvelope_DelPortFwd)(nil),
		(*PlatformEnvelope_GetPortFwds)(nil),
		(*PlatformEnvelope_Ping)(nil),
		(*PlatformEnvelope_ConsoleOpen)(nil),
		(*PlatformEnvelope_ConsoleInput)(nil),
		(*PlatformEnvelope_ConsoleResize)(nil),
		(*PlatformEnvelope_ConsoleClose)(nil),
		(*PlatformEnvelope_WgSyncResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_agent_proto = out.File
	file_proto_agent_agent_proto_goTypes = nil
	file_proto_agent_agent_proto_depIdxs = nil
}
