// =============================================================================
// Narwhal Cloud Agent Gateway Protocol  —  v1.0
//
// 概述 / Overview:
//   本协议定义了 Narwhal Cloud 平台与 Agent 节点之间的双向流式 gRPC 通信。
//   Agent 运行于宿主机（VPS 物理节点），负责管理其上所有 VM 的完整生命周期。
//
//   This file defines the bidirectional streaming gRPC protocol between the
//   Narwhal Cloud platform and agent nodes. Each agent manages VMs on a single host.
//
// 连接流程 / Connection Flow:
//   1. Agent 拨号平台 gRPC 端点（支持 TLS）。
//      Agent dials the platform gRPC endpoint (TLS recommended).
//   2. Agent 在 gRPC metadata 中携带身份令牌：
//      Agent sets metadata:  authorization = "Bearer <agent_token>"
//   3. Agent 调用 AgentGateway.Connect() 建立持久双向流。
//      Agent calls AgentGateway.Connect() to open a persistent stream.
//   4. Agent 每 30 秒发送一次 Heartbeat；平台按需下发命令。
//      Agent sends Heartbeat every 30 s; platform sends commands on demand.
//   5. 断线后 Agent 须以指数退避策略重连。
//      On disconnect, agent reconnects with exponential backoff.
//
// 命令确认 / Command Acknowledgement:
//   平台每条下行命令都携带全局唯一的 command_id。
//   Agent 执行完毕（或失败）后，必须通过 CommandResult 回报结果。
//
//   Every platform command carries a unique command_id.
//   Agent MUST respond with CommandResult (success or failure) for every command.
//
// 代码生成 / Code Generation:
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          proto/agent/agent.proto
// =============================================================================

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0
// source: proto/agent/agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_Connect_FullMethodName = "/agent.AgentGateway/Connect"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentGateway — Agent 与 Narwhal Cloud 平台之间的双向流式通信服务。
// 由 Agent 主动建立连接；平台侧作为 gRPC 服务端。
type AgentGatewayClient interface {
	// Connect 建立一条持久的双向流：
	//   - 上行 (AgentEnvelope)：心跳、命令结果、控制台输出
	//   - 下行 (PlatformEnvelope)：VM 操作命令、控制台控制帧
	//
	// The stream is long-lived. Agent should reconnect with exponential backoff on any error.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEnvelope, PlatformEnvelope], error)
}

type agentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentGatewayClient{cc}
}

func (c *agentGatewayClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentEnvelope, PlatformEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentEnvelope, PlatformEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ConnectClient = grpc.BidiStreamingClient[AgentEnvelope, PlatformEnvelope]

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
//
// AgentGateway — Agent 与 Narwhal Cloud 平台之间的双向流式通信服务。
// 由 Agent 主动建立连接；平台侧作为 gRPC 服务端。
type AgentGatewayServer interface {
	// Connect 建立一条持久的双向流：
	//   - 上行 (AgentEnvelope)：心跳、命令结果、控制台输出
	//   - 下行 (PlatformEnvelope)：VM 操作命令、控制台控制帧
	//
	// The stream is long-lived. Agent should reconnect with exponential backoff on any error.
	Connect(grpc.BidiStreamingServer[AgentEnvelope, PlatformEnvelope]) error
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) Connect(grpc.BidiStreamingServer[AgentEnvelope, PlatformEnvelope]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).Connect(&grpc.GenericServerStream[AgentEnvelope, PlatformEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_ConnectServer = grpc.BidiStreamingServer[AgentEnvelope, PlatformEnvelope]

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentGateway_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/agent.proto",
}
