import { ApiRequestError, apiRequest, type AdminPrincipal, type AuthData, type ItemList } from "@vps-billing/api-types";
import { type Locale, type MessageKey, useI18n } from "@vps-billing/i18n";
import { Alert, AppShell, Button, Card, EmptyState, ErrorState, Skeleton, StatusBadge } from "@vps-billing/ui";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { type FormEvent, useEffect, useState } from "react";

type T = (key: MessageKey) => string;
type Item = Record<string, unknown>;
type Page = "dashboard"|"users"|"products"|"orders"|"payments"|"ledger"|"subscriptions"|"instances"|"nodes"|"providers"|"operations"|"tickets"|"audit"|"admins"|"roles"|"settings";
type DashboardData = {metrics:Item;critical_alerts:Item[];failed_operations:Item[];provider_health:Item[];node_health:Item[];capacity_warnings:Item[]};

const pages: {key:Page;permission:string}[] = [
  {key:"dashboard",permission:"health.read"},{key:"users",permission:"users.read"},{key:"products",permission:"products.read"},
  {key:"orders",permission:"orders.read"},{key:"payments",permission:"payments.read"},{key:"ledger",permission:"ledger.read"},
  {key:"subscriptions",permission:"subscriptions.read"},{key:"instances",permission:"instances.read"},{key:"nodes",permission:"nodes.read"},
  {key:"providers",permission:"providers.read"},{key:"operations",permission:"operations.read"},{key:"tickets",permission:"tickets.read"},
  {key:"audit",permission:"audit.read"},{key:"admins",permission:"admins.read"},{key:"roles",permission:"roles.read"},{key:"settings",permission:"settings.read"},
];
const columns: Partial<Record<Page,string[]>> = {
  users:["email","status","locale","created_at"],products:["slug","status","name_i18n","created_at"],orders:["order_no","user_email","status","total_minor","currency","created_at"],
  payments:["payment_no","order_no","user_email","status","amount_minor","currency","gateway","created_at"],ledger:["type","reference_type","description","created_at"],
  subscriptions:["user_email","plan_slug","status","billing_cycle","current_period_end"],instances:["name","user_email","observed_state","desired_state","node_name","provider_name"],
  nodes:["name","region","status","provider_name","available_memory_mb","last_seen_at"],providers:["name","provider_type","status","version","last_health_check_at"],
  operations:["type","resource_type","status","phase","progress","error_code","created_at"],tickets:["ticket_no","user_email","subject","status","priority","message_count","updated_at"],
  audit:["action","resource_type","actor_email","request_id","created_at"],admins:["email","display_name","status","two_factor_enabled","roles"],roles:["key","permissions"],settings:["key","value","is_secret","updated_at"],
};

export function App(){
  const {locale,setLocale,t}=useI18n(),client=useQueryClient();
  const auth=useQuery({queryKey:["admin-auth"],queryFn:()=>apiRequest<AuthData<AdminPrincipal>>("/api/v1/admin/auth/me"),retry:false});
  const [page,setPage]=useHashPage();
  useEffect(()=>{document.documentElement.lang=locale;document.title=t("admin.appName")},[locale,t]);
  if(auth.isPending)return <Shell locale={locale} setLocale={setLocale} t={t}><Skeleton label={t("common.loading")}/></Shell>;
  if(auth.isError&&(!(auth.error instanceof ApiRequestError)||auth.error.status!==401))return <Shell locale={locale} setLocale={setLocale} t={t}><ErrorState title={errorText(auth.error,t)} retry={()=>void auth.refetch()} retryLabel={t("common.retry")}/></Shell>;
  if(!auth.data)return <Login locale={locale} setLocale={setLocale} t={t} success={(data)=>client.setQueryData(["admin-auth"],data)}/>;
  const allowed=pages.filter((item)=>auth.data.principal.permissions.includes(item.permission));
  const selected=allowed.some((item)=>item.key===page)?page:allowed[0]?.key;
  return <Shell locale={locale} setLocale={setLocale} t={t} actions={<Logout csrf={auth.data.csrf_token} t={t}/>}><div className="admin-layout"><nav className="admin-nav" aria-label={t("admin.appName")}>{allowed.map((item)=><button key={item.key} data-active={selected===item.key} onClick={()=>setPage(item.key)}>{t(`admin.nav.${item.key}` as MessageKey)}</button>)}</nav><main className="admin-content">{selected?<PageView page={selected} principal={auth.data.principal} csrf={auth.data.csrf_token} locale={locale} t={t}/>:<ErrorState title={t("errors.permissionDenied")}/>}</main></div></Shell>;
}

function Login({locale,setLocale,t,success}:{locale:Locale;setLocale:(v:Locale)=>void;t:T;success:(v:AuthData<AdminPrincipal>)=>void}){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[code,setCode]=useState("");const mutation=useMutation({mutationFn:()=>apiRequest<AuthData<AdminPrincipal>>("/api/v1/admin/auth/login",{method:"POST",body:JSON.stringify({email,password,totp_code:code})}),onSuccess:success});const submit=(e:FormEvent)=>{e.preventDefault();mutation.mutate()};return <Shell locale={locale} setLocale={setLocale} t={t}><div className="auth-card"><Card><h1>{t("auth.adminTitle")}</h1><form className="auth-form" onSubmit={submit}><label className="form-field">{t("auth.email")}<input className="form-input" type="email" autoComplete="username" required value={email} onChange={(e)=>setEmail(e.target.value)}/></label><label className="form-field">{t("auth.password")}<input className="form-input" type="password" autoComplete="current-password" required value={password} onChange={(e)=>setPassword(e.target.value)}/></label><label className="form-field">{t("auth.totp")}<input className="form-input" inputMode="numeric" pattern="[0-9]{6}" value={code} onChange={(e)=>setCode(e.target.value)}/></label>{mutation.isError&&<Alert tone="danger">{errorText(mutation.error,t)}</Alert>}<Button disabled={mutation.isPending}>{t(mutation.isPending?"auth.pending":"auth.login")}</Button></form></Card></div></Shell>}

function PageView({page,principal,csrf,locale,t}:{page:Page;principal:AdminPrincipal;csrf:string;locale:Locale;t:T}){if(page==="dashboard")return <Dashboard locale={locale} t={t}/>;return <ResourcePage page={page} principal={principal} csrf={csrf} locale={locale} t={t}/>}
function Dashboard({locale,t}:{locale:Locale;t:T}){const query=useQuery({queryKey:["admin","dashboard"],queryFn:()=>apiRequest<DashboardData>("/api/v1/admin/dashboard"),refetchInterval:30000});if(query.isPending)return <Skeleton label={t("common.loading")}/>;if(query.isError)return <ErrorState title={errorText(query.error,t)} retry={()=>void query.refetch()} retryLabel={t("common.retry")}/>;const d=query.data;return <section><h1 className="page-title">{t("admin.nav.dashboard")}</h1><h2>{t("admin.criticalAlerts")}</h2>{d.critical_alerts.length?<DenseTable items={d.critical_alerts} fields={["kind","status","error_code","created_at"]} locale={locale} t={t}/>:<Alert tone="success">{t("admin.noCriticalAlerts")}</Alert>}<div className="metric-grid admin-metrics">{Object.entries(d.metrics).map(([key,value])=><div className="metric" key={key}><span>{t(`admin.metric.${key}` as MessageKey)}</span><strong>{String(value)}</strong></div>)}</div><DashboardPanel title={t("admin.failedOperations")} items={d.failed_operations} fields={["type","status","phase","error_code"]} locale={locale} t={t}/><DashboardPanel title={t("admin.providerHealth")} items={d.provider_health} fields={["name","provider_type","status","last_health_check_at"]} locale={locale} t={t}/><DashboardPanel title={t("admin.nodeHealth")} items={d.node_health} fields={["name","region","status","last_seen_at"]} locale={locale} t={t}/><DashboardPanel title={t("admin.capacityWarnings")} items={d.capacity_warnings} fields={["name","cpu_percent","memory_percent","disk_percent"]} locale={locale} t={t}/></section>}
function DashboardPanel({title,items,fields,locale,t}:{title:string;items:Item[];fields:string[];locale:Locale;t:T}){return <section className="admin-section"><h2>{title}</h2>{items.length?<DenseTable items={items} fields={fields} locale={locale} t={t}/>:<EmptyState title={t("common.empty")}/>}</section>}

function ResourcePage({page,principal,csrf,locale,t}:{page:Page;principal:AdminPrincipal;csrf:string;locale:Locale;t:T}){const query=useQuery({queryKey:["admin",page],queryFn:()=>apiRequest<ItemList<Item>>(`/api/v1/admin/${page}`)});const[selected,setSelected]=useState<Item|null>(null);if(query.isPending)return <Skeleton label={t("common.loading")}/>;if(query.isError){if(query.error instanceof ApiRequestError&&query.error.status===403)return <ErrorState title={t("errors.permissionDenied")}/>;return <ErrorState title={errorText(query.error,t)} retry={()=>void query.refetch()} retryLabel={t("common.retry")}/>};const actionable=["instances","operations","tickets","users","admins"].includes(page);return <section><div className="card-heading"><h1 className="page-title">{t(`admin.nav.${page}` as MessageKey)}</h1><ActionForm page={page} principal={principal} csrf={csrf} t={t}/></div>{query.data.items.length?<DenseTable items={query.data.items} fields={columns[page]??[]} locale={locale} t={t} select={actionable?setSelected:undefined}/>:<EmptyState title={t("common.empty")}/>} {selected&&<Detail page={page} item={selected} principal={principal} csrf={csrf} locale={locale} t={t} close={()=>setSelected(null)}/>}</section>}

function DenseTable({items,fields,locale,t,select}:{items:Item[];fields:string[];locale:Locale;t:T;select?:(i:Item)=>void}){return <div className="table-wrap"><table><thead><tr>{fields.map((field)=><th key={field}>{t(`admin.field.${field}` as MessageKey)}</th>)}{select&&<th>{t("common.actions")}</th>}</tr></thead><tbody>{items.map((item,index)=><tr key={String(item.id??index)}>{fields.map((field)=><td key={field}>{renderValue(field,item[field],locale,t)}</td>)}{select&&<td><button className="link-button" onClick={()=>select(item)}>{t("common.view")}</button></td>}</tr>)}</tbody></table></div>}
function renderValue(field:string,value:unknown,locale:Locale,t:T){if(value===null||value===undefined||value==="")return "—";if(field.includes("status")||field==="observed_state"||field==="desired_state")return <StatusBadge status={String(value)} label={statusText(String(value),t)}/>;if(field.endsWith("_at")){const date=new Date(String(value));return Number.isNaN(date.valueOf())?String(value):date.toLocaleString(locale)};if(field.endsWith("_minor"))return new Intl.NumberFormat(locale).format(Number(value));if(typeof value==="object")return Array.isArray(value)?value.join(", "):JSON.stringify(value);if(typeof value==="boolean")return t(value?"common.yes":"common.no");return String(value)}

function Detail({page,item,principal,csrf,locale,t,close}:{page:Page;item:Item;principal:AdminPrincipal;csrf:string;locale:Locale;t:T;close:()=>void}){const id=String(item.id),hasDetail=page==="instances"||page==="operations",query=useQuery({queryKey:["admin",page,id],queryFn:()=>apiRequest<Item>(`/api/v1/admin/${page}/${id}`),enabled:hasDetail});let content;if(page==="tickets")content=<TicketActions item={item} principal={principal} csrf={csrf} t={t}/>;else if(page==="users")content=<UserActions item={item} principal={principal} csrf={csrf} t={t}/>;else if(page==="admins")content=<AdminRoleActions item={item} principal={principal} csrf={csrf} t={t}/>;else content=query.isPending?<Skeleton label={t("common.loading")}/>:query.isError?<ErrorState title={errorText(query.error,t)}/>:<pre className="diagnostic">{JSON.stringify(query.data,null,2)}</pre>;return <div className="dialog-backdrop"><section className="dialog admin-detail" role="dialog" aria-modal="true"><div className="card-heading"><h2>{t("admin.detail")}</h2><button className="button button--secondary" onClick={close}>{t("common.close")}</button></div>{content}<small>{new Date().toLocaleString(locale)}</small></section></div>}

function UserActions({item,principal,csrf,t}:{item:Item;principal:AdminPrincipal;csrf:string;t:T}){const client=useQueryClient(),[status,setStatus]=useState(String(item.status)),mutation=useMutation({mutationFn:()=>apiRequest<Item>(`/api/v1/admin/users/${item.id}/status`,{method:"PATCH",headers:{"X-CSRF-Token":csrf},body:JSON.stringify({status})}),onSuccess:()=>void client.invalidateQueries({queryKey:["admin","users"]})});if(!principal.permissions.includes("users.suspend"))return <ErrorState title={t("errors.permissionDenied")}/>;return <div className="auth-form"><label className="form-field">{t("admin.field.status")}<select className="form-input" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="active">{statusText("active",t)}</option><option value="suspended">{statusText("suspended",t)}</option></select></label>{mutation.isError&&<Alert tone="danger">{errorText(mutation.error,t)}</Alert>}<Button onClick={()=>mutation.mutate()}>{t("admin.updateUser")}</Button></div>}
function AdminRoleActions({item,principal,csrf,t}:{item:Item;principal:AdminPrincipal;csrf:string;t:T}){const choices=["super_admin","operations","finance","support","read_only"],client=useQueryClient(),[roles,setRoles]=useState<string[]>(Array.isArray(item.roles)?item.roles.map(String):[]),mutation=useMutation({mutationFn:()=>apiRequest<Item>(`/api/v1/admin/admins/${item.id}/roles`,{method:"PUT",headers:{"X-CSRF-Token":csrf},body:JSON.stringify({roles})}),onSuccess:()=>void client.invalidateQueries({queryKey:["admin","admins"]})});if(!principal.permissions.includes("admins.manage"))return <ErrorState title={t("errors.permissionDenied")}/>;return <div className="auth-form"><fieldset><legend>{t("admin.field.roles")}</legend>{choices.map((role)=><label className="check-line" key={role}><input type="checkbox" checked={roles.includes(role)} onChange={(e)=>setRoles(e.target.checked?[...roles,role]:roles.filter((v)=>v!==role))}/> {t(`roles.${role}` as MessageKey)}</label>)}</fieldset>{mutation.isError&&<Alert tone="danger">{errorText(mutation.error,t)}</Alert>}<Button onClick={()=>mutation.mutate()} disabled={!roles.length}>{t("admin.updateRoles")}</Button></div>}

function TicketActions({item,principal,csrf,t}:{item:Item;principal:AdminPrincipal;csrf:string;t:T}){const client=useQueryClient(),[message,setMessage]=useState(""),[status,setStatus]=useState(String(item.status));const reply=useMutation({mutationFn:()=>apiRequest<Item>(`/api/v1/admin/tickets/${item.id}/messages`,{method:"POST",headers:{"X-CSRF-Token":csrf},body:JSON.stringify({message})}),onSuccess:()=>{setMessage("");void client.invalidateQueries({queryKey:["admin","tickets"]})}});const update=useMutation({mutationFn:()=>apiRequest<Item>(`/api/v1/admin/tickets/${item.id}/status`,{method:"PATCH",headers:{"X-CSRF-Token":csrf},body:JSON.stringify({status})}),onSuccess:()=>void client.invalidateQueries({queryKey:["admin","tickets"]})});return <div className="auth-form">{principal.permissions.includes("tickets.reply")&&<><label className="form-field">{t("admin.reply")}<textarea className="form-input textarea" value={message} onChange={(e)=>setMessage(e.target.value)}/></label><Button onClick={()=>reply.mutate()} disabled={!message||reply.isPending}>{t("admin.sendReply")}</Button></>}{principal.permissions.includes("tickets.manage")&&<><label className="form-field">{t("admin.field.status")}<select className="form-input" value={status} onChange={(e)=>setStatus(e.target.value)}>{["open","waiting_user","waiting_support","resolved","closed"].map((v)=><option value={v} key={v}>{statusText(v,t)}</option>)}</select></label><Button onClick={()=>update.mutate()}>{t("common.save")}</Button></>}{(reply.isError||update.isError)&&<Alert tone="danger">{errorText(reply.error??update.error,t)}</Alert>}</div>}

function ActionForm({page,principal,csrf,t}:{page:Page;principal:AdminPrincipal;csrf:string;t:T}){if(page==="ledger"&&principal.permissions.includes("ledger.adjust"))return <WalletAdjustment csrf={csrf} t={t}/>;if(page==="settings"&&principal.permissions.includes("settings.manage"))return <SettingForm csrf={csrf} t={t}/>;return null}
function WalletAdjustment({csrf,t}:{csrf:string;t:T}){const client=useQueryClient(),[open,setOpen]=useState(false),[userID,setUserID]=useState(""),[currency,setCurrency]=useState("USD"),[amount,setAmount]=useState(""),[description,setDescription]=useState("");const mutation=useMutation({mutationFn:()=>apiRequest<Item>("/api/v1/admin/ledger/adjustments",{method:"POST",headers:{"X-CSRF-Token":csrf},body:JSON.stringify({user_id:userID,currency,amount_minor:Number(amount),description})}),onSuccess:()=>void client.invalidateQueries({queryKey:["admin","ledger"]})});return <><Button onClick={()=>setOpen(true)}>{t("admin.adjustWallet")}</Button>{open&&<div className="dialog-backdrop"><form className="dialog auth-form" onSubmit={(e)=>{e.preventDefault();mutation.mutate()}}><h2>{t("admin.adjustWallet")}</h2><Field label={t("admin.field.user_id")} value={userID} set={setUserID}/><Field label={t("admin.field.currency")} value={currency} set={setCurrency}/><Field label={t("admin.field.amount_minor")} value={amount} set={setAmount} type="number"/><Field label={t("admin.field.description")} value={description} set={setDescription}/>{mutation.isError&&<Alert tone="danger">{errorText(mutation.error,t)}</Alert>}<div className="button-row"><Button>{t("common.save")}</Button><button type="button" className="button button--secondary" onClick={()=>setOpen(false)}>{t("common.cancel")}</button></div></form></div>}</>}
function SettingForm({csrf,t}:{csrf:string;t:T}){const client=useQueryClient(),[open,setOpen]=useState(false),[key,setKey]=useState(""),[value,setValue]=useState(""),[secret,setSecret]=useState(false);const mutation=useMutation({mutationFn:()=>apiRequest<Item>(`/api/v1/admin/settings/${encodeURIComponent(key)}`,{method:"PUT",headers:{"X-CSRF-Token":csrf},body:JSON.stringify({value,is_secret:secret})}),onSuccess:()=>void client.invalidateQueries({queryKey:["admin","settings"]})});return <><Button onClick={()=>setOpen(true)}>{t("admin.updateSetting")}</Button>{open&&<div className="dialog-backdrop"><form className="dialog auth-form" onSubmit={(e)=>{e.preventDefault();mutation.mutate()}}><h2>{t("admin.updateSetting")}</h2><Field label={t("admin.field.key")} value={key} set={setKey}/><Field label={t("admin.field.value")} value={value} set={setValue}/><label><input type="checkbox" checked={secret} onChange={(e)=>setSecret(e.target.checked)}/> {t("admin.field.is_secret")}</label>{mutation.isError&&<Alert tone="danger">{errorText(mutation.error,t)}</Alert>}<div className="button-row"><Button>{t("common.save")}</Button><button type="button" className="button button--secondary" onClick={()=>setOpen(false)}>{t("common.cancel")}</button></div></form></div>}</>}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="form-field">{label}<input className="form-input" type={type} required value={value} onChange={(e)=>set(e.target.value)}/></label>}

function Shell({locale,setLocale,t,actions,children}:{locale:Locale;setLocale:(v:Locale)=>void;t:T;actions?:React.ReactNode;children:React.ReactNode}){return <AppShell title={t("admin.appName")} actions={<><label><span className="sr-only">{t("common.language")}</span><select className="locale-select" value={locale} onChange={(e)=>setLocale(e.target.value as Locale)}><option value="zh-CN">{t("common.locale.zh-CN")}</option><option value="en-US">{t("common.locale.en-US")}</option></select></label>{actions}</>}>{children}</AppShell>}
function Logout({csrf,t}:{csrf:string;t:T}){const client=useQueryClient(),mutation=useMutation({mutationFn:()=>apiRequest<{logged_out:boolean}>("/api/v1/admin/auth/logout",{method:"POST",headers:{"X-CSRF-Token":csrf}}),onSuccess:()=>client.setQueryData(["admin-auth"],undefined)});return <button type="button" className="button button--secondary" onClick={()=>mutation.mutate()} disabled={mutation.isPending}>{t("auth.logout")}</button>}
function useHashPage():[Page,(v:Page)=>void]{const read=()=>{const value=window.location.hash.slice(1) as Page;return pages.some((p)=>p.key===value)?value:"dashboard"};const[page,setState]=useState<Page>(read);useEffect(()=>{const listener=()=>setState(read());window.addEventListener("hashchange",listener);return()=>window.removeEventListener("hashchange",listener)},[]);return[page,(value)=>{window.location.hash=value;setState(value)}]}
function errorText(error:unknown,t:T){return error instanceof ApiRequestError?t(error.messageKey as MessageKey):t("errors.internal")}
function statusText(status:string,t:T){const key=`status.${status}` as MessageKey;return t(key)===key?status:t(key)}
