// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxEvents = `-- name: ClaimOutboxEvents :many
SELECT id, event_type, aggregate_type, aggregate_id, payload, status, attempts, next_attempt_at, created_at, published_at FROM outbox_events
WHERE status = 'pending' AND next_attempt_at <= now()
ORDER BY created_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

func (q *Queries) ClaimOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, claimOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countLedgerTransactionsByReference = `-- name: CountLedgerTransactionsByReference :one
SELECT count(*) FROM ledger_transactions WHERE type = $1 AND reference_type = $2 AND reference_id = $3
`

type CountLedgerTransactionsByReferenceParams struct {
	Type          string      `json:"type"`
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   *uuid.UUID  `json:"reference_id"`
}

func (q *Queries) CountLedgerTransactionsByReference(ctx context.Context, arg CountLedgerTransactionsByReferenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLedgerTransactionsByReference, arg.Type, arg.ReferenceType, arg.ReferenceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (id, invoice_no, user_id, order_id, status, amount_minor, currency, due_at)
VALUES ($1, $2, $3, $4, 'open', $5, $6, $7)
RETURNING id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	ID          uuid.UUID          `json:"id"`
	InvoiceNo   string             `json:"invoice_no"`
	UserID      uuid.UUID          `json:"user_id"`
	OrderID     *uuid.UUID         `json:"order_id"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	DueAt       pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ID,
		arg.InvoiceNo,
		arg.UserID,
		arg.OrderID,
		arg.AmountMinor,
		arg.Currency,
		arg.DueAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.UserID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :exec
INSERT INTO invoice_items (id, invoice_id, description_i18n, quantity, unit_amount_minor, total_minor)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateInvoiceItemParams struct {
	ID              uuid.UUID `json:"id"`
	InvoiceID       uuid.UUID `json:"invoice_id"`
	DescriptionI18n []byte    `json:"description_i18n"`
	Quantity        int32     `json:"quantity"`
	UnitAmountMinor int64     `json:"unit_amount_minor"`
	TotalMinor      int64     `json:"total_minor"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) error {
	_, err := q.db.Exec(ctx, createInvoiceItem,
		arg.ID,
		arg.InvoiceID,
		arg.DescriptionI18n,
		arg.Quantity,
		arg.UnitAmountMinor,
		arg.TotalMinor,
	)
	return err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :exec
INSERT INTO ledger_entries (id, transaction_id, account_type, account_id, direction, amount_minor, currency)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateLedgerEntryParams struct {
	ID            uuid.UUID `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountType   string    `json:"account_type"`
	AccountID     uuid.UUID `json:"account_id"`
	Direction     string    `json:"direction"`
	AmountMinor   int64     `json:"amount_minor"`
	Currency      string    `json:"currency"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, createLedgerEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountType,
		arg.AccountID,
		arg.Direction,
		arg.AmountMinor,
		arg.Currency,
	)
	return err
}

const createLedgerTransaction = `-- name: CreateLedgerTransaction :exec
INSERT INTO ledger_transactions (id, type, reference_type, reference_id, description)
VALUES ($1, $2, $3, $4, $5)
`

type CreateLedgerTransactionParams struct {
	ID            uuid.UUID   `json:"id"`
	Type          string      `json:"type"`
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   *uuid.UUID  `json:"reference_id"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) error {
	_, err := q.db.Exec(ctx, createLedgerTransaction,
		arg.ID,
		arg.Type,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Description,
	)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, idempotency_key)
VALUES ($1, $2, $3, 'pending', $4, 0, $4, $5, $6)
RETURNING id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, paid_at, created_at, updated_at, idempotency_key
`

type CreateOrderParams struct {
	ID             uuid.UUID   `json:"id"`
	OrderNo        string      `json:"order_no"`
	UserID         uuid.UUID   `json:"user_id"`
	SubtotalMinor  int64       `json:"subtotal_minor"`
	Currency       string      `json:"currency"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.OrderNo,
		arg.UserID,
		arg.SubtotalMinor,
		arg.Currency,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (id, order_id, product_id, plan_id, quantity, unit_price_minor, total_minor, product_snapshot, plan_snapshot)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOrderItemParams struct {
	ID              uuid.UUID `json:"id"`
	OrderID         uuid.UUID `json:"order_id"`
	ProductID       uuid.UUID `json:"product_id"`
	PlanID          uuid.UUID `json:"plan_id"`
	Quantity        int32     `json:"quantity"`
	UnitPriceMinor  int64     `json:"unit_price_minor"`
	TotalMinor      int64     `json:"total_minor"`
	ProductSnapshot []byte    `json:"product_snapshot"`
	PlanSnapshot    []byte    `json:"plan_snapshot"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.PlanID,
		arg.Quantity,
		arg.UnitPriceMinor,
		arg.TotalMinor,
		arg.ProductSnapshot,
		arg.PlanSnapshot,
	)
	return err
}

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO outbox_events (id, event_type, aggregate_type, aggregate_id, payload)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOutboxEventParams struct {
	ID            uuid.UUID `json:"id"`
	EventType     string    `json:"event_type"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   uuid.UUID `json:"aggregate_id"`
	Payload       []byte    `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
	)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (id, payment_no, order_id, gateway, status, amount_minor, currency, idempotency_key)
VALUES ($1, $2, $3, $4, 'pending', $5, $6, $7)
RETURNING id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	ID             uuid.UUID `json:"id"`
	PaymentNo      string    `json:"payment_no"`
	OrderID        uuid.UUID `json:"order_id"`
	Gateway        string    `json:"gateway"`
	AmountMinor    int64     `json:"amount_minor"`
	Currency       string    `json:"currency"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.PaymentNo,
		arg.OrderID,
		arg.Gateway,
		arg.AmountMinor,
		arg.Currency,
		arg.IdempotencyKey,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureWallet = `-- name: EnsureWallet :one
INSERT INTO wallets (id, user_id, currency) VALUES ($1, $2, $3)
ON CONFLICT (user_id, currency) DO UPDATE SET currency = EXCLUDED.currency
RETURNING id, user_id, currency, available_balance_minor, created_at, updated_at
`

type EnsureWalletParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Currency string    `json:"currency"`
}

func (q *Queries) EnsureWallet(ctx context.Context, arg EnsureWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, ensureWallet, arg.ID, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByUserIdempotency = `-- name: GetOrderByUserIdempotency :one
SELECT id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, paid_at, created_at, updated_at, idempotency_key FROM orders WHERE user_id = $1 AND idempotency_key = $2
`

type GetOrderByUserIdempotencyParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetOrderByUserIdempotency(ctx context.Context, arg GetOrderByUserIdempotencyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByUserIdempotency, arg.UserID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getPaymentByOrder = `-- name: GetPaymentByOrder :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments WHERE order_id = $1 ORDER BY created_at LIMIT 1
`

func (q *Queries) GetPaymentByOrder(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrder, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanForOrder = `-- name: GetPlanForOrder :one
SELECT plans.id, plans.product_id, plans.node_group_id, plans.slug, plans.name_i18n, plans.status, plans.cpu_cores, plans.memory_mb, plans.disk_gb, plans.traffic_gb, plans.bandwidth_mbps, plans.ipv4_count, plans.ipv6_count, plans.nat_port_count, plans.virtualization, plans.billing_cycle, plans.price_minor, plans.currency, plans.stock_mode, plans.created_at, plans.updated_at, products.slug AS product_slug, products.name_i18n AS product_name_i18n,
       products.description_i18n AS product_description_i18n, products.status AS product_status
FROM plans JOIN products ON products.id = plans.product_id
WHERE plans.id = $1 AND plans.status = 'active' AND products.status = 'active'
`

type GetPlanForOrderRow struct {
	ID                     uuid.UUID          `json:"id"`
	ProductID              uuid.UUID          `json:"product_id"`
	NodeGroupID            *uuid.UUID         `json:"node_group_id"`
	Slug                   string             `json:"slug"`
	NameI18n               []byte             `json:"name_i18n"`
	Status                 string             `json:"status"`
	CpuCores               pgtype.Numeric     `json:"cpu_cores"`
	MemoryMb               int32              `json:"memory_mb"`
	DiskGb                 int32              `json:"disk_gb"`
	TrafficGb              pgtype.Int8        `json:"traffic_gb"`
	BandwidthMbps          pgtype.Int4        `json:"bandwidth_mbps"`
	Ipv4Count              int32              `json:"ipv4_count"`
	Ipv6Count              int32              `json:"ipv6_count"`
	NatPortCount           int32              `json:"nat_port_count"`
	Virtualization         string             `json:"virtualization"`
	BillingCycle           string             `json:"billing_cycle"`
	PriceMinor             int64              `json:"price_minor"`
	Currency               string             `json:"currency"`
	StockMode              string             `json:"stock_mode"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	ProductSlug            string             `json:"product_slug"`
	ProductNameI18n        []byte             `json:"product_name_i18n"`
	ProductDescriptionI18n []byte             `json:"product_description_i18n"`
	ProductStatus          string             `json:"product_status"`
}

func (q *Queries) GetPlanForOrder(ctx context.Context, id uuid.UUID) (GetPlanForOrderRow, error) {
	row := q.db.QueryRow(ctx, getPlanForOrder, id)
	var i GetPlanForOrderRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.NodeGroupID,
		&i.Slug,
		&i.NameI18n,
		&i.Status,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficGb,
		&i.BandwidthMbps,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Virtualization,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StockMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductSlug,
		&i.ProductNameI18n,
		&i.ProductDescriptionI18n,
		&i.ProductStatus,
	)
	return i, err
}

const getWalletByUserCurrency = `-- name: GetWalletByUserCurrency :one
SELECT id, user_id, currency, available_balance_minor, created_at, updated_at FROM wallets WHERE user_id = $1 AND currency = $2
`

type GetWalletByUserCurrencyParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Currency string    `json:"currency"`
}

func (q *Queries) GetWalletByUserCurrency(ctx context.Context, arg GetWalletByUserCurrencyParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByUserCurrency, arg.UserID, arg.Currency)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookReceipt = `-- name: GetWebhookReceipt :one
SELECT id, gateway, external_event_id, payload, received_at, processed_at FROM payment_webhook_receipts WHERE gateway = $1 AND external_event_id = $2
`

type GetWebhookReceiptParams struct {
	Gateway         string `json:"gateway"`
	ExternalEventID string `json:"external_event_id"`
}

func (q *Queries) GetWebhookReceipt(ctx context.Context, arg GetWebhookReceiptParams) (PaymentWebhookReceipt, error) {
	row := q.db.QueryRow(ctx, getWebhookReceipt, arg.Gateway, arg.ExternalEventID)
	var i PaymentWebhookReceipt
	err := row.Scan(
		&i.ID,
		&i.Gateway,
		&i.ExternalEventID,
		&i.Payload,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const insertWebhookReceipt = `-- name: InsertWebhookReceipt :one
INSERT INTO payment_webhook_receipts (id, gateway, external_event_id, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (gateway, external_event_id) DO NOTHING
RETURNING id
`

type InsertWebhookReceiptParams struct {
	ID              uuid.UUID `json:"id"`
	Gateway         string    `json:"gateway"`
	ExternalEventID string    `json:"external_event_id"`
	Payload         []byte    `json:"payload"`
}

func (q *Queries) InsertWebhookReceipt(ctx context.Context, arg InsertWebhookReceiptParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertWebhookReceipt,
		arg.ID,
		arg.Gateway,
		arg.ExternalEventID,
		arg.Payload,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listActiveProductsAndPlans = `-- name: ListActiveProductsAndPlans :many
SELECT products.id AS product_id, products.slug AS product_slug, products.name_i18n AS product_name_i18n,
       products.description_i18n, plans.id AS plan_id, plans.slug AS plan_slug, plans.name_i18n AS plan_name_i18n,
       plans.cpu_cores, plans.memory_mb, plans.disk_gb, plans.traffic_gb, plans.bandwidth_mbps,
       plans.ipv4_count, plans.ipv6_count, plans.nat_port_count, plans.virtualization, plans.billing_cycle,
       plans.price_minor, plans.currency, plans.stock_mode
FROM products JOIN plans ON plans.product_id = products.id
WHERE products.status = 'active' AND plans.status = 'active'
ORDER BY products.sort_order, products.slug, plans.price_minor, plans.slug
`

type ListActiveProductsAndPlansRow struct {
	ProductID       uuid.UUID      `json:"product_id"`
	ProductSlug     string         `json:"product_slug"`
	ProductNameI18n []byte         `json:"product_name_i18n"`
	DescriptionI18n []byte         `json:"description_i18n"`
	PlanID          uuid.UUID      `json:"plan_id"`
	PlanSlug        string         `json:"plan_slug"`
	PlanNameI18n    []byte         `json:"plan_name_i18n"`
	CpuCores        pgtype.Numeric `json:"cpu_cores"`
	MemoryMb        int32          `json:"memory_mb"`
	DiskGb          int32          `json:"disk_gb"`
	TrafficGb       pgtype.Int8    `json:"traffic_gb"`
	BandwidthMbps   pgtype.Int4    `json:"bandwidth_mbps"`
	Ipv4Count       int32          `json:"ipv4_count"`
	Ipv6Count       int32          `json:"ipv6_count"`
	NatPortCount    int32          `json:"nat_port_count"`
	Virtualization  string         `json:"virtualization"`
	BillingCycle    string         `json:"billing_cycle"`
	PriceMinor      int64          `json:"price_minor"`
	Currency        string         `json:"currency"`
	StockMode       string         `json:"stock_mode"`
}

func (q *Queries) ListActiveProductsAndPlans(ctx context.Context) ([]ListActiveProductsAndPlansRow, error) {
	rows, err := q.db.Query(ctx, listActiveProductsAndPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsAndPlansRow{}
	for rows.Next() {
		var i ListActiveProductsAndPlansRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductSlug,
			&i.ProductNameI18n,
			&i.DescriptionI18n,
			&i.PlanID,
			&i.PlanSlug,
			&i.PlanNameI18n,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficGb,
			&i.BandwidthMbps,
			&i.Ipv4Count,
			&i.Ipv6Count,
			&i.NatPortCount,
			&i.Virtualization,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StockMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByUser = `-- name: ListInvoicesByUser :many
SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at FROM invoices WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByUser(ctx context.Context, userID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNo,
			&i.UserID,
			&i.SubscriptionID,
			&i.OrderID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.DueAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT orders.id, orders.order_no, orders.user_id, orders.status, orders.subtotal_minor, orders.discount_minor, orders.total_minor, orders.currency, orders.paid_at, orders.created_at, orders.updated_at, orders.idempotency_key, payments.id AS payment_id, payments.status AS payment_status, payments.gateway
FROM orders LEFT JOIN payments ON payments.order_id = orders.id
WHERE orders.user_id = $1 ORDER BY orders.created_at DESC
`

type ListOrdersByUserRow struct {
	ID             uuid.UUID          `json:"id"`
	OrderNo        string             `json:"order_no"`
	UserID         uuid.UUID          `json:"user_id"`
	Status         string             `json:"status"`
	SubtotalMinor  int64              `json:"subtotal_minor"`
	DiscountMinor  int64              `json:"discount_minor"`
	TotalMinor     int64              `json:"total_minor"`
	Currency       string             `json:"currency"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	PaymentID      *uuid.UUID         `json:"payment_id"`
	PaymentStatus  pgtype.Text        `json:"payment_status"`
	Gateway        pgtype.Text        `json:"gateway"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, userID uuid.UUID) ([]ListOrdersByUserRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByUserRow{}
	for rows.Next() {
		var i ListOrdersByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.Status,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.TotalMinor,
			&i.Currency,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
			&i.PaymentID,
			&i.PaymentStatus,
			&i.Gateway,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentOrderInvoice = `-- name: LockPaymentOrderInvoice :one
SELECT payments.id AS payment_id, payments.status AS payment_status, payments.amount_minor AS payment_amount_minor,
       payments.currency AS payment_currency, payments.order_id, orders.user_id, orders.status AS order_status,
       invoices.id AS invoice_id, invoices.status AS invoice_status
FROM payments
JOIN orders ON orders.id = payments.order_id
JOIN invoices ON invoices.order_id = orders.id
WHERE payments.id = $1 AND payments.gateway = $2
FOR UPDATE OF payments, orders, invoices
`

type LockPaymentOrderInvoiceParams struct {
	ID      uuid.UUID `json:"id"`
	Gateway string    `json:"gateway"`
}

type LockPaymentOrderInvoiceRow struct {
	PaymentID          uuid.UUID `json:"payment_id"`
	PaymentStatus      string    `json:"payment_status"`
	PaymentAmountMinor int64     `json:"payment_amount_minor"`
	PaymentCurrency    string    `json:"payment_currency"`
	OrderID            uuid.UUID `json:"order_id"`
	UserID             uuid.UUID `json:"user_id"`
	OrderStatus        string    `json:"order_status"`
	InvoiceID          uuid.UUID `json:"invoice_id"`
	InvoiceStatus      string    `json:"invoice_status"`
}

func (q *Queries) LockPaymentOrderInvoice(ctx context.Context, arg LockPaymentOrderInvoiceParams) (LockPaymentOrderInvoiceRow, error) {
	row := q.db.QueryRow(ctx, lockPaymentOrderInvoice, arg.ID, arg.Gateway)
	var i LockPaymentOrderInvoiceRow
	err := row.Scan(
		&i.PaymentID,
		&i.PaymentStatus,
		&i.PaymentAmountMinor,
		&i.PaymentCurrency,
		&i.OrderID,
		&i.UserID,
		&i.OrderStatus,
		&i.InvoiceID,
		&i.InvoiceStatus,
	)
	return i, err
}

const markInvoicePaid = `-- name: MarkInvoicePaid :exec
UPDATE invoices SET status = 'paid', paid_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkInvoicePaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvoicePaid, id)
	return err
}

const markOrderPaid = `-- name: MarkOrderPaid :exec
UPDATE orders SET status = 'paid', paid_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkOrderPaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOrderPaid, id)
	return err
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE outbox_events SET status = 'published', published_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const markOutboxRetry = `-- name: MarkOutboxRetry :exec
UPDATE outbox_events
SET attempts = attempts + 1,
    next_attempt_at = now() + make_interval(secs => LEAST(300, (1 << LEAST(attempts, 8))))
WHERE id = $1
`

func (q *Queries) MarkOutboxRetry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxRetry, id)
	return err
}

const markPaymentSucceeded = `-- name: MarkPaymentSucceeded :exec
UPDATE payments SET status = 'succeeded', gateway_payment_id = $2, gateway_payload = $3, paid_at = now(), updated_at = now()
WHERE id = $1
`

type MarkPaymentSucceededParams struct {
	ID               uuid.UUID   `json:"id"`
	GatewayPaymentID pgtype.Text `json:"gateway_payment_id"`
	GatewayPayload   []byte      `json:"gateway_payload"`
}

func (q *Queries) MarkPaymentSucceeded(ctx context.Context, arg MarkPaymentSucceededParams) error {
	_, err := q.db.Exec(ctx, markPaymentSucceeded, arg.ID, arg.GatewayPaymentID, arg.GatewayPayload)
	return err
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE payment_webhook_receipts SET processed_at = now() WHERE id = $1
`

func (q *Queries) MarkWebhookProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, id)
	return err
}
