// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foundation.sql

package sqlc

import (
	"context"
)

const databasePing = `-- name: DatabasePing :one
SELECT 1::integer
`

func (q *Queries) DatabasePing(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, databasePing)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
