// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignAdminRole = `-- name: AssignAdminRole :exec
INSERT INTO admin_roles (admin_id, role_id)
SELECT $1, id FROM roles WHERE key = $2
ON CONFLICT DO NOTHING
`

type AssignAdminRoleParams struct {
	AdminID uuid.UUID `json:"admin_id"`
	Key     string    `json:"key"`
}

func (q *Queries) AssignAdminRole(ctx context.Context, arg AssignAdminRoleParams) error {
	_, err := q.db.Exec(ctx, assignAdminRole, arg.AdminID, arg.Key)
	return err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (id, email, password_hash, status, display_name)
VALUES ($1, $2, $3, 'active', $4)
RETURNING id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at
`

type CreateAdminParams struct {
	ID           uuid.UUID   `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	DisplayName  pgtype.Text `json:"display_name"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdminSession = `-- name: CreateAdminSession :one
INSERT INTO admin_sessions (id, admin_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, admin_id, token_hash, expires_at, last_seen_at, revoked_at, created_at
`

type CreateAdminSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	AdminID   uuid.UUID          `json:"admin_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error) {
	row := q.db.QueryRow(ctx, createAdminSession,
		arg.ID,
		arg.AdminID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AdminSession
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (
  id, actor_type, actor_id, action, resource_type, resource_id,
  before_data, after_data, ip_address, user_agent, request_id, trace_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateAuditEventParams struct {
	ID           uuid.UUID   `json:"id"`
	ActorType    string      `json:"actor_type"`
	ActorID      *uuid.UUID  `json:"actor_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   *uuid.UUID  `json:"resource_id"`
	BeforeData   []byte      `json:"before_data"`
	AfterData    []byte      `json:"after_data"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	RequestID    pgtype.Text `json:"request_id"`
	TraceID      pgtype.Text `json:"trace_id"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeData,
		arg.AfterData,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.TraceID,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, status, locale, timezone)
VALUES ($1, $2, $3, 'active', $4, $5)
RETURNING id, email, password_hash, status, locale, timezone, email_verified_at, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Locale       string    `json:"locale"`
	Timezone     string    `json:"timezone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, expires_at, last_seen_at, revoked_at, created_at
`

type CreateUserSessionParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const enableAdminTOTP = `-- name: EnableAdminTOTP :exec
WITH enabled AS (
  UPDATE admin_totp_secrets SET verified_at = now() WHERE admin_id = $1 RETURNING admin_id
)
UPDATE admins SET two_factor_enabled = true, updated_at = now()
WHERE id IN (SELECT admin_id FROM enabled)
`

func (q *Queries) EnableAdminTOTP(ctx context.Context, adminID uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableAdminTOTP, adminID)
	return err
}

const getActiveAdminSession = `-- name: GetActiveAdminSession :one
SELECT admin_sessions.id, admin_sessions.admin_id, admin_sessions.token_hash, admin_sessions.expires_at, admin_sessions.last_seen_at, admin_sessions.revoked_at, admin_sessions.created_at, admins.email, admins.status AS admin_status, admins.display_name, admins.two_factor_enabled
FROM admin_sessions
JOIN admins ON admins.id = admin_sessions.admin_id
WHERE admin_sessions.token_hash = $1
  AND admin_sessions.revoked_at IS NULL
  AND admin_sessions.expires_at > now()
`

type GetActiveAdminSessionRow struct {
	ID               uuid.UUID          `json:"id"`
	AdminID          uuid.UUID          `json:"admin_id"`
	TokenHash        []byte             `json:"token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Email            string             `json:"email"`
	AdminStatus      string             `json:"admin_status"`
	DisplayName      pgtype.Text        `json:"display_name"`
	TwoFactorEnabled bool               `json:"two_factor_enabled"`
}

func (q *Queries) GetActiveAdminSession(ctx context.Context, tokenHash []byte) (GetActiveAdminSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveAdminSession, tokenHash)
	var i GetActiveAdminSessionRow
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Email,
		&i.AdminStatus,
		&i.DisplayName,
		&i.TwoFactorEnabled,
	)
	return i, err
}

const getActiveUserSession = `-- name: GetActiveUserSession :one
SELECT user_sessions.id, user_sessions.user_id, user_sessions.token_hash, user_sessions.expires_at, user_sessions.last_seen_at, user_sessions.revoked_at, user_sessions.created_at, users.email, users.status AS user_status, users.locale, users.timezone
FROM user_sessions
JOIN users ON users.id = user_sessions.user_id
WHERE user_sessions.token_hash = $1
  AND user_sessions.revoked_at IS NULL
  AND user_sessions.expires_at > now()
`

type GetActiveUserSessionRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Email      string             `json:"email"`
	UserStatus string             `json:"user_status"`
	Locale     string             `json:"locale"`
	Timezone   string             `json:"timezone"`
}

func (q *Queries) GetActiveUserSession(ctx context.Context, tokenHash []byte) (GetActiveUserSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserSession, tokenHash)
	var i GetActiveUserSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.Email,
		&i.UserStatus,
		&i.Locale,
		&i.Timezone,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at FROM admins WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at FROM admins WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminTOTPSecret = `-- name: GetAdminTOTPSecret :one
SELECT admin_id, ciphertext, nonce, created_at, verified_at FROM admin_totp_secrets WHERE admin_id = $1
`

func (q *Queries) GetAdminTOTPSecret(ctx context.Context, adminID uuid.UUID) (AdminTotpSecret, error) {
	row := q.db.QueryRow(ctx, getAdminTOTPSecret, adminID)
	var i AdminTotpSecret
	err := row.Scan(
		&i.AdminID,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, status, locale, timezone, email_verified_at, last_login_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, status, locale, timezone, email_verified_at, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.Locale,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminPermissions = `-- name: ListAdminPermissions :many
SELECT DISTINCT permissions.key
FROM permissions
JOIN role_permissions ON role_permissions.permission_id = permissions.id
JOIN admin_roles ON admin_roles.role_id = role_permissions.role_id
WHERE admin_roles.admin_id = $1
ORDER BY permissions.key
`

func (q *Queries) ListAdminPermissions(ctx context.Context, adminID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAdminPermissions, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminSession = `-- name: RevokeAdminSession :exec
UPDATE admin_sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAdminSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeAdminSession, tokenHash)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
UPDATE user_sessions SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeUserSession, tokenHash)
	return err
}

const touchAdminSession = `-- name: TouchAdminSession :exec
UPDATE admin_sessions SET last_seen_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchAdminSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAdminSession, id)
	return err
}

const touchUserSession = `-- name: TouchUserSession :exec
UPDATE user_sessions SET last_seen_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchUserSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserSession, id)
	return err
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admins SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const upsertAdminTOTPSecret = `-- name: UpsertAdminTOTPSecret :exec
INSERT INTO admin_totp_secrets (admin_id, ciphertext, nonce)
VALUES ($1, $2, $3)
ON CONFLICT (admin_id) DO UPDATE
SET ciphertext = EXCLUDED.ciphertext, nonce = EXCLUDED.nonce, created_at = now(), verified_at = NULL
`

type UpsertAdminTOTPSecretParams struct {
	AdminID    uuid.UUID `json:"admin_id"`
	Ciphertext []byte    `json:"ciphertext"`
	Nonce      []byte    `json:"nonce"`
}

func (q *Queries) UpsertAdminTOTPSecret(ctx context.Context, arg UpsertAdminTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, upsertAdminTOTPSecret, arg.AdminID, arg.Ciphertext, arg.Nonce)
	return err
}
