// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: infrastructure.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addNodeReservation = `-- name: AddNodeReservation :one
UPDATE nodes
SET cpu_reserved = cpu_reserved + $1,
    memory_reserved_mb = memory_reserved_mb + $2,
    disk_reserved_gb = disk_reserved_gb + $3,
    ipv4_reserved = ipv4_reserved + $4,
    ipv6_reserved = ipv6_reserved + $5,
    nat_port_reserved = nat_port_reserved + $6,
    version = version + 1,
    updated_at = now()
WHERE id = $7
  AND cpu_total - cpu_allocated - cpu_reserved >= $1
  AND memory_total_mb - memory_allocated_mb - memory_reserved_mb >= $2
  AND disk_total_gb - disk_allocated_gb - disk_reserved_gb >= $3
  AND ipv4_total - ipv4_allocated - ipv4_reserved >= $4
  AND ipv6_total - ipv6_allocated - ipv6_reserved >= $5
  AND nat_port_total - nat_port_allocated - nat_port_reserved >= $6
RETURNING id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at, ipv4_total, ipv4_allocated, ipv4_reserved, ipv6_total, ipv6_allocated, ipv6_reserved, nat_port_total, nat_port_allocated, nat_port_reserved
`

type AddNodeReservationParams struct {
	CpuCores     float64   `json:"cpu_cores"`
	MemoryMb     int64     `json:"memory_mb"`
	DiskGb       int64     `json:"disk_gb"`
	Ipv4Count    int32     `json:"ipv4_count"`
	Ipv6Count    int32     `json:"ipv6_count"`
	NatPortCount int32     `json:"nat_port_count"`
	NodeID       uuid.UUID `json:"node_id"`
}

func (q *Queries) AddNodeReservation(ctx context.Context, arg AddNodeReservationParams) (Node, error) {
	row := q.db.QueryRow(ctx, addNodeReservation,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Ipv4Count,
		arg.Ipv6Count,
		arg.NatPortCount,
		arg.NodeID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NodeGroupID,
		&i.ProviderNodeID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CpuTotal,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuAllocated,
		&i.MemoryAllocatedMb,
		&i.DiskAllocatedGb,
		&i.CpuReserved,
		&i.MemoryReservedMb,
		&i.DiskReservedGb,
		&i.Weight,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ipv4Total,
		&i.Ipv4Allocated,
		&i.Ipv4Reserved,
		&i.Ipv6Total,
		&i.Ipv6Allocated,
		&i.Ipv6Reserved,
		&i.NatPortTotal,
		&i.NatPortAllocated,
		&i.NatPortReserved,
	)
	return i, err
}

const commitNodeReservation = `-- name: CommitNodeReservation :one
UPDATE nodes
SET cpu_reserved = cpu_reserved - $1,
    memory_reserved_mb = memory_reserved_mb - $2,
    disk_reserved_gb = disk_reserved_gb - $3,
    ipv4_reserved = ipv4_reserved - $4,
    ipv6_reserved = ipv6_reserved - $5,
    nat_port_reserved = nat_port_reserved - $6,
    cpu_allocated = cpu_allocated + $1,
    memory_allocated_mb = memory_allocated_mb + $2,
    disk_allocated_gb = disk_allocated_gb + $3,
    ipv4_allocated = ipv4_allocated + $4,
    ipv6_allocated = ipv6_allocated + $5,
    nat_port_allocated = nat_port_allocated + $6,
    version = version + 1,
    updated_at = now()
WHERE id = $7
RETURNING id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at, ipv4_total, ipv4_allocated, ipv4_reserved, ipv6_total, ipv6_allocated, ipv6_reserved, nat_port_total, nat_port_allocated, nat_port_reserved
`

type CommitNodeReservationParams struct {
	CpuCores     float64   `json:"cpu_cores"`
	MemoryMb     int64     `json:"memory_mb"`
	DiskGb       int64     `json:"disk_gb"`
	Ipv4Count    int32     `json:"ipv4_count"`
	Ipv6Count    int32     `json:"ipv6_count"`
	NatPortCount int32     `json:"nat_port_count"`
	NodeID       uuid.UUID `json:"node_id"`
}

func (q *Queries) CommitNodeReservation(ctx context.Context, arg CommitNodeReservationParams) (Node, error) {
	row := q.db.QueryRow(ctx, commitNodeReservation,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Ipv4Count,
		arg.Ipv6Count,
		arg.NatPortCount,
		arg.NodeID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NodeGroupID,
		&i.ProviderNodeID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CpuTotal,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuAllocated,
		&i.MemoryAllocatedMb,
		&i.DiskAllocatedGb,
		&i.CpuReserved,
		&i.MemoryReservedMb,
		&i.DiskReservedGb,
		&i.Weight,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ipv4Total,
		&i.Ipv4Allocated,
		&i.Ipv4Reserved,
		&i.Ipv6Total,
		&i.Ipv6Allocated,
		&i.Ipv6Reserved,
		&i.NatPortTotal,
		&i.NatPortAllocated,
		&i.NatPortReserved,
	)
	return i, err
}

const createInfrastructureProvider = `-- name: CreateInfrastructureProvider :one
INSERT INTO providers (id, name, provider_type, endpoint, credential_ref, status, config, capabilities)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, provider_type, endpoint, credential_ref, status, version, config, capabilities, last_health_check_at, created_at, updated_at
`

type CreateInfrastructureProviderParams struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	ProviderType  string      `json:"provider_type"`
	Endpoint      pgtype.Text `json:"endpoint"`
	CredentialRef pgtype.Text `json:"credential_ref"`
	Status        string      `json:"status"`
	Config        []byte      `json:"config"`
	Capabilities  []byte      `json:"capabilities"`
}

func (q *Queries) CreateInfrastructureProvider(ctx context.Context, arg CreateInfrastructureProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createInfrastructureProvider,
		arg.ID,
		arg.Name,
		arg.ProviderType,
		arg.Endpoint,
		arg.CredentialRef,
		arg.Status,
		arg.Config,
		arg.Capabilities,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Endpoint,
		&i.CredentialRef,
		&i.Status,
		&i.Version,
		&i.Config,
		&i.Capabilities,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (
  id, provider_id, node_group_id, provider_node_id, name, region, status,
  cpu_total, memory_total_mb, disk_total_gb, ipv4_total, ipv6_total, nat_port_total,
  weight, capabilities, last_seen_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at, ipv4_total, ipv4_allocated, ipv4_reserved, ipv6_total, ipv6_allocated, ipv6_reserved, nat_port_total, nat_port_allocated, nat_port_reserved
`

type CreateNodeParams struct {
	ID             uuid.UUID          `json:"id"`
	ProviderID     uuid.UUID          `json:"provider_id"`
	NodeGroupID    *uuid.UUID         `json:"node_group_id"`
	ProviderNodeID pgtype.Text        `json:"provider_node_id"`
	Name           string             `json:"name"`
	Region         string             `json:"region"`
	Status         string             `json:"status"`
	CpuTotal       float64            `json:"cpu_total"`
	MemoryTotalMb  int64              `json:"memory_total_mb"`
	DiskTotalGb    int64              `json:"disk_total_gb"`
	Ipv4Total      int32              `json:"ipv4_total"`
	Ipv6Total      int32              `json:"ipv6_total"`
	NatPortTotal   int32              `json:"nat_port_total"`
	Weight         int32              `json:"weight"`
	Capabilities   []byte             `json:"capabilities"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.ProviderID,
		arg.NodeGroupID,
		arg.ProviderNodeID,
		arg.Name,
		arg.Region,
		arg.Status,
		arg.CpuTotal,
		arg.MemoryTotalMb,
		arg.DiskTotalGb,
		arg.Ipv4Total,
		arg.Ipv6Total,
		arg.NatPortTotal,
		arg.Weight,
		arg.Capabilities,
		arg.LastSeenAt,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NodeGroupID,
		&i.ProviderNodeID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CpuTotal,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuAllocated,
		&i.MemoryAllocatedMb,
		&i.DiskAllocatedGb,
		&i.CpuReserved,
		&i.MemoryReservedMb,
		&i.DiskReservedGb,
		&i.Weight,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ipv4Total,
		&i.Ipv4Allocated,
		&i.Ipv4Reserved,
		&i.Ipv6Total,
		&i.Ipv6Allocated,
		&i.Ipv6Reserved,
		&i.NatPortTotal,
		&i.NatPortAllocated,
		&i.NatPortReserved,
	)
	return i, err
}

const createNodeGroup = `-- name: CreateNodeGroup :one
INSERT INTO node_groups (id, name, region, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, region, status, created_at, updated_at, placement_policy
`

type CreateNodeGroupParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Region string    `json:"region"`
	Status string    `json:"status"`
}

func (q *Queries) CreateNodeGroup(ctx context.Context, arg CreateNodeGroupParams) (NodeGroup, error) {
	row := q.db.QueryRow(ctx, createNodeGroup,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.Status,
	)
	var i NodeGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlacementPolicy,
	)
	return i, err
}

const createResourceReservation = `-- name: CreateResourceReservation :one
INSERT INTO resource_reservations (
  id, node_id, operation_id, cpu_cores, memory_mb, disk_gb,
  ipv4_count, ipv6_count, nat_port_count, status, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'reserved', $10)
RETURNING id, node_id, operation_id, cpu_cores, memory_mb, disk_gb, ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at
`

type CreateResourceReservationParams struct {
	ID           uuid.UUID          `json:"id"`
	NodeID       uuid.UUID          `json:"node_id"`
	OperationID  uuid.UUID          `json:"operation_id"`
	CpuCores     float64            `json:"cpu_cores"`
	MemoryMb     int64              `json:"memory_mb"`
	DiskGb       int64              `json:"disk_gb"`
	Ipv4Count    int32              `json:"ipv4_count"`
	Ipv6Count    int32              `json:"ipv6_count"`
	NatPortCount int32              `json:"nat_port_count"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateResourceReservation(ctx context.Context, arg CreateResourceReservationParams) (ResourceReservation, error) {
	row := q.db.QueryRow(ctx, createResourceReservation,
		arg.ID,
		arg.NodeID,
		arg.OperationID,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Ipv4Count,
		arg.Ipv6Count,
		arg.NatPortCount,
		arg.ExpiresAt,
	)
	var i ResourceReservation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OperationID,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInfrastructureProviderByID = `-- name: GetInfrastructureProviderByID :one
SELECT id, name, provider_type, endpoint, credential_ref, status, version, config, capabilities, last_health_check_at, created_at, updated_at FROM providers WHERE id = $1 AND status IN ('active', 'degraded')
`

func (q *Queries) GetInfrastructureProviderByID(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getInfrastructureProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Endpoint,
		&i.CredentialRef,
		&i.Status,
		&i.Version,
		&i.Config,
		&i.Capabilities,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceReservationByOperation = `-- name: GetResourceReservationByOperation :one
SELECT id, node_id, operation_id, cpu_cores, memory_mb, disk_gb, ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at FROM resource_reservations WHERE operation_id = $1
`

func (q *Queries) GetResourceReservationByOperation(ctx context.Context, operationID uuid.UUID) (ResourceReservation, error) {
	row := q.db.QueryRow(ctx, getResourceReservationByOperation, operationID)
	var i ResourceReservation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OperationID,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInfrastructureProviders = `-- name: ListInfrastructureProviders :many
SELECT id, name, provider_type, endpoint, credential_ref, status, version, config, capabilities, last_health_check_at, created_at, updated_at FROM providers ORDER BY name, id
`

func (q *Queries) ListInfrastructureProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listInfrastructureProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Endpoint,
			&i.CredentialRef,
			&i.Status,
			&i.Version,
			&i.Config,
			&i.Capabilities,
			&i.LastHealthCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeGroups = `-- name: ListNodeGroups :many
SELECT id, name, region, status, created_at, updated_at, placement_policy FROM node_groups ORDER BY region, name, id
`

func (q *Queries) ListNodeGroups(ctx context.Context) ([]NodeGroup, error) {
	rows, err := q.db.Query(ctx, listNodeGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeGroup{}
	for rows.Next() {
		var i NodeGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlacementPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at, ipv4_total, ipv4_allocated, ipv4_reserved, ipv6_total, ipv6_allocated, ipv6_reserved, nat_port_total, nat_port_allocated, nat_port_reserved FROM nodes ORDER BY region, name, id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.NodeGroupID,
			&i.ProviderNodeID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CpuTotal,
			&i.MemoryTotalMb,
			&i.DiskTotalGb,
			&i.CpuAllocated,
			&i.MemoryAllocatedMb,
			&i.DiskAllocatedGb,
			&i.CpuReserved,
			&i.MemoryReservedMb,
			&i.DiskReservedGb,
			&i.Weight,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ipv4Total,
			&i.Ipv4Allocated,
			&i.Ipv4Reserved,
			&i.Ipv6Total,
			&i.Ipv6Allocated,
			&i.Ipv6Reserved,
			&i.NatPortTotal,
			&i.NatPortAllocated,
			&i.NatPortReserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockResourceReservation = `-- name: LockResourceReservation :one
SELECT id, node_id, operation_id, cpu_cores, memory_mb, disk_gb, ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at FROM resource_reservations WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockResourceReservation(ctx context.Context, id uuid.UUID) (ResourceReservation, error) {
	row := q.db.QueryRow(ctx, lockResourceReservation, id)
	var i ResourceReservation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OperationID,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseNodeReservation = `-- name: ReleaseNodeReservation :one
UPDATE nodes
SET cpu_reserved = cpu_reserved - $1,
    memory_reserved_mb = memory_reserved_mb - $2,
    disk_reserved_gb = disk_reserved_gb - $3,
    ipv4_reserved = ipv4_reserved - $4,
    ipv6_reserved = ipv6_reserved - $5,
    nat_port_reserved = nat_port_reserved - $6,
    version = version + 1,
    updated_at = now()
WHERE id = $7
RETURNING id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at, ipv4_total, ipv4_allocated, ipv4_reserved, ipv6_total, ipv6_allocated, ipv6_reserved, nat_port_total, nat_port_allocated, nat_port_reserved
`

type ReleaseNodeReservationParams struct {
	CpuCores     float64   `json:"cpu_cores"`
	MemoryMb     int64     `json:"memory_mb"`
	DiskGb       int64     `json:"disk_gb"`
	Ipv4Count    int32     `json:"ipv4_count"`
	Ipv6Count    int32     `json:"ipv6_count"`
	NatPortCount int32     `json:"nat_port_count"`
	NodeID       uuid.UUID `json:"node_id"`
}

func (q *Queries) ReleaseNodeReservation(ctx context.Context, arg ReleaseNodeReservationParams) (Node, error) {
	row := q.db.QueryRow(ctx, releaseNodeReservation,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Ipv4Count,
		arg.Ipv6Count,
		arg.NatPortCount,
		arg.NodeID,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NodeGroupID,
		&i.ProviderNodeID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CpuTotal,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuAllocated,
		&i.MemoryAllocatedMb,
		&i.DiskAllocatedGb,
		&i.CpuReserved,
		&i.MemoryReservedMb,
		&i.DiskReservedGb,
		&i.Weight,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ipv4Total,
		&i.Ipv4Allocated,
		&i.Ipv4Reserved,
		&i.Ipv6Total,
		&i.Ipv6Allocated,
		&i.Ipv6Reserved,
		&i.NatPortTotal,
		&i.NatPortAllocated,
		&i.NatPortReserved,
	)
	return i, err
}

const selectCandidateNodesForUpdate = `-- name: SelectCandidateNodesForUpdate :many
SELECT nodes.id, nodes.provider_id, nodes.node_group_id, nodes.provider_node_id, nodes.name, nodes.region, nodes.status, nodes.cpu_total, nodes.memory_total_mb, nodes.disk_total_gb, nodes.cpu_allocated, nodes.memory_allocated_mb, nodes.disk_allocated_gb, nodes.cpu_reserved, nodes.memory_reserved_mb, nodes.disk_reserved_gb, nodes.weight, nodes.capabilities, nodes.last_seen_at, nodes.version, nodes.created_at, nodes.updated_at, nodes.ipv4_total, nodes.ipv4_allocated, nodes.ipv4_reserved, nodes.ipv6_total, nodes.ipv6_allocated, nodes.ipv6_reserved, nodes.nat_port_total, nodes.nat_port_allocated, nodes.nat_port_reserved
FROM nodes
JOIN providers ON providers.id = nodes.provider_id
JOIN node_groups ON node_groups.id = nodes.node_group_id
WHERE nodes.node_group_id = $1
  AND nodes.status = 'online'
  AND providers.status = 'active'
  AND node_groups.status = 'active'
  AND nodes.capabilities @> $2::jsonb
  AND nodes.cpu_total - nodes.cpu_allocated - nodes.cpu_reserved >= $3
  AND nodes.memory_total_mb - nodes.memory_allocated_mb - nodes.memory_reserved_mb >= $4
  AND nodes.disk_total_gb - nodes.disk_allocated_gb - nodes.disk_reserved_gb >= $5
  AND nodes.ipv4_total - nodes.ipv4_allocated - nodes.ipv4_reserved >= $6
  AND nodes.ipv6_total - nodes.ipv6_allocated - nodes.ipv6_reserved >= $7
  AND nodes.nat_port_total - nodes.nat_port_allocated - nodes.nat_port_reserved >= $8
ORDER BY CASE WHEN node_groups.placement_policy = 'pack' THEN -1 ELSE 1 END * GREATEST(
    COALESCE((nodes.cpu_allocated + nodes.cpu_reserved + $3) / NULLIF(nodes.cpu_total, 0), 0),
    COALESCE((nodes.memory_allocated_mb + nodes.memory_reserved_mb + $4)::numeric / NULLIF(nodes.memory_total_mb, 0), 0),
    COALESCE((nodes.disk_allocated_gb + nodes.disk_reserved_gb + $5)::numeric / NULLIF(nodes.disk_total_gb, 0), 0)
  ) ASC,
  nodes.weight DESC,
  nodes.id ASC
FOR UPDATE OF nodes
`

type SelectCandidateNodesForUpdateParams struct {
	NodeGroupID          *uuid.UUID `json:"node_group_id"`
	RequiredCapabilities []byte     `json:"required_capabilities"`
	CpuCores             float64    `json:"cpu_cores"`
	MemoryMb             int64      `json:"memory_mb"`
	DiskGb               int64      `json:"disk_gb"`
	Ipv4Count            int32      `json:"ipv4_count"`
	Ipv6Count            int32      `json:"ipv6_count"`
	NatPortCount         int32      `json:"nat_port_count"`
}

func (q *Queries) SelectCandidateNodesForUpdate(ctx context.Context, arg SelectCandidateNodesForUpdateParams) ([]Node, error) {
	rows, err := q.db.Query(ctx, selectCandidateNodesForUpdate,
		arg.NodeGroupID,
		arg.RequiredCapabilities,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Ipv4Count,
		arg.Ipv6Count,
		arg.NatPortCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.NodeGroupID,
			&i.ProviderNodeID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CpuTotal,
			&i.MemoryTotalMb,
			&i.DiskTotalGb,
			&i.CpuAllocated,
			&i.MemoryAllocatedMb,
			&i.DiskAllocatedGb,
			&i.CpuReserved,
			&i.MemoryReservedMb,
			&i.DiskReservedGb,
			&i.Weight,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ipv4Total,
			&i.Ipv4Allocated,
			&i.Ipv4Reserved,
			&i.Ipv6Total,
			&i.Ipv6Allocated,
			&i.Ipv6Reserved,
			&i.NatPortTotal,
			&i.NatPortAllocated,
			&i.NatPortReserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResourceReservationStatus = `-- name: SetResourceReservationStatus :one
UPDATE resource_reservations
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, node_id, operation_id, cpu_cores, memory_mb, disk_gb, ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at
`

type SetResourceReservationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetResourceReservationStatus(ctx context.Context, arg SetResourceReservationStatusParams) (ResourceReservation, error) {
	row := q.db.QueryRow(ctx, setResourceReservationStatus, arg.ID, arg.Status)
	var i ResourceReservation
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OperationID,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
