// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"password_hash"`
	Status           string             `json:"status"`
	DisplayName      pgtype.Text        `json:"display_name"`
	TwoFactorEnabled bool               `json:"two_factor_enabled"`
	LastLoginAt      pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type AdminRole struct {
	AdminID uuid.UUID `json:"admin_id"`
	RoleID  uuid.UUID `json:"role_id"`
}

type AdminSession struct {
	ID         uuid.UUID          `json:"id"`
	AdminID    uuid.UUID          `json:"admin_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AdminTotpSecret struct {
	AdminID    uuid.UUID          `json:"admin_id"`
	Ciphertext []byte             `json:"ciphertext"`
	Nonce      []byte             `json:"nonce"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
}

type AgentCommand struct {
	ID             uuid.UUID          `json:"id"`
	NodeID         uuid.UUID          `json:"node_id"`
	OperationID    *uuid.UUID         `json:"operation_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	CommandType    string             `json:"command_type"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Result         []byte             `json:"result"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DispatchedAt   pgtype.Timestamptz `json:"dispatched_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AgentConnection struct {
	NodeID          uuid.UUID          `json:"node_id"`
	ConnectionID    uuid.UUID          `json:"connection_id"`
	Status          string             `json:"status"`
	RemoteAddress   pgtype.Text        `json:"remote_address"`
	AgentVersion    pgtype.Text        `json:"agent_version"`
	ConnectedAt     pgtype.Timestamptz `json:"connected_at"`
	DisconnectedAt  pgtype.Timestamptz `json:"disconnected_at"`
	LastHeartbeatAt pgtype.Timestamptz `json:"last_heartbeat_at"`
}

type AgentImage struct {
	NodeID    uuid.UUID          `json:"node_id"`
	ImageID   string             `json:"image_id"`
	Name      string             `json:"name"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AgentMessage struct {
	MessageID  string             `json:"message_id"`
	NodeID     uuid.UUID          `json:"node_id"`
	ReceivedAt pgtype.Timestamptz `json:"received_at"`
}

type AgentPortForward struct {
	NodeID      uuid.UUID          `json:"node_id"`
	InstanceID  uuid.UUID          `json:"instance_id"`
	Protocol    string             `json:"protocol"`
	HostPort    int32              `json:"host_port"`
	GuestPort   int32              `json:"guest_port"`
	Description string             `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AgentToken struct {
	ID         uuid.UUID          `json:"id"`
	NodeID     uuid.UUID          `json:"node_id"`
	TokenHash  []byte             `json:"token_hash"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type AgentVmState struct {
	NodeID            uuid.UUID          `json:"node_id"`
	InstanceID        uuid.UUID          `json:"instance_id"`
	Status            string             `json:"status"`
	CpuPercent        float64            `json:"cpu_percent"`
	RamUsedMb         int64              `json:"ram_used_mb"`
	TrafficInBytes    int64              `json:"traffic_in_bytes"`
	TrafficOutBytes   int64              `json:"traffic_out_bytes"`
	MonthlyTrafficIn  int64              `json:"monthly_traffic_in"`
	MonthlyTrafficOut int64              `json:"monthly_traffic_out"`
	Ips               []byte             `json:"ips"`
	ObservedAt        pgtype.Timestamptz `json:"observed_at"`
}

type AuditEvent struct {
	ID           uuid.UUID          `json:"id"`
	ActorType    string             `json:"actor_type"`
	ActorID      *uuid.UUID         `json:"actor_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   *uuid.UUID         `json:"resource_id"`
	BeforeData   []byte             `json:"before_data"`
	AfterData    []byte             `json:"after_data"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	RequestID    pgtype.Text        `json:"request_id"`
	TraceID      pgtype.Text        `json:"trace_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BillingProfile struct {
	UserID      uuid.UUID          `json:"user_id"`
	LegalName   string             `json:"legal_name"`
	TaxID       string             `json:"tax_id"`
	CountryCode string             `json:"country_code"`
	Address     []byte             `json:"address"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Instance struct {
	ID                 uuid.UUID          `json:"id"`
	SubscriptionID     uuid.UUID          `json:"subscription_id"`
	NodeID             *uuid.UUID         `json:"node_id"`
	ProviderID         *uuid.UUID         `json:"provider_id"`
	ProviderInstanceID pgtype.Text        `json:"provider_instance_id"`
	Name               string             `json:"name"`
	DesiredState       string             `json:"desired_state"`
	ObservedState      string             `json:"observed_state"`
	CpuCores           float64            `json:"cpu_cores"`
	MemoryMb           int32              `json:"memory_mb"`
	DiskGb             int32              `json:"disk_gb"`
	TrafficLimitGb     pgtype.Int8        `json:"traffic_limit_gb"`
	BandwidthMbps      pgtype.Int4        `json:"bandwidth_mbps"`
	ImageID            pgtype.Text        `json:"image_id"`
	PrimaryIpv4        *netip.Addr        `json:"primary_ipv4"`
	PrimaryIpv6        *netip.Addr        `json:"primary_ipv6"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
	Version            int64              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type InstanceNetwork struct {
	ID                uuid.UUID          `json:"id"`
	InstanceID        uuid.UUID          `json:"instance_id"`
	Type              string             `json:"type"`
	Address           *netip.Addr        `json:"address"`
	Gateway           *netip.Addr        `json:"gateway"`
	Prefix            pgtype.Int4        `json:"prefix"`
	ProviderNetworkID pgtype.Text        `json:"provider_network_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID                     uuid.UUID          `json:"id"`
	InvoiceNo              string             `json:"invoice_no"`
	UserID                 uuid.UUID          `json:"user_id"`
	SubscriptionID         *uuid.UUID         `json:"subscription_id"`
	OrderID                *uuid.UUID         `json:"order_id"`
	Status                 string             `json:"status"`
	AmountMinor            int64              `json:"amount_minor"`
	Currency               string             `json:"currency"`
	DueAt                  pgtype.Timestamptz `json:"due_at"`
	PaidAt                 pgtype.Timestamptz `json:"paid_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	BillingProfileSnapshot []byte             `json:"billing_profile_snapshot"`
}

type InvoiceItem struct {
	ID              uuid.UUID          `json:"id"`
	InvoiceID       uuid.UUID          `json:"invoice_id"`
	DescriptionI18n []byte             `json:"description_i18n"`
	Quantity        int32              `json:"quantity"`
	UnitAmountMinor int64              `json:"unit_amount_minor"`
	TotalMinor      int64              `json:"total_minor"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type LedgerEntry struct {
	ID            uuid.UUID          `json:"id"`
	TransactionID uuid.UUID          `json:"transaction_id"`
	AccountType   string             `json:"account_type"`
	AccountID     uuid.UUID          `json:"account_id"`
	Direction     string             `json:"direction"`
	AmountMinor   int64              `json:"amount_minor"`
	Currency      string             `json:"currency"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type LedgerTransaction struct {
	ID            uuid.UUID          `json:"id"`
	Type          string             `json:"type"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferenceID   *uuid.UUID         `json:"reference_id"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Node struct {
	ID                uuid.UUID          `json:"id"`
	ProviderID        uuid.UUID          `json:"provider_id"`
	NodeGroupID       *uuid.UUID         `json:"node_group_id"`
	ProviderNodeID    pgtype.Text        `json:"provider_node_id"`
	Name              string             `json:"name"`
	Region            string             `json:"region"`
	Status            string             `json:"status"`
	CpuTotal          float64            `json:"cpu_total"`
	MemoryTotalMb     int64              `json:"memory_total_mb"`
	DiskTotalGb       int64              `json:"disk_total_gb"`
	CpuAllocated      float64            `json:"cpu_allocated"`
	MemoryAllocatedMb int64              `json:"memory_allocated_mb"`
	DiskAllocatedGb   int64              `json:"disk_allocated_gb"`
	CpuReserved       float64            `json:"cpu_reserved"`
	MemoryReservedMb  int64              `json:"memory_reserved_mb"`
	DiskReservedGb    int64              `json:"disk_reserved_gb"`
	Weight            int32              `json:"weight"`
	Capabilities      []byte             `json:"capabilities"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Ipv4Total         int32              `json:"ipv4_total"`
	Ipv4Allocated     int32              `json:"ipv4_allocated"`
	Ipv4Reserved      int32              `json:"ipv4_reserved"`
	Ipv6Total         int32              `json:"ipv6_total"`
	Ipv6Allocated     int32              `json:"ipv6_allocated"`
	Ipv6Reserved      int32              `json:"ipv6_reserved"`
	NatPortTotal      int32              `json:"nat_port_total"`
	NatPortAllocated  int32              `json:"nat_port_allocated"`
	NatPortReserved   int32              `json:"nat_port_reserved"`
}

type NodeGroup struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Region          string             `json:"region"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PlacementPolicy string             `json:"placement_policy"`
}

type Notification struct {
	ID         uuid.UUID          `json:"id"`
	UserID     *uuid.UUID         `json:"user_id"`
	AdminID    *uuid.UUID         `json:"admin_id"`
	Type       string             `json:"type"`
	TitleKey   string             `json:"title_key"`
	MessageKey string             `json:"message_key"`
	Parameters []byte             `json:"parameters"`
	Severity   string             `json:"severity"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Operation struct {
	ID                  uuid.UUID          `json:"id"`
	Type                string             `json:"type"`
	ResourceType        string             `json:"resource_type"`
	ResourceID          uuid.UUID          `json:"resource_id"`
	Status              string             `json:"status"`
	Phase               pgtype.Text        `json:"phase"`
	Progress            int32              `json:"progress"`
	MessageKey          pgtype.Text        `json:"message_key"`
	ProviderID          *uuid.UUID         `json:"provider_id"`
	ProviderOperationID pgtype.Text        `json:"provider_operation_id"`
	IdempotencyKey      string             `json:"idempotency_key"`
	Retryable           bool               `json:"retryable"`
	RetryCount          int32              `json:"retry_count"`
	MaxRetries          int32              `json:"max_retries"`
	ErrorCode           pgtype.Text        `json:"error_code"`
	ErrorMessage        pgtype.Text        `json:"error_message"`
	TraceID             string             `json:"trace_id"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	FinishedAt          pgtype.Timestamptz `json:"finished_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UserID              *uuid.UUID         `json:"user_id"`
	ActorAdminID        *uuid.UUID         `json:"actor_admin_id"`
	NextAttemptAt       pgtype.Timestamptz `json:"next_attempt_at"`
	HeartbeatAt         pgtype.Timestamptz `json:"heartbeat_at"`
	Input               []byte             `json:"input"`
	DeadlineAt          pgtype.Timestamptz `json:"deadline_at"`
	ParentOperationID   *uuid.UUID         `json:"parent_operation_id"`
}

type OperationAttempt struct {
	ID           uuid.UUID          `json:"id"`
	OperationID  uuid.UUID          `json:"operation_id"`
	Attempt      int32              `json:"attempt"`
	Status       string             `json:"status"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	WorkerID     pgtype.Text        `json:"worker_id"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

type OperationStep struct {
	ID           uuid.UUID          `json:"id"`
	OperationID  uuid.UUID          `json:"operation_id"`
	StepKey      string             `json:"step_key"`
	StepOrder    int32              `json:"step_order"`
	Status       string             `json:"status"`
	Progress     int32              `json:"progress"`
	Attempt      int32              `json:"attempt"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Output       []byte             `json:"output"`
}

type Order struct {
	ID                uuid.UUID          `json:"id"`
	OrderNo           string             `json:"order_no"`
	UserID            uuid.UUID          `json:"user_id"`
	Status            string             `json:"status"`
	SubtotalMinor     int64              `json:"subtotal_minor"`
	DiscountMinor     int64              `json:"discount_minor"`
	TotalMinor        int64              `json:"total_minor"`
	Currency          string             `json:"currency"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	Kind              string             `json:"kind"`
	SubscriptionID    *uuid.UUID         `json:"subscription_id"`
	PromotionSnapshot []byte             `json:"promotion_snapshot"`
}

type OrderItem struct {
	ID              uuid.UUID          `json:"id"`
	OrderID         uuid.UUID          `json:"order_id"`
	ProductID       uuid.UUID          `json:"product_id"`
	PlanID          uuid.UUID          `json:"plan_id"`
	Quantity        int32              `json:"quantity"`
	UnitPriceMinor  int64              `json:"unit_price_minor"`
	TotalMinor      int64              `json:"total_minor"`
	ProductSnapshot []byte             `json:"product_snapshot"`
	PlanSnapshot    []byte             `json:"plan_snapshot"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type OutboxEvent struct {
	ID             uuid.UUID          `json:"id"`
	EventType      string             `json:"event_type"`
	AggregateType  string             `json:"aggregate_type"`
	AggregateID    uuid.UUID          `json:"aggregate_id"`
	Payload        []byte             `json:"payload"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	LastError      pgtype.Text        `json:"last_error"`
	DeadLetteredAt pgtype.Timestamptz `json:"dead_lettered_at"`
	ReplayedAt     pgtype.Timestamptz `json:"replayed_at"`
	ReplayedBy     *uuid.UUID         `json:"replayed_by"`
}

type Payment struct {
	ID               uuid.UUID          `json:"id"`
	PaymentNo        string             `json:"payment_no"`
	OrderID          uuid.UUID          `json:"order_id"`
	Gateway          string             `json:"gateway"`
	GatewayPaymentID pgtype.Text        `json:"gateway_payment_id"`
	Status           string             `json:"status"`
	AmountMinor      int64              `json:"amount_minor"`
	Currency         string             `json:"currency"`
	IdempotencyKey   string             `json:"idempotency_key"`
	GatewayPayload   []byte             `json:"gateway_payload"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RefundedMinor    int64              `json:"refunded_minor"`
}

type PaymentWebhookReceipt struct {
	ID              uuid.UUID          `json:"id"`
	Gateway         string             `json:"gateway"`
	ExternalEventID string             `json:"external_event_id"`
	Payload         []byte             `json:"payload"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

type Permission struct {
	ID  uuid.UUID `json:"id"`
	Key string    `json:"key"`
}

type Plan struct {
	ID                       uuid.UUID          `json:"id"`
	ProductID                uuid.UUID          `json:"product_id"`
	NodeGroupID              *uuid.UUID         `json:"node_group_id"`
	Slug                     string             `json:"slug"`
	NameI18n                 []byte             `json:"name_i18n"`
	Status                   string             `json:"status"`
	CpuCores                 float64            `json:"cpu_cores"`
	MemoryMb                 int32              `json:"memory_mb"`
	DiskGb                   int32              `json:"disk_gb"`
	TrafficGb                pgtype.Int8        `json:"traffic_gb"`
	BandwidthMbps            pgtype.Int4        `json:"bandwidth_mbps"`
	Ipv4Count                int32              `json:"ipv4_count"`
	Ipv6Count                int32              `json:"ipv6_count"`
	NatPortCount             int32              `json:"nat_port_count"`
	Virtualization           string             `json:"virtualization"`
	BillingCycle             string             `json:"billing_cycle"`
	PriceMinor               int64              `json:"price_minor"`
	Currency                 string             `json:"currency"`
	StockMode                string             `json:"stock_mode"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DefaultImageID           string             `json:"default_image_id"`
	StockQuantity            pgtype.Int4        `json:"stock_quantity"`
	SetupFeeMinor            int64              `json:"setup_fee_minor"`
	TrafficOveragePriceMinor int64              `json:"traffic_overage_price_minor"`
	Metadata                 []byte             `json:"metadata"`
}

type PortForward struct {
	ID                uuid.UUID          `json:"id"`
	InstanceID        uuid.UUID          `json:"instance_id"`
	Protocol          string             `json:"protocol"`
	PublicIp          netip.Addr         `json:"public_ip"`
	PublicPort        int32              `json:"public_port"`
	GuestPort         int32              `json:"guest_port"`
	Description       pgtype.Text        `json:"description"`
	Status            string             `json:"status"`
	ProviderMappingID pgtype.Text        `json:"provider_mapping_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	OperationID       *uuid.UUID         `json:"operation_id"`
	ErrorCode         pgtype.Text        `json:"error_code"`
}

type Product struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	NameI18n        []byte             `json:"name_i18n"`
	DescriptionI18n []byte             `json:"description_i18n"`
	Status          string             `json:"status"`
	SortOrder       int32              `json:"sort_order"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ProductType     string             `json:"product_type"`
	Featured        bool               `json:"featured"`
}

type Promotion struct {
	ID              uuid.UUID          `json:"id"`
	Code            string             `json:"code"`
	Status          string             `json:"status"`
	DiscountType    string             `json:"discount_type"`
	DiscountValue   int64              `json:"discount_value"`
	Currency        pgtype.Text        `json:"currency"`
	StartsAt        pgtype.Timestamptz `json:"starts_at"`
	EndsAt          pgtype.Timestamptz `json:"ends_at"`
	MaxRedemptions  pgtype.Int4        `json:"max_redemptions"`
	RedemptionCount int32              `json:"redemption_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PromotionRedemption struct {
	ID            uuid.UUID          `json:"id"`
	PromotionID   uuid.UUID          `json:"promotion_id"`
	OrderID       uuid.UUID          `json:"order_id"`
	UserID        uuid.UUID          `json:"user_id"`
	DiscountMinor int64              `json:"discount_minor"`
	Snapshot      []byte             `json:"snapshot"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Provider struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	ProviderType      string             `json:"provider_type"`
	Endpoint          pgtype.Text        `json:"endpoint"`
	CredentialRef     pgtype.Text        `json:"credential_ref"`
	Status            string             `json:"status"`
	Version           pgtype.Text        `json:"version"`
	Config            []byte             `json:"config"`
	Capabilities      []byte             `json:"capabilities"`
	LastHealthCheckAt pgtype.Timestamptz `json:"last_health_check_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ProviderHealthCheck struct {
	ID           uuid.UUID          `json:"id"`
	ProviderID   uuid.UUID          `json:"provider_id"`
	Status       string             `json:"status"`
	Version      pgtype.Text        `json:"version"`
	LatencyMs    int32              `json:"latency_ms"`
	Capabilities []byte             `json:"capabilities"`
	Details      []byte             `json:"details"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	CheckedAt    pgtype.Timestamptz `json:"checked_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Refund struct {
	ID                  uuid.UUID          `json:"id"`
	PaymentID           uuid.UUID          `json:"payment_id"`
	AmountMinor         int64              `json:"amount_minor"`
	Currency            string             `json:"currency"`
	Reason              string             `json:"reason"`
	Status              string             `json:"status"`
	IdempotencyKey      string             `json:"idempotency_key"`
	LedgerTransactionID uuid.UUID          `json:"ledger_transaction_id"`
	CreatedBy           *uuid.UUID         `json:"created_by"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ResourceReservation struct {
	ID           uuid.UUID          `json:"id"`
	NodeID       uuid.UUID          `json:"node_id"`
	OperationID  uuid.UUID          `json:"operation_id"`
	CpuCores     float64            `json:"cpu_cores"`
	MemoryMb     int64              `json:"memory_mb"`
	DiskGb       int64              `json:"disk_gb"`
	Ipv4Count    int32              `json:"ipv4_count"`
	Ipv6Count    int32              `json:"ipv6_count"`
	NatPortCount int32              `json:"nat_port_count"`
	Status       string             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID        uuid.UUID          `json:"id"`
	Key       string             `json:"key"`
	NameKey   string             `json:"name_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type SchedulerDecision struct {
	ID                   uuid.UUID          `json:"id"`
	OperationID          uuid.UUID          `json:"operation_id"`
	NodeGroupID          uuid.UUID          `json:"node_group_id"`
	SelectedNodeID       *uuid.UUID         `json:"selected_node_id"`
	PlacementPolicy      string             `json:"placement_policy"`
	CandidateCount       int32              `json:"candidate_count"`
	RequestedResources   []byte             `json:"requested_resources"`
	RequiredCapabilities []byte             `json:"required_capabilities"`
	SelectedScore        pgtype.Numeric     `json:"selected_score"`
	Result               string             `json:"result"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	BillingCycle       string             `json:"billing_cycle"`
	PriceMinor         int64              `json:"price_minor"`
	Currency           string             `json:"currency"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
	GraceUntil         pgtype.Timestamptz `json:"grace_until"`
	CancelAtPeriodEnd  bool               `json:"cancel_at_period_end"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	Version            int64              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SourceOrderID      *uuid.UUID         `json:"source_order_id"`
	SourceItemIndex    pgtype.Int4        `json:"source_item_index"`
}

type SystemSetting struct {
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	IsSecret  bool               `json:"is_secret"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy *uuid.UUID         `json:"updated_by"`
}

type Ticket struct {
	ID        uuid.UUID          `json:"id"`
	TicketNo  string             `json:"ticket_no"`
	UserID    uuid.UUID          `json:"user_id"`
	Subject   string             `json:"subject"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ClosedAt  pgtype.Timestamptz `json:"closed_at"`
}

type TicketMessage struct {
	ID         uuid.UUID          `json:"id"`
	TicketID   uuid.UUID          `json:"ticket_id"`
	SenderType string             `json:"sender_type"`
	SenderID   *uuid.UUID         `json:"sender_id"`
	Message    string             `json:"message"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type TrafficUsage struct {
	ID          uuid.UUID          `json:"id"`
	InstanceID  uuid.UUID          `json:"instance_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	RxBytes     int64              `json:"rx_bytes"`
	TxBytes     int64              `json:"tx_bytes"`
	Source      string             `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type UsageBillingPeriod struct {
	ID                     uuid.UUID          `json:"id"`
	SubscriptionID         uuid.UUID          `json:"subscription_id"`
	InstanceID             uuid.UUID          `json:"instance_id"`
	PeriodStart            pgtype.Timestamptz `json:"period_start"`
	PeriodEnd              pgtype.Timestamptz `json:"period_end"`
	IncludedBytes          int64              `json:"included_bytes"`
	UsedBytes              int64              `json:"used_bytes"`
	OverageBytes           int64              `json:"overage_bytes"`
	OveragePriceMinorPerGb int64              `json:"overage_price_minor_per_gb"`
	AmountMinor            int64              `json:"amount_minor"`
	Currency               string             `json:"currency"`
	Status                 string             `json:"status"`
	InvoiceID              *uuid.UUID         `json:"invoice_id"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type UsageCharge struct {
	ID                   uuid.UUID          `json:"id"`
	UsageBillingPeriodID uuid.UUID          `json:"usage_billing_period_id"`
	InvoiceID            uuid.UUID          `json:"invoice_id"`
	LedgerTransactionID  uuid.UUID          `json:"ledger_transaction_id"`
	AmountMinor          int64              `json:"amount_minor"`
	Currency             string             `json:"currency"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type UsageSample struct {
	ID            uuid.UUID          `json:"id"`
	ProviderID    uuid.UUID          `json:"provider_id"`
	InstanceID    uuid.UUID          `json:"instance_id"`
	SourceEventID string             `json:"source_event_id"`
	PeriodStart   pgtype.Timestamptz `json:"period_start"`
	PeriodEnd     pgtype.Timestamptz `json:"period_end"`
	RxBytes       int64              `json:"rx_bytes"`
	TxBytes       int64              `json:"tx_bytes"`
	CollectedAt   pgtype.Timestamptz `json:"collected_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Status          string             `json:"status"`
	Locale          string             `json:"locale"`
	Timezone        string             `json:"timezone"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserSession struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Wallet struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	Currency              string             `json:"currency"`
	AvailableBalanceMinor int64              `json:"available_balance_minor"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}
