// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operation.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueOperationRetries = `-- name: ClaimDueOperationRetries :many
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at FROM operations
WHERE status = 'retrying' AND next_attempt_at <= now()
ORDER BY next_attempt_at, created_at
FOR UPDATE SKIP LOCKED
LIMIT $1
`

func (q *Queries) ClaimDueOperationRetries(ctx context.Context, limit int32) ([]Operation, error) {
	rows, err := q.db.Query(ctx, claimDueOperationRetries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
			&i.Phase,
			&i.Progress,
			&i.MessageKey,
			&i.ProviderID,
			&i.ProviderOperationID,
			&i.IdempotencyKey,
			&i.Retryable,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.TraceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ActorAdminID,
			&i.NextAttemptAt,
			&i.HeartbeatAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimOperation = `-- name: ClaimOperation :one
UPDATE operations
SET status = 'running', phase = COALESCE(phase, 'starting'), started_at = COALESCE(started_at, now()),
    heartbeat_at = now(), updated_at = now()
WHERE id = $1 AND status = 'queued' AND next_attempt_at <= now()
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at
`

func (q *Queries) ClaimOperation(ctx context.Context, id uuid.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, claimOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const completeOperation = `-- name: CompleteOperation :one
UPDATE operations
SET status = $2, phase = $3, progress = $4, message_key = $5,
    retryable = false, error_code = $6, error_message = $7,
    heartbeat_at = now(), finished_at = now(), updated_at = now()
WHERE id = $1 AND status NOT IN ('succeeded', 'failed', 'cancelled')
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at
`

type CompleteOperationParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	Phase        pgtype.Text `json:"phase"`
	Progress     int32       `json:"progress"`
	MessageKey   pgtype.Text `json:"message_key"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) CompleteOperation(ctx context.Context, arg CompleteOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, completeOperation,
		arg.ID,
		arg.Status,
		arg.Phase,
		arg.Progress,
		arg.MessageKey,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (
  id, type, resource_type, resource_id, status, phase, progress, message_key,
  idempotency_key, retryable, retry_count, max_retries, trace_id, user_id, actor_admin_id, next_attempt_at
)
VALUES ($1, $2, $3, $4, 'queued', 'queued', 0, $5, $6, false, 0, $7, $8, $9, $10, now())
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at
`

type CreateOperationParams struct {
	ID             uuid.UUID   `json:"id"`
	Type           string      `json:"type"`
	ResourceType   string      `json:"resource_type"`
	ResourceID     uuid.UUID   `json:"resource_id"`
	MessageKey     pgtype.Text `json:"message_key"`
	IdempotencyKey string      `json:"idempotency_key"`
	MaxRetries     int32       `json:"max_retries"`
	TraceID        string      `json:"trace_id"`
	UserID         *uuid.UUID  `json:"user_id"`
	ActorAdminID   *uuid.UUID  `json:"actor_admin_id"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ID,
		arg.Type,
		arg.ResourceType,
		arg.ResourceID,
		arg.MessageKey,
		arg.IdempotencyKey,
		arg.MaxRetries,
		arg.TraceID,
		arg.UserID,
		arg.ActorAdminID,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const createOperationStep = `-- name: CreateOperationStep :one
INSERT INTO operation_steps (id, operation_id, step_key, step_order, status, progress)
VALUES ($1, $2, $3, $4, 'pending', 0)
RETURNING id, operation_id, step_key, step_order, status, progress, attempt, error_code, error_message, started_at, finished_at, created_at, updated_at, output
`

type CreateOperationStepParams struct {
	ID          uuid.UUID `json:"id"`
	OperationID uuid.UUID `json:"operation_id"`
	StepKey     string    `json:"step_key"`
	StepOrder   int32     `json:"step_order"`
}

func (q *Queries) CreateOperationStep(ctx context.Context, arg CreateOperationStepParams) (OperationStep, error) {
	row := q.db.QueryRow(ctx, createOperationStep,
		arg.ID,
		arg.OperationID,
		arg.StepKey,
		arg.StepOrder,
	)
	var i OperationStep
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.StepKey,
		&i.StepOrder,
		&i.Status,
		&i.Progress,
		&i.Attempt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Output,
	)
	return i, err
}

const getOperationByID = `-- name: GetOperationByID :one
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at FROM operations WHERE id = $1
`

func (q *Queries) GetOperationByID(ctx context.Context, id uuid.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByID, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const getOperationByIdempotency = `-- name: GetOperationByIdempotency :one
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at FROM operations WHERE idempotency_key = $1
`

func (q *Queries) GetOperationByIdempotency(ctx context.Context, idempotencyKey string) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByIdempotency, idempotencyKey)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const getOperationForUser = `-- name: GetOperationForUser :one
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at FROM operations WHERE id = $1 AND user_id = $2
`

type GetOperationForUserParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOperationForUser(ctx context.Context, arg GetOperationForUserParams) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationForUser, arg.ID, arg.UserID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const listOperationSteps = `-- name: ListOperationSteps :many
SELECT id, operation_id, step_key, step_order, status, progress, attempt, error_code, error_message, started_at, finished_at, created_at, updated_at, output FROM operation_steps WHERE operation_id = $1 ORDER BY step_order, id
`

func (q *Queries) ListOperationSteps(ctx context.Context, operationID uuid.UUID) ([]OperationStep, error) {
	rows, err := q.db.Query(ctx, listOperationSteps, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationStep{}
	for rows.Next() {
		var i OperationStep
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.StepKey,
			&i.StepOrder,
			&i.Status,
			&i.Progress,
			&i.Attempt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Output,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueOperation = `-- name: RequeueOperation :one
UPDATE operations
SET status = 'queued', phase = 'queued', progress = 0, message_key = 'operation.queued',
    retryable = false, heartbeat_at = NULL, updated_at = now()
WHERE id = $1 AND status = 'retrying'
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at
`

func (q *Queries) RequeueOperation(ctx context.Context, id uuid.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, requeueOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const scheduleOperationRetry = `-- name: ScheduleOperationRetry :one
UPDATE operations
SET status = 'retrying', phase = 'retrying', retryable = true,
    retry_count = retry_count + 1, error_code = $2, error_message = $3,
    message_key = $4, next_attempt_at = $5, heartbeat_at = now(), updated_at = now()
WHERE id = $1 AND status NOT IN ('succeeded', 'failed', 'cancelled')
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at
`

type ScheduleOperationRetryParams struct {
	ID            uuid.UUID          `json:"id"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	MessageKey    pgtype.Text        `json:"message_key"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) ScheduleOperationRetry(ctx context.Context, arg ScheduleOperationRetryParams) (Operation, error) {
	row := q.db.QueryRow(ctx, scheduleOperationRetry,
		arg.ID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.MessageKey,
		arg.NextAttemptAt,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const updateOperationProgress = `-- name: UpdateOperationProgress :one
UPDATE operations
SET status = $2, phase = $3, progress = $4, message_key = $5, heartbeat_at = now(), updated_at = now()
WHERE id = $1 AND status NOT IN ('succeeded', 'failed', 'cancelled')
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at, user_id, actor_admin_id, next_attempt_at, heartbeat_at
`

type UpdateOperationProgressParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	Phase      pgtype.Text `json:"phase"`
	Progress   int32       `json:"progress"`
	MessageKey pgtype.Text `json:"message_key"`
}

func (q *Queries) UpdateOperationProgress(ctx context.Context, arg UpdateOperationProgressParams) (Operation, error) {
	row := q.db.QueryRow(ctx, updateOperationProgress,
		arg.ID,
		arg.Status,
		arg.Phase,
		arg.Progress,
		arg.MessageKey,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ActorAdminID,
		&i.NextAttemptAt,
		&i.HeartbeatAt,
	)
	return i, err
}

const updateOperationStep = `-- name: UpdateOperationStep :one
UPDATE operation_steps
SET status = $2, progress = $3, attempt = $4, error_code = $5, error_message = $6,
    output = $7, started_at = COALESCE(started_at, CASE WHEN $2 = 'running' THEN now() END),
    finished_at = CASE WHEN $2 IN ('succeeded', 'failed', 'skipped') THEN now() ELSE finished_at END,
    updated_at = now()
WHERE operation_id = $1 AND step_key = $8
RETURNING id, operation_id, step_key, step_order, status, progress, attempt, error_code, error_message, started_at, finished_at, created_at, updated_at, output
`

type UpdateOperationStepParams struct {
	OperationID  uuid.UUID   `json:"operation_id"`
	Status       string      `json:"status"`
	Progress     int32       `json:"progress"`
	Attempt      int32       `json:"attempt"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	Output       []byte      `json:"output"`
	StepKey      string      `json:"step_key"`
}

func (q *Queries) UpdateOperationStep(ctx context.Context, arg UpdateOperationStepParams) (OperationStep, error) {
	row := q.db.QueryRow(ctx, updateOperationStep,
		arg.OperationID,
		arg.Status,
		arg.Progress,
		arg.Attempt,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Output,
		arg.StepKey,
	)
	var i OperationStep
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.StepKey,
		&i.StepOrder,
		&i.Status,
		&i.Progress,
		&i.Attempt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Output,
	)
	return i, err
}
