// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: portal.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserTicket = `-- name: CreateUserTicket :one
INSERT INTO tickets (id, ticket_no, user_id, subject, status, priority)
VALUES ($1, $2, $3, $4, 'open', $5)
RETURNING id, ticket_no, user_id, subject, status, priority, created_at, updated_at, closed_at
`

type CreateUserTicketParams struct {
	ID       uuid.UUID `json:"id"`
	TicketNo string    `json:"ticket_no"`
	UserID   uuid.UUID `json:"user_id"`
	Subject  string    `json:"subject"`
	Priority string    `json:"priority"`
}

func (q *Queries) CreateUserTicket(ctx context.Context, arg CreateUserTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createUserTicket,
		arg.ID,
		arg.TicketNo,
		arg.UserID,
		arg.Subject,
		arg.Priority,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketNo,
		&i.UserID,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createUserTicketMessage = `-- name: CreateUserTicketMessage :one
INSERT INTO ticket_messages (id, ticket_id, sender_type, sender_id, message)
VALUES ($1, $2, 'user', $3, $4)
RETURNING id, ticket_id, sender_type, sender_id, message, created_at
`

type CreateUserTicketMessageParams struct {
	ID       uuid.UUID  `json:"id"`
	TicketID uuid.UUID  `json:"ticket_id"`
	SenderID *uuid.UUID `json:"sender_id"`
	Message  string     `json:"message"`
}

func (q *Queries) CreateUserTicketMessage(ctx context.Context, arg CreateUserTicketMessageParams) (TicketMessage, error) {
	row := q.db.QueryRow(ctx, createUserTicketMessage,
		arg.ID,
		arg.TicketID,
		arg.SenderID,
		arg.Message,
	)
	var i TicketMessage
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.SenderType,
		&i.SenderID,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const getInstanceActionContextByOperation = `-- name: GetInstanceActionContextByOperation :one
SELECT i.id, i.provider_id, i.provider_instance_id, i.node_id, i.image_id,
       i.desired_state, i.observed_state, COALESCE(n.provider_node_id, n.id::text) AS provider_node_id,
       o.type AS operation_type
FROM operations o
JOIN instances i ON i.id = o.resource_id AND o.resource_type = 'instance'
JOIN nodes n ON n.id = i.node_id
WHERE o.id = $1
`

type GetInstanceActionContextByOperationRow struct {
	ID                 uuid.UUID   `json:"id"`
	ProviderID         *uuid.UUID  `json:"provider_id"`
	ProviderInstanceID pgtype.Text `json:"provider_instance_id"`
	NodeID             *uuid.UUID  `json:"node_id"`
	ImageID            pgtype.Text `json:"image_id"`
	DesiredState       string      `json:"desired_state"`
	ObservedState      string      `json:"observed_state"`
	ProviderNodeID     pgtype.Text `json:"provider_node_id"`
	OperationType      string      `json:"operation_type"`
}

func (q *Queries) GetInstanceActionContextByOperation(ctx context.Context, id uuid.UUID) (GetInstanceActionContextByOperationRow, error) {
	row := q.db.QueryRow(ctx, getInstanceActionContextByOperation, id)
	var i GetInstanceActionContextByOperationRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.NodeID,
		&i.ImageID,
		&i.DesiredState,
		&i.ObservedState,
		&i.ProviderNodeID,
		&i.OperationType,
	)
	return i, err
}

const getUserInstance = `-- name: GetUserInstance :one
SELECT i.id, i.name, i.desired_state, i.observed_state, i.cpu_cores, i.memory_mb,
       i.disk_gb, i.traffic_limit_gb, i.bandwidth_mbps, i.image_id,
       COALESCE(host(i.primary_ipv4), '')::text AS primary_ipv4,
       COALESCE(host(i.primary_ipv6), '')::text AS primary_ipv6,
       i.last_synced_at, i.created_at, i.updated_at,
       s.id AS subscription_id, s.status AS subscription_status, s.current_period_end,
       p.slug AS plan_slug, p.name_i18n AS plan_name_i18n
FROM instances i
JOIN subscriptions s ON s.id = i.subscription_id
JOIN plans p ON p.id = s.plan_id
WHERE i.id = $1 AND s.user_id = $2 AND i.deleted_at IS NULL
`

type GetUserInstanceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetUserInstanceRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	DesiredState       string             `json:"desired_state"`
	ObservedState      string             `json:"observed_state"`
	CpuCores           float64            `json:"cpu_cores"`
	MemoryMb           int32              `json:"memory_mb"`
	DiskGb             int32              `json:"disk_gb"`
	TrafficLimitGb     pgtype.Int8        `json:"traffic_limit_gb"`
	BandwidthMbps      pgtype.Int4        `json:"bandwidth_mbps"`
	ImageID            pgtype.Text        `json:"image_id"`
	PrimaryIpv4        string             `json:"primary_ipv4"`
	PrimaryIpv6        string             `json:"primary_ipv6"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SubscriptionID     uuid.UUID          `json:"subscription_id"`
	SubscriptionStatus string             `json:"subscription_status"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	PlanSlug           string             `json:"plan_slug"`
	PlanNameI18n       []byte             `json:"plan_name_i18n"`
}

func (q *Queries) GetUserInstance(ctx context.Context, arg GetUserInstanceParams) (GetUserInstanceRow, error) {
	row := q.db.QueryRow(ctx, getUserInstance, arg.ID, arg.UserID)
	var i GetUserInstanceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DesiredState,
		&i.ObservedState,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficLimitGb,
		&i.BandwidthMbps,
		&i.ImageID,
		&i.PrimaryIpv4,
		&i.PrimaryIpv6,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.PlanSlug,
		&i.PlanNameI18n,
	)
	return i, err
}

const getUserInstanceActionContext = `-- name: GetUserInstanceActionContext :one
SELECT i.id, i.provider_id, i.provider_instance_id, i.node_id, i.image_id,
       i.desired_state, i.observed_state, COALESCE(n.provider_node_id, n.id::text) AS provider_node_id
FROM instances i
JOIN subscriptions s ON s.id = i.subscription_id
JOIN nodes n ON n.id = i.node_id
WHERE i.id = $1 AND s.user_id = $2 AND i.deleted_at IS NULL
`

type GetUserInstanceActionContextParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetUserInstanceActionContextRow struct {
	ID                 uuid.UUID   `json:"id"`
	ProviderID         *uuid.UUID  `json:"provider_id"`
	ProviderInstanceID pgtype.Text `json:"provider_instance_id"`
	NodeID             *uuid.UUID  `json:"node_id"`
	ImageID            pgtype.Text `json:"image_id"`
	DesiredState       string      `json:"desired_state"`
	ObservedState      string      `json:"observed_state"`
	ProviderNodeID     pgtype.Text `json:"provider_node_id"`
}

func (q *Queries) GetUserInstanceActionContext(ctx context.Context, arg GetUserInstanceActionContextParams) (GetUserInstanceActionContextRow, error) {
	row := q.db.QueryRow(ctx, getUserInstanceActionContext, arg.ID, arg.UserID)
	var i GetUserInstanceActionContextRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.NodeID,
		&i.ImageID,
		&i.DesiredState,
		&i.ObservedState,
		&i.ProviderNodeID,
	)
	return i, err
}

const getUserTicket = `-- name: GetUserTicket :one
SELECT id, ticket_no, subject, status, priority, created_at, updated_at, closed_at
FROM tickets
WHERE id = $1 AND user_id = $2
`

type GetUserTicketParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetUserTicketRow struct {
	ID        uuid.UUID          `json:"id"`
	TicketNo  string             `json:"ticket_no"`
	Subject   string             `json:"subject"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ClosedAt  pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) GetUserTicket(ctx context.Context, arg GetUserTicketParams) (GetUserTicketRow, error) {
	row := q.db.QueryRow(ctx, getUserTicket, arg.ID, arg.UserID)
	var i GetUserTicketRow
	err := row.Scan(
		&i.ID,
		&i.TicketNo,
		&i.Subject,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listUserInstanceNetworks = `-- name: ListUserInstanceNetworks :many
SELECT n.id, n.type, COALESCE(host(n.address), '')::text AS address,
       COALESCE(host(n.gateway), '')::text AS gateway, n.prefix, n.created_at
FROM instance_networks n
JOIN instances i ON i.id = n.instance_id
JOIN subscriptions s ON s.id = i.subscription_id
WHERE n.instance_id = $1 AND s.user_id = $2
ORDER BY n.type, n.created_at
`

type ListUserInstanceNetworksParams struct {
	InstanceID uuid.UUID `json:"instance_id"`
	UserID     uuid.UUID `json:"user_id"`
}

type ListUserInstanceNetworksRow struct {
	ID        uuid.UUID          `json:"id"`
	Type      string             `json:"type"`
	Address   string             `json:"address"`
	Gateway   string             `json:"gateway"`
	Prefix    pgtype.Int4        `json:"prefix"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUserInstanceNetworks(ctx context.Context, arg ListUserInstanceNetworksParams) ([]ListUserInstanceNetworksRow, error) {
	rows, err := q.db.Query(ctx, listUserInstanceNetworks, arg.InstanceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserInstanceNetworksRow{}
	for rows.Next() {
		var i ListUserInstanceNetworksRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Address,
			&i.Gateway,
			&i.Prefix,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInstanceTraffic = `-- name: ListUserInstanceTraffic :many
SELECT t.period_start, t.period_end, t.rx_bytes, t.tx_bytes, t.source
FROM traffic_usage t
JOIN instances i ON i.id = t.instance_id
JOIN subscriptions s ON s.id = i.subscription_id
WHERE t.instance_id = $1 AND s.user_id = $2
ORDER BY t.period_start DESC
LIMIT 90
`

type ListUserInstanceTrafficParams struct {
	InstanceID uuid.UUID `json:"instance_id"`
	UserID     uuid.UUID `json:"user_id"`
}

type ListUserInstanceTrafficRow struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	RxBytes     int64              `json:"rx_bytes"`
	TxBytes     int64              `json:"tx_bytes"`
	Source      string             `json:"source"`
}

func (q *Queries) ListUserInstanceTraffic(ctx context.Context, arg ListUserInstanceTrafficParams) ([]ListUserInstanceTrafficRow, error) {
	rows, err := q.db.Query(ctx, listUserInstanceTraffic, arg.InstanceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserInstanceTrafficRow{}
	for rows.Next() {
		var i ListUserInstanceTrafficRow
		if err := rows.Scan(
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RxBytes,
			&i.TxBytes,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInstances = `-- name: ListUserInstances :many
SELECT i.id, i.name, i.desired_state, i.observed_state, i.cpu_cores, i.memory_mb,
       i.disk_gb, i.traffic_limit_gb, i.bandwidth_mbps, i.image_id,
       COALESCE(host(i.primary_ipv4), '')::text AS primary_ipv4,
       COALESCE(host(i.primary_ipv6), '')::text AS primary_ipv6,
       i.last_synced_at, i.created_at, i.updated_at,
       s.id AS subscription_id, s.status AS subscription_status, s.current_period_end,
       p.slug AS plan_slug, p.name_i18n AS plan_name_i18n
FROM instances i
JOIN subscriptions s ON s.id = i.subscription_id
JOIN plans p ON p.id = s.plan_id
WHERE s.user_id = $1 AND i.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type ListUserInstancesRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	DesiredState       string             `json:"desired_state"`
	ObservedState      string             `json:"observed_state"`
	CpuCores           float64            `json:"cpu_cores"`
	MemoryMb           int32              `json:"memory_mb"`
	DiskGb             int32              `json:"disk_gb"`
	TrafficLimitGb     pgtype.Int8        `json:"traffic_limit_gb"`
	BandwidthMbps      pgtype.Int4        `json:"bandwidth_mbps"`
	ImageID            pgtype.Text        `json:"image_id"`
	PrimaryIpv4        string             `json:"primary_ipv4"`
	PrimaryIpv6        string             `json:"primary_ipv6"`
	LastSyncedAt       pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	SubscriptionID     uuid.UUID          `json:"subscription_id"`
	SubscriptionStatus string             `json:"subscription_status"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	PlanSlug           string             `json:"plan_slug"`
	PlanNameI18n       []byte             `json:"plan_name_i18n"`
}

func (q *Queries) ListUserInstances(ctx context.Context, userID uuid.UUID) ([]ListUserInstancesRow, error) {
	rows, err := q.db.Query(ctx, listUserInstances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserInstancesRow{}
	for rows.Next() {
		var i ListUserInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DesiredState,
			&i.ObservedState,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficLimitGb,
			&i.BandwidthMbps,
			&i.ImageID,
			&i.PrimaryIpv4,
			&i.PrimaryIpv6,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubscriptionID,
			&i.SubscriptionStatus,
			&i.CurrentPeriodEnd,
			&i.PlanSlug,
			&i.PlanNameI18n,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, type, title_key, message_key, parameters, severity, read_at, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 100
`

type ListUserNotificationsRow struct {
	ID         uuid.UUID          `json:"id"`
	Type       string             `json:"type"`
	TitleKey   string             `json:"title_key"`
	MessageKey string             `json:"message_key"`
	Parameters []byte             `json:"parameters"`
	Severity   string             `json:"severity"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUserNotifications(ctx context.Context, userID *uuid.UUID) ([]ListUserNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listUserNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserNotificationsRow{}
	for rows.Next() {
		var i ListUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TitleKey,
			&i.MessageKey,
			&i.Parameters,
			&i.Severity,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTicketMessages = `-- name: ListUserTicketMessages :many
SELECT m.id, m.sender_type, m.message, m.created_at
FROM ticket_messages m
JOIN tickets t ON t.id = m.ticket_id
WHERE m.ticket_id = $1 AND t.user_id = $2
ORDER BY m.created_at, m.id
`

type ListUserTicketMessagesParams struct {
	TicketID uuid.UUID `json:"ticket_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type ListUserTicketMessagesRow struct {
	ID         uuid.UUID          `json:"id"`
	SenderType string             `json:"sender_type"`
	Message    string             `json:"message"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUserTicketMessages(ctx context.Context, arg ListUserTicketMessagesParams) ([]ListUserTicketMessagesRow, error) {
	rows, err := q.db.Query(ctx, listUserTicketMessages, arg.TicketID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTicketMessagesRow{}
	for rows.Next() {
		var i ListUserTicketMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderType,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTickets = `-- name: ListUserTickets :many
SELECT id, ticket_no, subject, status, priority, created_at, updated_at, closed_at
FROM tickets
WHERE user_id = $1
ORDER BY updated_at DESC
`

type ListUserTicketsRow struct {
	ID        uuid.UUID          `json:"id"`
	TicketNo  string             `json:"ticket_no"`
	Subject   string             `json:"subject"`
	Status    string             `json:"status"`
	Priority  string             `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ClosedAt  pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) ListUserTickets(ctx context.Context, userID uuid.UUID) ([]ListUserTicketsRow, error) {
	rows, err := q.db.Query(ctx, listUserTickets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTicketsRow{}
	for rows.Next() {
		var i ListUserTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketNo,
			&i.Subject,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserNotificationRead = `-- name: MarkUserNotificationRead :execrows
UPDATE notifications SET read_at = COALESCE(read_at, now())
WHERE id = $1 AND user_id = $2
`

type MarkUserNotificationReadParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkUserNotificationRead(ctx context.Context, arg MarkUserNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUserNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInstanceActionState = `-- name: SetInstanceActionState :exec
UPDATE instances
SET desired_state = $2, observed_state = $3, version = version + 1, updated_at = now()
WHERE id = $1
`

type SetInstanceActionStateParams struct {
	ID            uuid.UUID `json:"id"`
	DesiredState  string    `json:"desired_state"`
	ObservedState string    `json:"observed_state"`
}

func (q *Queries) SetInstanceActionState(ctx context.Context, arg SetInstanceActionStateParams) error {
	_, err := q.db.Exec(ctx, setInstanceActionState, arg.ID, arg.DesiredState, arg.ObservedState)
	return err
}

const setInstanceObservedState = `-- name: SetInstanceObservedState :exec
UPDATE instances
SET observed_state = $2, last_synced_at = now(), version = version + 1, updated_at = now()
WHERE id = $1
`

type SetInstanceObservedStateParams struct {
	ID            uuid.UUID `json:"id"`
	ObservedState string    `json:"observed_state"`
}

func (q *Queries) SetInstanceObservedState(ctx context.Context, arg SetInstanceObservedStateParams) error {
	_, err := q.db.Exec(ctx, setInstanceObservedState, arg.ID, arg.ObservedState)
	return err
}

const touchUserTicket = `-- name: TouchUserTicket :exec
UPDATE tickets SET updated_at = now()
WHERE id = $1 AND user_id = $2 AND status <> 'closed'
`

type TouchUserTicketParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) TouchUserTicket(ctx context.Context, arg TouchUserTicketParams) error {
	_, err := q.db.Exec(ctx, touchUserTicket, arg.ID, arg.UserID)
	return err
}
