// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provision.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateProvisionedSubscription = `-- name: ActivateProvisionedSubscription :one
UPDATE subscriptions
SET status = 'active', started_at = COALESCE(started_at, $2),
    current_period_start = COALESCE(current_period_start, $2),
    current_period_end = COALESCE(current_period_end, $2 + CASE billing_cycle
      WHEN 'monthly' THEN interval '1 month'
      WHEN 'quarterly' THEN interval '3 months'
      WHEN 'yearly' THEN interval '1 year'
    END),
    next_due_at = COALESCE(next_due_at, $2 + CASE billing_cycle
      WHEN 'monthly' THEN interval '1 month'
      WHEN 'quarterly' THEN interval '3 months'
      WHEN 'yearly' THEN interval '1 year'
    END),
    version = version + CASE WHEN status = 'pending' THEN 1 ELSE 0 END,
    updated_at = now()
WHERE id = $1 AND status IN ('pending', 'active')
RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at, source_order_id, source_item_index
`

type ActivateProvisionedSubscriptionParams struct {
	ID        uuid.UUID          `json:"id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) ActivateProvisionedSubscription(ctx context.Context, arg ActivateProvisionedSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, activateProvisionedSubscription, arg.ID, arg.StartedAt)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceOrderID,
		&i.SourceItemIndex,
	)
	return i, err
}

const createPendingInstance = `-- name: CreatePendingInstance :one
INSERT INTO instances (
  id, subscription_id, name, desired_state, observed_state, cpu_cores, memory_mb,
  disk_gb, traffic_limit_gb, bandwidth_mbps, image_id
)
VALUES ($1, $2, $3, 'running', 'pending', $4, $5, $6, $7, $8, $9)
ON CONFLICT (subscription_id) DO UPDATE SET subscription_id = EXCLUDED.subscription_id
RETURNING id, subscription_id, node_id, provider_id, provider_instance_id, name, desired_state, observed_state, cpu_cores, memory_mb, disk_gb, traffic_limit_gb, bandwidth_mbps, image_id, primary_ipv4, primary_ipv6, last_synced_at, version, created_at, updated_at, deleted_at
`

type CreatePendingInstanceParams struct {
	ID             uuid.UUID   `json:"id"`
	SubscriptionID uuid.UUID   `json:"subscription_id"`
	Name           string      `json:"name"`
	CpuCores       float64     `json:"cpu_cores"`
	MemoryMb       int32       `json:"memory_mb"`
	DiskGb         int32       `json:"disk_gb"`
	TrafficLimitGb pgtype.Int8 `json:"traffic_limit_gb"`
	BandwidthMbps  pgtype.Int4 `json:"bandwidth_mbps"`
	ImageID        pgtype.Text `json:"image_id"`
}

func (q *Queries) CreatePendingInstance(ctx context.Context, arg CreatePendingInstanceParams) (Instance, error) {
	row := q.db.QueryRow(ctx, createPendingInstance,
		arg.ID,
		arg.SubscriptionID,
		arg.Name,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.TrafficLimitGb,
		arg.BandwidthMbps,
		arg.ImageID,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.NodeID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.Name,
		&i.DesiredState,
		&i.ObservedState,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficLimitGb,
		&i.BandwidthMbps,
		&i.ImageID,
		&i.PrimaryIpv4,
		&i.PrimaryIpv6,
		&i.LastSyncedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProvisionNotification = `-- name: CreateProvisionNotification :exec
INSERT INTO notifications (id, user_id, type, title_key, message_key, parameters, severity)
VALUES ($1, $2, 'instance_ready', 'notifications.instanceReady.title', 'notifications.instanceReady.message', $3, 'success')
ON CONFLICT (id) DO NOTHING
`

type CreateProvisionNotificationParams struct {
	ID         uuid.UUID  `json:"id"`
	UserID     *uuid.UUID `json:"user_id"`
	Parameters []byte     `json:"parameters"`
}

func (q *Queries) CreateProvisionNotification(ctx context.Context, arg CreateProvisionNotificationParams) error {
	_, err := q.db.Exec(ctx, createProvisionNotification, arg.ID, arg.UserID, arg.Parameters)
	return err
}

const createPurchaseSubscription = `-- name: CreatePurchaseSubscription :one
INSERT INTO subscriptions (
  id, user_id, plan_id, status, billing_cycle, price_minor, currency,
  source_order_id, source_item_index
)
VALUES ($1, $2, $3, 'pending', $4, $5, $6, $7, $8)
ON CONFLICT (source_order_id, source_item_index) WHERE source_order_id IS NOT NULL
DO UPDATE SET source_order_id = EXCLUDED.source_order_id
RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at, source_order_id, source_item_index
`

type CreatePurchaseSubscriptionParams struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	PlanID          uuid.UUID   `json:"plan_id"`
	BillingCycle    string      `json:"billing_cycle"`
	PriceMinor      int64       `json:"price_minor"`
	Currency        string      `json:"currency"`
	SourceOrderID   *uuid.UUID  `json:"source_order_id"`
	SourceItemIndex pgtype.Int4 `json:"source_item_index"`
}

func (q *Queries) CreatePurchaseSubscription(ctx context.Context, arg CreatePurchaseSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createPurchaseSubscription,
		arg.ID,
		arg.UserID,
		arg.PlanID,
		arg.BillingCycle,
		arg.PriceMinor,
		arg.Currency,
		arg.SourceOrderID,
		arg.SourceItemIndex,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceOrderID,
		&i.SourceItemIndex,
	)
	return i, err
}

const getPaidPurchaseForProvision = `-- name: GetPaidPurchaseForProvision :one
SELECT orders.id AS order_id, orders.user_id, orders.status AS order_status,
       order_items.quantity, plans.id, plans.product_id, plans.node_group_id, plans.slug, plans.name_i18n, plans.status, plans.cpu_cores, plans.memory_mb, plans.disk_gb, plans.traffic_gb, plans.bandwidth_mbps, plans.ipv4_count, plans.ipv6_count, plans.nat_port_count, plans.virtualization, plans.billing_cycle, plans.price_minor, plans.currency, plans.stock_mode, plans.created_at, plans.updated_at, plans.default_image_id, plans.stock_quantity, plans.setup_fee_minor, plans.traffic_overage_price_minor, plans.metadata
FROM orders
JOIN order_items ON order_items.order_id = orders.id
JOIN plans ON plans.id = order_items.plan_id
WHERE orders.id = $1 AND orders.kind = 'purchase' AND orders.status IN ('paid', 'fulfilling', 'fulfilled')
FOR UPDATE OF orders
`

type GetPaidPurchaseForProvisionRow struct {
	OrderID                  uuid.UUID          `json:"order_id"`
	UserID                   uuid.UUID          `json:"user_id"`
	OrderStatus              string             `json:"order_status"`
	Quantity                 int32              `json:"quantity"`
	ID                       uuid.UUID          `json:"id"`
	ProductID                uuid.UUID          `json:"product_id"`
	NodeGroupID              *uuid.UUID         `json:"node_group_id"`
	Slug                     string             `json:"slug"`
	NameI18n                 []byte             `json:"name_i18n"`
	Status                   string             `json:"status"`
	CpuCores                 float64            `json:"cpu_cores"`
	MemoryMb                 int32              `json:"memory_mb"`
	DiskGb                   int32              `json:"disk_gb"`
	TrafficGb                pgtype.Int8        `json:"traffic_gb"`
	BandwidthMbps            pgtype.Int4        `json:"bandwidth_mbps"`
	Ipv4Count                int32              `json:"ipv4_count"`
	Ipv6Count                int32              `json:"ipv6_count"`
	NatPortCount             int32              `json:"nat_port_count"`
	Virtualization           string             `json:"virtualization"`
	BillingCycle             string             `json:"billing_cycle"`
	PriceMinor               int64              `json:"price_minor"`
	Currency                 string             `json:"currency"`
	StockMode                string             `json:"stock_mode"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	DefaultImageID           string             `json:"default_image_id"`
	StockQuantity            pgtype.Int4        `json:"stock_quantity"`
	SetupFeeMinor            int64              `json:"setup_fee_minor"`
	TrafficOveragePriceMinor int64              `json:"traffic_overage_price_minor"`
	Metadata                 []byte             `json:"metadata"`
}

func (q *Queries) GetPaidPurchaseForProvision(ctx context.Context, id uuid.UUID) (GetPaidPurchaseForProvisionRow, error) {
	row := q.db.QueryRow(ctx, getPaidPurchaseForProvision, id)
	var i GetPaidPurchaseForProvisionRow
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.OrderStatus,
		&i.Quantity,
		&i.ID,
		&i.ProductID,
		&i.NodeGroupID,
		&i.Slug,
		&i.NameI18n,
		&i.Status,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficGb,
		&i.BandwidthMbps,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Virtualization,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StockMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultImageID,
		&i.StockQuantity,
		&i.SetupFeeMinor,
		&i.TrafficOveragePriceMinor,
		&i.Metadata,
	)
	return i, err
}

const getProvisionContext = `-- name: GetProvisionContext :one
SELECT operations.id AS operation_id, operations.retry_count,
       instances.id AS instance_id, instances.name AS instance_name,
       instances.provider_instance_id, instances.observed_state,
       subscriptions.id AS subscription_id, subscriptions.user_id,
       subscriptions.source_order_id, subscriptions.status AS subscription_status,
       plans.node_group_id, plans.cpu_cores, plans.memory_mb, plans.disk_gb,
       plans.traffic_gb, plans.bandwidth_mbps, plans.ipv4_count, plans.ipv6_count,
       plans.nat_port_count, plans.virtualization, plans.default_image_id
FROM operations
JOIN instances ON instances.id = operations.resource_id AND operations.resource_type = 'instance'
JOIN subscriptions ON subscriptions.id = instances.subscription_id
JOIN plans ON plans.id = subscriptions.plan_id
WHERE operations.id = $1
`

type GetProvisionContextRow struct {
	OperationID        uuid.UUID   `json:"operation_id"`
	RetryCount         int32       `json:"retry_count"`
	InstanceID         uuid.UUID   `json:"instance_id"`
	InstanceName       string      `json:"instance_name"`
	ProviderInstanceID pgtype.Text `json:"provider_instance_id"`
	ObservedState      string      `json:"observed_state"`
	SubscriptionID     uuid.UUID   `json:"subscription_id"`
	UserID             uuid.UUID   `json:"user_id"`
	SourceOrderID      *uuid.UUID  `json:"source_order_id"`
	SubscriptionStatus string      `json:"subscription_status"`
	NodeGroupID        *uuid.UUID  `json:"node_group_id"`
	CpuCores           float64     `json:"cpu_cores"`
	MemoryMb           int32       `json:"memory_mb"`
	DiskGb             int32       `json:"disk_gb"`
	TrafficGb          pgtype.Int8 `json:"traffic_gb"`
	BandwidthMbps      pgtype.Int4 `json:"bandwidth_mbps"`
	Ipv4Count          int32       `json:"ipv4_count"`
	Ipv6Count          int32       `json:"ipv6_count"`
	NatPortCount       int32       `json:"nat_port_count"`
	Virtualization     string      `json:"virtualization"`
	DefaultImageID     string      `json:"default_image_id"`
}

func (q *Queries) GetProvisionContext(ctx context.Context, id uuid.UUID) (GetProvisionContextRow, error) {
	row := q.db.QueryRow(ctx, getProvisionContext, id)
	var i GetProvisionContextRow
	err := row.Scan(
		&i.OperationID,
		&i.RetryCount,
		&i.InstanceID,
		&i.InstanceName,
		&i.ProviderInstanceID,
		&i.ObservedState,
		&i.SubscriptionID,
		&i.UserID,
		&i.SourceOrderID,
		&i.SubscriptionStatus,
		&i.NodeGroupID,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficGb,
		&i.BandwidthMbps,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Virtualization,
		&i.DefaultImageID,
	)
	return i, err
}

const getProvisionPlacement = `-- name: GetProvisionPlacement :one
SELECT resource_reservations.id AS reservation_id, nodes.id AS node_id,
       nodes.provider_id, COALESCE(nodes.provider_node_id, nodes.id::text) AS provider_node_id
FROM resource_reservations
JOIN nodes ON nodes.id = resource_reservations.node_id
WHERE resource_reservations.operation_id = $1
`

type GetProvisionPlacementRow struct {
	ReservationID  uuid.UUID   `json:"reservation_id"`
	NodeID         uuid.UUID   `json:"node_id"`
	ProviderID     uuid.UUID   `json:"provider_id"`
	ProviderNodeID pgtype.Text `json:"provider_node_id"`
}

func (q *Queries) GetProvisionPlacement(ctx context.Context, operationID uuid.UUID) (GetProvisionPlacementRow, error) {
	row := q.db.QueryRow(ctx, getProvisionPlacement, operationID)
	var i GetProvisionPlacementRow
	err := row.Scan(
		&i.ReservationID,
		&i.NodeID,
		&i.ProviderID,
		&i.ProviderNodeID,
	)
	return i, err
}

const markOrderFulfilling = `-- name: MarkOrderFulfilling :exec
UPDATE orders SET status = 'fulfilling', updated_at = now()
WHERE id = $1 AND status = 'paid'
`

func (q *Queries) MarkOrderFulfilling(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOrderFulfilling, id)
	return err
}

const markPurchaseOrderFulfilledIfReady = `-- name: MarkPurchaseOrderFulfilledIfReady :exec
UPDATE orders SET status = 'fulfilled', updated_at = now()
WHERE orders.id = $1 AND orders.status IN ('paid', 'fulfilling', 'fulfilled')
  AND NOT EXISTS (
    SELECT 1 FROM subscriptions
    WHERE source_order_id = $1 AND status <> 'active'
  )
`

func (q *Queries) MarkPurchaseOrderFulfilledIfReady(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPurchaseOrderFulfilledIfReady, id)
	return err
}

const setInstancePlacement = `-- name: SetInstancePlacement :exec
UPDATE instances
SET node_id = $2, provider_id = $3, observed_state = 'provisioning', version = version + 1, updated_at = now()
WHERE id = $1 AND observed_state IN ('pending', 'provisioning', 'unknown', 'error')
`

type SetInstancePlacementParams struct {
	ID         uuid.UUID  `json:"id"`
	NodeID     *uuid.UUID `json:"node_id"`
	ProviderID *uuid.UUID `json:"provider_id"`
}

func (q *Queries) SetInstancePlacement(ctx context.Context, arg SetInstancePlacementParams) error {
	_, err := q.db.Exec(ctx, setInstancePlacement, arg.ID, arg.NodeID, arg.ProviderID)
	return err
}

const setInstanceProviderResult = `-- name: SetInstanceProviderResult :exec
UPDATE instances
SET provider_instance_id = $2, observed_state = $3, primary_ipv4 = $4, primary_ipv6 = $5,
    last_synced_at = now(), version = version + 1, updated_at = now()
WHERE id = $1
`

type SetInstanceProviderResultParams struct {
	ID                 uuid.UUID   `json:"id"`
	ProviderInstanceID pgtype.Text `json:"provider_instance_id"`
	ObservedState      string      `json:"observed_state"`
	PrimaryIpv4        *netip.Addr `json:"primary_ipv4"`
	PrimaryIpv6        *netip.Addr `json:"primary_ipv6"`
}

func (q *Queries) SetInstanceProviderResult(ctx context.Context, arg SetInstanceProviderResultParams) error {
	_, err := q.db.Exec(ctx, setInstanceProviderResult,
		arg.ID,
		arg.ProviderInstanceID,
		arg.ObservedState,
		arg.PrimaryIpv4,
		arg.PrimaryIpv6,
	)
	return err
}

const setInstanceProvisionError = `-- name: SetInstanceProvisionError :exec
UPDATE instances
SET observed_state = 'error', version = version + 1, updated_at = now()
WHERE id = $1 AND observed_state <> 'running'
`

func (q *Queries) SetInstanceProvisionError(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setInstanceProvisionError, id)
	return err
}
