// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateProvisionedSubscription(ctx context.Context, arg ActivateProvisionedSubscriptionParams) (Subscription, error)
	AddNodeReservation(ctx context.Context, arg AddNodeReservationParams) (Node, error)
	AssignAdminRole(ctx context.Context, arg AssignAdminRoleParams) error
	ClaimDueOperationRetries(ctx context.Context, limit int32) ([]Operation, error)
	ClaimOperation(ctx context.Context, id uuid.UUID) (Operation, error)
	ClaimOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	ClaimSubscriptionsForLifecycle(ctx context.Context, arg ClaimSubscriptionsForLifecycleParams) ([]Subscription, error)
	CommitNodeReservation(ctx context.Context, arg CommitNodeReservationParams) (Node, error)
	CompleteOperation(ctx context.Context, arg CompleteOperationParams) (Operation, error)
	CountLedgerTransactionsByReference(ctx context.Context, arg CountLedgerTransactionsByReferenceParams) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateAdminSession(ctx context.Context, arg CreateAdminSessionParams) (AdminSession, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateInfrastructureProvider(ctx context.Context, arg CreateInfrastructureProviderParams) (Provider, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) error
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error
	CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) error
	CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error)
	CreateNodeGroup(ctx context.Context, arg CreateNodeGroupParams) (NodeGroup, error)
	CreateOperation(ctx context.Context, arg CreateOperationParams) (Operation, error)
	CreateOperationStep(ctx context.Context, arg CreateOperationStepParams) (OperationStep, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePendingInstance(ctx context.Context, arg CreatePendingInstanceParams) (Instance, error)
	CreateProvisionNotification(ctx context.Context, arg CreateProvisionNotificationParams) error
	CreatePurchaseSubscription(ctx context.Context, arg CreatePurchaseSubscriptionParams) (Subscription, error)
	CreateResourceReservation(ctx context.Context, arg CreateResourceReservationParams) (ResourceReservation, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	CreateUserTicket(ctx context.Context, arg CreateUserTicketParams) (Ticket, error)
	CreateUserTicketMessage(ctx context.Context, arg CreateUserTicketMessageParams) (TicketMessage, error)
	DatabasePing(ctx context.Context) (int32, error)
	EnableAdminTOTP(ctx context.Context, adminID uuid.UUID) error
	EnsureWallet(ctx context.Context, arg EnsureWalletParams) (Wallet, error)
	GetActiveAdminSession(ctx context.Context, tokenHash []byte) (GetActiveAdminSessionRow, error)
	GetActiveUserSession(ctx context.Context, tokenHash []byte) (GetActiveUserSessionRow, error)
	GetAdminByEmail(ctx context.Context, email string) (Admin, error)
	GetAdminByID(ctx context.Context, id uuid.UUID) (Admin, error)
	GetAdminTOTPSecret(ctx context.Context, adminID uuid.UUID) (AdminTotpSecret, error)
	GetInfrastructureProviderByID(ctx context.Context, id uuid.UUID) (Provider, error)
	GetInstanceActionContextByOperation(ctx context.Context, id uuid.UUID) (GetInstanceActionContextByOperationRow, error)
	GetOperationByID(ctx context.Context, id uuid.UUID) (Operation, error)
	GetOperationByIdempotency(ctx context.Context, idempotencyKey string) (Operation, error)
	GetOperationForUser(ctx context.Context, arg GetOperationForUserParams) (Operation, error)
	GetOrderByUserIdempotency(ctx context.Context, arg GetOrderByUserIdempotencyParams) (Order, error)
	GetPaidPurchaseForProvision(ctx context.Context, id uuid.UUID) (GetPaidPurchaseForProvisionRow, error)
	GetPaymentByOrder(ctx context.Context, orderID uuid.UUID) (Payment, error)
	GetPlanForOrder(ctx context.Context, id uuid.UUID) (GetPlanForOrderRow, error)
	GetProvisionContext(ctx context.Context, id uuid.UUID) (GetProvisionContextRow, error)
	GetProvisionPlacement(ctx context.Context, operationID uuid.UUID) (GetProvisionPlacementRow, error)
	GetResourceReservationByOperation(ctx context.Context, operationID uuid.UUID) (ResourceReservation, error)
	GetSubscriptionForRenewal(ctx context.Context, arg GetSubscriptionForRenewalParams) (GetSubscriptionForRenewalRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserInstance(ctx context.Context, arg GetUserInstanceParams) (GetUserInstanceRow, error)
	GetUserInstanceActionContext(ctx context.Context, arg GetUserInstanceActionContextParams) (GetUserInstanceActionContextRow, error)
	GetUserTicket(ctx context.Context, arg GetUserTicketParams) (GetUserTicketRow, error)
	GetWalletByUserCurrency(ctx context.Context, arg GetWalletByUserCurrencyParams) (Wallet, error)
	GetWebhookReceipt(ctx context.Context, arg GetWebhookReceiptParams) (PaymentWebhookReceipt, error)
	InsertWebhookReceipt(ctx context.Context, arg InsertWebhookReceiptParams) (uuid.UUID, error)
	ListActiveProductsAndPlans(ctx context.Context) ([]ListActiveProductsAndPlansRow, error)
	ListAdminPermissions(ctx context.Context, adminID uuid.UUID) ([]string, error)
	ListInfrastructureProviders(ctx context.Context) ([]Provider, error)
	ListInvoicesByUser(ctx context.Context, userID uuid.UUID) ([]Invoice, error)
	ListNodeGroups(ctx context.Context) ([]NodeGroup, error)
	ListNodes(ctx context.Context) ([]Node, error)
	ListOperationSteps(ctx context.Context, operationID uuid.UUID) ([]OperationStep, error)
	ListOrdersByUser(ctx context.Context, userID uuid.UUID) ([]ListOrdersByUserRow, error)
	ListSubscriptionsByUser(ctx context.Context, userID uuid.UUID) ([]ListSubscriptionsByUserRow, error)
	ListUserInstanceNetworks(ctx context.Context, arg ListUserInstanceNetworksParams) ([]ListUserInstanceNetworksRow, error)
	ListUserInstanceTraffic(ctx context.Context, arg ListUserInstanceTrafficParams) ([]ListUserInstanceTrafficRow, error)
	ListUserInstances(ctx context.Context, userID uuid.UUID) ([]ListUserInstancesRow, error)
	ListUserNotifications(ctx context.Context, userID *uuid.UUID) ([]ListUserNotificationsRow, error)
	ListUserTicketMessages(ctx context.Context, arg ListUserTicketMessagesParams) ([]ListUserTicketMessagesRow, error)
	ListUserTickets(ctx context.Context, userID uuid.UUID) ([]ListUserTicketsRow, error)
	LockPaymentOrderInvoice(ctx context.Context, arg LockPaymentOrderInvoiceParams) (LockPaymentOrderInvoiceRow, error)
	LockResourceReservation(ctx context.Context, id uuid.UUID) (ResourceReservation, error)
	LockSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error)
	LockSubscriptionByUser(ctx context.Context, arg LockSubscriptionByUserParams) (Subscription, error)
	MarkInvoicePaid(ctx context.Context, id uuid.UUID) error
	MarkOrderFulfilling(ctx context.Context, id uuid.UUID) error
	MarkOrderPaid(ctx context.Context, id uuid.UUID) error
	MarkOutboxPublished(ctx context.Context, id uuid.UUID) error
	MarkOutboxRetry(ctx context.Context, arg MarkOutboxRetryParams) error
	MarkPaymentSucceeded(ctx context.Context, arg MarkPaymentSucceededParams) error
	MarkPurchaseOrderFulfilledIfReady(ctx context.Context, id uuid.UUID) error
	MarkUserNotificationRead(ctx context.Context, arg MarkUserNotificationReadParams) (int64, error)
	MarkWebhookProcessed(ctx context.Context, id uuid.UUID) error
	ReleaseNodeReservation(ctx context.Context, arg ReleaseNodeReservationParams) (Node, error)
	RenewSubscriptionAfterPayment(ctx context.Context, arg RenewSubscriptionAfterPaymentParams) (Subscription, error)
	RequeueOperation(ctx context.Context, id uuid.UUID) (Operation, error)
	RevokeAdminSession(ctx context.Context, tokenHash []byte) error
	RevokeUserSession(ctx context.Context, tokenHash []byte) error
	ScheduleOperationRetry(ctx context.Context, arg ScheduleOperationRetryParams) (Operation, error)
	SelectCandidateNodesForUpdate(ctx context.Context, arg SelectCandidateNodesForUpdateParams) ([]Node, error)
	SetInstanceActionState(ctx context.Context, arg SetInstanceActionStateParams) error
	SetInstanceObservedState(ctx context.Context, arg SetInstanceObservedStateParams) error
	SetInstancePlacement(ctx context.Context, arg SetInstancePlacementParams) error
	SetInstanceProviderResult(ctx context.Context, arg SetInstanceProviderResultParams) error
	SetInstanceProvisionError(ctx context.Context, id uuid.UUID) error
	SetResourceReservationStatus(ctx context.Context, arg SetResourceReservationStatusParams) (ResourceReservation, error)
	SetSubscriptionCancelAtPeriodEnd(ctx context.Context, arg SetSubscriptionCancelAtPeriodEndParams) (Subscription, error)
	TouchAdminSession(ctx context.Context, id uuid.UUID) error
	TouchUserSession(ctx context.Context, id uuid.UUID) error
	TouchUserTicket(ctx context.Context, arg TouchUserTicketParams) error
	UpdateAdminLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateOperationProgress(ctx context.Context, arg UpdateOperationProgressParams) (Operation, error)
	UpdateOperationStep(ctx context.Context, arg UpdateOperationStepParams) (OperationStep, error)
	UpdateSubscriptionLifecycle(ctx context.Context, arg UpdateSubscriptionLifecycleParams) (Subscription, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpsertAdminTOTPSecret(ctx context.Context, arg UpsertAdminTOTPSecretParams) error
}

var _ Querier = (*Queries)(nil)
