// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimSubscriptionsForLifecycle = `-- name: ClaimSubscriptionsForLifecycle :many
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
WHERE (status = 'active' AND current_period_end IS NOT NULL AND current_period_end <= $1)
   OR (status = 'past_due' AND grace_until IS NOT NULL AND grace_until <= $1)
ORDER BY COALESCE(grace_until, current_period_end), id
FOR UPDATE SKIP LOCKED
LIMIT $2
`

type ClaimSubscriptionsForLifecycleParams struct {
	CurrentPeriodEnd pgtype.Timestamptz `json:"current_period_end"`
	Limit            int32              `json:"limit"`
}

func (q *Queries) ClaimSubscriptionsForLifecycle(ctx context.Context, arg ClaimSubscriptionsForLifecycleParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, claimSubscriptionsForLifecycle, arg.CurrentPeriodEnd, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StartedAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextDueAt,
			&i.GraceUntil,
			&i.CancelAtPeriodEnd,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionForRenewal = `-- name: GetSubscriptionForRenewal :one
SELECT subscriptions.id, subscriptions.user_id, subscriptions.plan_id, subscriptions.status, subscriptions.billing_cycle, subscriptions.price_minor, subscriptions.currency, subscriptions.started_at, subscriptions.current_period_start, subscriptions.current_period_end, subscriptions.next_due_at, subscriptions.grace_until, subscriptions.cancel_at_period_end, subscriptions.ended_at, subscriptions.version, subscriptions.created_at, subscriptions.updated_at, plans.slug AS plan_slug, plans.name_i18n AS plan_name_i18n,
       products.id AS product_id, products.slug AS product_slug,
       products.name_i18n AS product_name_i18n, products.description_i18n AS product_description_i18n
FROM subscriptions
JOIN plans ON plans.id = subscriptions.plan_id
JOIN products ON products.id = plans.product_id
WHERE subscriptions.id = $1 AND subscriptions.user_id = $2
FOR UPDATE OF subscriptions
`

type GetSubscriptionForRenewalParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetSubscriptionForRenewalRow struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	PlanID                 uuid.UUID          `json:"plan_id"`
	Status                 string             `json:"status"`
	BillingCycle           string             `json:"billing_cycle"`
	PriceMinor             int64              `json:"price_minor"`
	Currency               string             `json:"currency"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	CurrentPeriodStart     pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
	NextDueAt              pgtype.Timestamptz `json:"next_due_at"`
	GraceUntil             pgtype.Timestamptz `json:"grace_until"`
	CancelAtPeriodEnd      bool               `json:"cancel_at_period_end"`
	EndedAt                pgtype.Timestamptz `json:"ended_at"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	PlanSlug               string             `json:"plan_slug"`
	PlanNameI18n           []byte             `json:"plan_name_i18n"`
	ProductID              uuid.UUID          `json:"product_id"`
	ProductSlug            string             `json:"product_slug"`
	ProductNameI18n        []byte             `json:"product_name_i18n"`
	ProductDescriptionI18n []byte             `json:"product_description_i18n"`
}

func (q *Queries) GetSubscriptionForRenewal(ctx context.Context, arg GetSubscriptionForRenewalParams) (GetSubscriptionForRenewalRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForRenewal, arg.ID, arg.UserID)
	var i GetSubscriptionForRenewalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanSlug,
		&i.PlanNameI18n,
		&i.ProductID,
		&i.ProductSlug,
		&i.ProductNameI18n,
		&i.ProductDescriptionI18n,
	)
	return i, err
}

const listSubscriptionsByUser = `-- name: ListSubscriptionsByUser :many
SELECT subscriptions.id, subscriptions.user_id, subscriptions.plan_id, subscriptions.status, subscriptions.billing_cycle, subscriptions.price_minor, subscriptions.currency, subscriptions.started_at, subscriptions.current_period_start, subscriptions.current_period_end, subscriptions.next_due_at, subscriptions.grace_until, subscriptions.cancel_at_period_end, subscriptions.ended_at, subscriptions.version, subscriptions.created_at, subscriptions.updated_at, plans.slug AS plan_slug, plans.name_i18n AS plan_name_i18n
FROM subscriptions
JOIN plans ON plans.id = subscriptions.plan_id
WHERE subscriptions.user_id = $1
ORDER BY subscriptions.created_at DESC
`

type ListSubscriptionsByUserRow struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	PlanID             uuid.UUID          `json:"plan_id"`
	Status             string             `json:"status"`
	BillingCycle       string             `json:"billing_cycle"`
	PriceMinor         int64              `json:"price_minor"`
	Currency           string             `json:"currency"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
	GraceUntil         pgtype.Timestamptz `json:"grace_until"`
	CancelAtPeriodEnd  bool               `json:"cancel_at_period_end"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
	Version            int64              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	PlanSlug           string             `json:"plan_slug"`
	PlanNameI18n       []byte             `json:"plan_name_i18n"`
}

func (q *Queries) ListSubscriptionsByUser(ctx context.Context, userID uuid.UUID) ([]ListSubscriptionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsByUserRow{}
	for rows.Next() {
		var i ListSubscriptionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StartedAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextDueAt,
			&i.GraceUntil,
			&i.CancelAtPeriodEnd,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanSlug,
			&i.PlanNameI18n,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSubscriptionByID = `-- name: LockSubscriptionByID :one
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, lockSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockSubscriptionByUser = `-- name: LockSubscriptionByUser :one
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type LockSubscriptionByUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) LockSubscriptionByUser(ctx context.Context, arg LockSubscriptionByUserParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, lockSubscriptionByUser, arg.ID, arg.UserID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renewSubscriptionAfterPayment = `-- name: RenewSubscriptionAfterPayment :one
UPDATE subscriptions
SET status = 'active',
    started_at = COALESCE(started_at, $2),
    current_period_start = CASE
      WHEN current_period_end IS NULL OR current_period_end <= $2 THEN $2
      ELSE current_period_start
    END,
    current_period_end = GREATEST(COALESCE(current_period_end, $2), $2) + CASE billing_cycle
      WHEN 'monthly' THEN interval '1 month'
      WHEN 'quarterly' THEN interval '3 months'
      WHEN 'yearly' THEN interval '1 year'
    END,
    next_due_at = GREATEST(COALESCE(current_period_end, $2), $2) + CASE billing_cycle
      WHEN 'monthly' THEN interval '1 month'
      WHEN 'quarterly' THEN interval '3 months'
      WHEN 'yearly' THEN interval '1 year'
    END,
    grace_until = NULL,
    cancel_at_period_end = false,
    ended_at = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
`

type RenewSubscriptionAfterPaymentParams struct {
	ID        uuid.UUID          `json:"id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) RenewSubscriptionAfterPayment(ctx context.Context, arg RenewSubscriptionAfterPaymentParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, renewSubscriptionAfterPayment, arg.ID, arg.StartedAt)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSubscriptionCancelAtPeriodEnd = `-- name: SetSubscriptionCancelAtPeriodEnd :one
UPDATE subscriptions
SET cancel_at_period_end = $2, version = version + 1, updated_at = now()
WHERE id = $1
RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
`

type SetSubscriptionCancelAtPeriodEndParams struct {
	ID                uuid.UUID `json:"id"`
	CancelAtPeriodEnd bool      `json:"cancel_at_period_end"`
}

func (q *Queries) SetSubscriptionCancelAtPeriodEnd(ctx context.Context, arg SetSubscriptionCancelAtPeriodEndParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, setSubscriptionCancelAtPeriodEnd, arg.ID, arg.CancelAtPeriodEnd)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionLifecycle = `-- name: UpdateSubscriptionLifecycle :one
UPDATE subscriptions
SET status = $2,
    grace_until = $3,
    ended_at = $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND version = $5
RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
`

type UpdateSubscriptionLifecycleParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     string             `json:"status"`
	GraceUntil pgtype.Timestamptz `json:"grace_until"`
	EndedAt    pgtype.Timestamptz `json:"ended_at"`
	Version    int64              `json:"version"`
}

func (q *Queries) UpdateSubscriptionLifecycle(ctx context.Context, arg UpdateSubscriptionLifecycleParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionLifecycle,
		arg.ID,
		arg.Status,
		arg.GraceUntil,
		arg.EndedAt,
		arg.Version,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
